// Code generated by temporalgen. DO NOT EDIT.

package order

import (
	"context"
	"fmt"

	"go.temporal.io/sdk/activity"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"

	"github.com/mixofreality-studio/archistrator-platform/framework-go-app-generator/internal/sample/internal/resourceaccess/orderstate"
)

// genActivities hosts one Temporal Activity per operation of each
// ResourceAccess component dependency — the manager's architecture-approved
// call surface. Fields are the contract interfaces, threaded by RegisterWorker.
type genActivities struct {
	OrderState orderstate.Access
}

// genActivityIdempotencyKey derives the run-scoped 3-part key
// workflowID:runID:activityID (stable per logical write within a run,
// distinct across runs of the same workflow ID).
func genActivityIdempotencyKey(ctx context.Context) fwra.IdempotencyKey {
	info := activity.GetInfo(ctx)
	return fwra.IdempotencyKey(fmt.Sprintf("%s:%s:%s",
		info.WorkflowExecution.ID, info.WorkflowExecution.RunID, info.ActivityID))
}

// OrderStateArchiveOrder wraps orderStateAccess.archiveOrder.
// Registered as "orderStateAccess.archiveOrder".
func (a *genActivities) OrderStateArchiveOrder(ctx context.Context, orderID orderstate.OrderID, expectedVersion orderstate.Version) (orderstate.Version, error) {
	v, err := a.OrderState.ArchiveOrder(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, orderID, expectedVersion, genActivityIdempotencyKey(ctx))
	return v, fwmanager.MapError(err)
}

// OrderStateCancelOrder wraps orderStateAccess.cancelOrder.
// Registered as "orderStateAccess.cancelOrder".
func (a *genActivities) OrderStateCancelOrder(ctx context.Context, orderID orderstate.OrderID, expectedVersion orderstate.Version, reason string) (orderstate.Version, error) {
	v, err := a.OrderState.CancelOrder(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, orderID, expectedVersion, reason)
	return v, fwmanager.MapError(err)
}

// OrderStateChargeOrder wraps orderStateAccess.chargeOrder.
// Registered as "orderStateAccess.chargeOrder".
func (a *genActivities) OrderStateChargeOrder(ctx context.Context, key fwra.IdempotencyKey, orderID orderstate.OrderID, amountCents int) (orderstate.Version, error) {
	v, err := a.OrderState.ChargeOrder(fwra.Context{Context: ctx, IdempotencyKey: key}, orderID, amountCents, key)
	return v, fwmanager.MapError(err)
}

// OrderStatePurgeOrder wraps orderStateAccess.purgeOrder.
// Registered as "orderStateAccess.purgeOrder".
func (a *genActivities) OrderStatePurgeOrder(ctx context.Context, orderID orderstate.OrderID) error {
	err := a.OrderState.PurgeOrder(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, orderID)
	return fwmanager.MapError(err)
}

// OrderStatePutOrder wraps orderStateAccess.putOrder.
// Registered as "orderStateAccess.putOrder".
func (a *genActivities) OrderStatePutOrder(ctx context.Context, orderID orderstate.OrderID, expectedVersion orderstate.Version, order orderstate.Order) (orderstate.Version, error) {
	v, err := a.OrderState.PutOrder(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, orderID, expectedVersion, order)
	return v, fwmanager.MapError(err)
}

// OrderStateReadOrder wraps orderStateAccess.readOrder.
// Registered as "orderStateAccess.readOrder".
func (a *genActivities) OrderStateReadOrder(ctx context.Context, orderID orderstate.OrderID) (orderstate.Order, error) {
	v, err := a.OrderState.ReadOrder(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, orderID)
	return v, fwmanager.MapError(err)
}

// OrderStateReceiptForOrder wraps orderStateAccess.receiptForOrder.
// Registered as "orderStateAccess.receiptForOrder".
func (a *genActivities) OrderStateReceiptForOrder(ctx context.Context, orderID orderstate.OrderID) (orderstate.OrderReceipt, error) {
	v, err := a.OrderState.ReceiptForOrder(fwra.Context{Context: ctx, IdempotencyKey: genActivityIdempotencyKey(ctx)}, orderID)
	return v, fwmanager.MapError(err)
}
