// Code generated by modelgen. DO NOT EDIT.

package stateaccessfake

import "example.com/alignapp/internal/resourceaccess/stateaccess"

// FakeStateAccess is a generated test double for stateaccess.StateAccess. It
// imports its sibling contract package — a same-ResourceAccess-layer edge — to
// prove the arch.Check exemption also holds when methodcheck.Check drives
// arch.Check over this shared fixture, and to prove absorbOwnedPackages already
// folds a <component>/fake sub-package under its owning StateAccess component
// instead of flagging it ALIGN-EXTRA-PKG.
type FakeStateAccess struct {
	Access stateaccess.StateAccess
}
