// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package widgetfake

import (
	"github.com/mixofreality-studio/archistrator-platform/framework-go-app-generator/internal/sample/fakeproof/internal/resourceaccess/widget"
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
)

// FakeWidgetAccess is a generated test double for widget.WidgetAccess: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeWidgetAccess struct {
	GetWidgetFn    func(rc fwra.Context, id widget.WidgetID) (widget.Widget, error)
	DeleteWidgetFn func(rc fwra.Context, id widget.WidgetID) error
	FindWidgetsFn  func(rc fwra.Context, filter *widget.WidgetFilter) ([]widget.WidgetID, error)
}

func (f *FakeWidgetAccess) GetWidget(rc fwra.Context, id widget.WidgetID) (widget.Widget, error) {
	if f.GetWidgetFn == nil {
		panic("FakeWidgetAccess.GetWidgetFn not set")
	}
	return f.GetWidgetFn(rc, id)
}

func (f *FakeWidgetAccess) DeleteWidget(rc fwra.Context, id widget.WidgetID) error {
	if f.DeleteWidgetFn == nil {
		panic("FakeWidgetAccess.DeleteWidgetFn not set")
	}
	return f.DeleteWidgetFn(rc, id)
}

func (f *FakeWidgetAccess) FindWidgets(rc fwra.Context, filter *widget.WidgetFilter) ([]widget.WidgetID, error) {
	if f.FindWidgetsFn == nil {
		panic("FakeWidgetAccess.FindWidgetsFn not set")
	}
	return f.FindWidgetsFn(rc, filter)
}

var _ widget.WidgetAccess = (*FakeWidgetAccess)(nil)
