// Code generated by framework-go-http-generator. DO NOT EDIT.
// Source contract: archistrator://contract/systemdesign

package systemdesign

import (
	"encoding/json"
	"errors"
	"net/http"
	"strconv"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go-http-generator/internal/stub/manager"
	"github.com/mixofreality-studio/archistrator-platform/framework-go-http-generator/internal/stub/security"
	mgr "github.com/mixofreality-studio/archistrator-platform/framework-go-http-generator/internal/stub/systemdesignmgr"
)

// Handler binds the SystemDesignManager manager to HTTP per the archistrator client convention.
type Handler struct {
	Manager  mgr.SystemDesignManager
	Security security.Security
}

// Register mounts every operation route on mux.
func (h *Handler) Register(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/v1/system-design/advance-phase/{projectID}", h.handleAdvancePhase)
	mux.HandleFunc("GET /api/v1/system-design/get-session-state/{projectID}", h.handleGetSessionState)
	mux.HandleFunc("POST /api/v1/system-design/request-artifact-draft/{projectID}", h.handleRequestArtifactDraft)
	mux.HandleFunc("POST /api/v1/system-design/set-research-input/{projectID}", h.handleSetResearchInput)
	mux.HandleFunc("POST /api/v1/system-design/start-system-design/{projectID}", h.handleStartSystemDesign)
	mux.HandleFunc("POST /api/v1/system-design/submit-review-decision/{projectID}", h.handleSubmitReviewDecision)
}

type requestArtifactDraftRequest struct {
	Kind     mgr.ArtifactKind    `json:"kind"`
	Feedback *mgr.ReviewFeedback `json:"feedback"`
}

type setResearchInputRequest struct {
	Research mgr.ResearchInput `json:"research"`
}

type submitReviewDecisionRequest struct {
	Kind     mgr.ArtifactKind    `json:"kind"`
	Decision mgr.ReviewDecision  `json:"decision"`
	Feedback *mgr.ReviewFeedback `json:"feedback"`
}

// handleAdvancePhase binds POST /api/v1/system-design/advance-phase/{projectID} -> mgr.AdvancePhase.
func (h *Handler) handleAdvancePhase(w http.ResponseWriter, r *http.Request) {
	projectID := mgr.ProjectID(r.PathValue("projectID"))
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "advance-phase"},
		security.ResourceRef{Kind: "project", ID: string(projectID)})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.AdvancePhase(rc, projectID)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleGetSessionState binds GET /api/v1/system-design/get-session-state/{projectID} -> mgr.GetSessionState.
func (h *Handler) handleGetSessionState(w http.ResponseWriter, r *http.Request) {
	projectID := mgr.ProjectID(r.PathValue("projectID"))
	kindInt, err := strconv.Atoi(r.URL.Query().Get("kind"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid kind: "+err.Error())
		return
	}
	kind := mgr.ArtifactKind(kindInt)
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "get-session-state"},
		security.ResourceRef{Kind: "project", ID: string(projectID)})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.GetSessionState(rc, projectID, kind)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleRequestArtifactDraft binds POST /api/v1/system-design/request-artifact-draft/{projectID} -> mgr.RequestArtifactDraft.
func (h *Handler) handleRequestArtifactDraft(w http.ResponseWriter, r *http.Request) {
	projectID := mgr.ProjectID(r.PathValue("projectID"))
	var req requestArtifactDraftRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "request-artifact-draft"},
		security.ResourceRef{Kind: "project", ID: string(projectID)})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.RequestArtifactDraft(rc, projectID, req.Kind, req.Feedback)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleSetResearchInput binds POST /api/v1/system-design/set-research-input/{projectID} -> mgr.SetResearchInput.
func (h *Handler) handleSetResearchInput(w http.ResponseWriter, r *http.Request) {
	projectID := mgr.ProjectID(r.PathValue("projectID"))
	var req setResearchInputRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "set-research-input"},
		security.ResourceRef{Kind: "project", ID: string(projectID)})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.SetResearchInput(rc, projectID, req.Research)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleStartSystemDesign binds POST /api/v1/system-design/start-system-design/{projectID} -> mgr.StartSystemDesign.
func (h *Handler) handleStartSystemDesign(w http.ResponseWriter, r *http.Request) {
	projectID := mgr.ProjectID(r.PathValue("projectID"))
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "start-system-design"},
		security.ResourceRef{Kind: "project", ID: string(projectID)})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.StartSystemDesign(rc, projectID)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleSubmitReviewDecision binds POST /api/v1/system-design/submit-review-decision/{projectID} -> mgr.SubmitReviewDecision.
func (h *Handler) handleSubmitReviewDecision(w http.ResponseWriter, r *http.Request) {
	projectID := mgr.ProjectID(r.PathValue("projectID"))
	var req submitReviewDecisionRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "submit-review-decision"},
		security.ResourceRef{Kind: "project", ID: string(projectID)})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	if err := h.Manager.SubmitReviewDecision(rc, projectID, req.Kind, req.Decision, req.Feedback); err != nil {
		writeManagerError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// --- response helpers ------------------------------------------------------

type errorResponse struct {
	Error string `json:"error"`
	Code  string `json:"code"`
}

func decodeJSON(w http.ResponseWriter, r *http.Request, dst any) bool {
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(dst); err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid JSON body: "+err.Error())
		return false
	}
	return true
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeError(w http.ResponseWriter, status int, code, detail string) {
	writeJSON(w, status, errorResponse{Error: detail, Code: code})
}

// writeManagerError maps a framework-go manager.Error to its HTTP status; any
// other error is a non-leaking 500.
func writeManagerError(w http.ResponseWriter, err error) {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		writeError(w, statusForKind(me.Kind), codeForKind(me.Kind), me.Detail)
		return
	}
	writeError(w, http.StatusInternalServerError, "internal", "internal error")
}

func statusForKind(kind fwmanager.Kind) int {
	switch kind {
	case fwmanager.ContractMisuse:
		return http.StatusBadRequest
	case fwmanager.NotFound:
		return http.StatusNotFound
	case fwmanager.Unauthorized:
		return http.StatusForbidden
	case fwmanager.FailedPrecondition:
		return http.StatusConflict
	case fwmanager.Infrastructure:
		return http.StatusServiceUnavailable
	default:
		return http.StatusInternalServerError
	}
}

func codeForKind(kind fwmanager.Kind) string {
	switch kind {
	case fwmanager.ContractMisuse:
		return "contract_misuse"
	case fwmanager.NotFound:
		return "not_found"
	case fwmanager.Unauthorized:
		return "forbidden"
	case fwmanager.FailedPrecondition:
		return "failed_precondition"
	case fwmanager.Infrastructure:
		return "infrastructure"
	default:
		return "internal"
	}
}
