// Code generated by cmd/clientgen (mcpemit). DO NOT EDIT.
// Source contract:

package construction

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	mgr "github.com/mixofreality-studio/archistrator/server/internal/manager/construction"
)

// Handler binds the ConstructionManager manager to MCP tools.
type Handler struct {
	Manager mgr.ConstructionManager
}

// Register adds every operation as an mcp.Tool on srv, each carrying an
// explicit human description and an explicit input JSON Schema (enum values +
// meanings, REST-matching optionality) so an agentic consumer needs no source.
func (h *Handler) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionExecuteNextActivity", Description: "Advance construction by one tick: dispatch the next ready activity (or continue an in-flight one) along the project network. tickID correlates this request; the pump is one per project — a call while it runs joins it.", InputSchema: executeNextActivityInputSchema(), OutputSchema: executeNextActivityOutputSchema()}, h.handleExecuteNextActivity)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionGetSessionState", Description: "Return construction progress. With no activityID, the whole-network state; with an activityID, that one activity's detailed lifecycle, build, and review state. Read-only.", InputSchema: getSessionStateInputSchema(), OutputSchema: getSessionStateOutputSchema()}, h.handleGetSessionState)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionOverrideActivity", Description: "Steer one construction activity that is waiting at an escalation (session stage awaitingTakeover): retry it, skip it, take it over, or reassign it. Notes are required. Refused as FailedPrecondition while the activity is not awaiting a takeover.", InputSchema: overrideActivityInputSchema(), OutputSchema: overrideActivityOutputSchema()}, h.handleOverrideActivity)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionPauseProject", Description: "Pause the construction pump for a project so no further activities dispatch until it is resumed. reason is recorded for the audit trail.", InputSchema: pauseProjectInputSchema(), OutputSchema: pauseProjectOutputSchema()}, h.handlePauseProject)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionRunReplanSweep", Description: "Run the re-plan sweep that detects scope or variance drift and re-derives the project network. With no projectID it sweeps every active project; tickID idempotently identifies the sweep.", InputSchema: runReplanSweepInputSchema(), OutputSchema: runReplanSweepOutputSchema()}, h.handleRunReplanSweep)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionSetReviewPolicy", Description: "Set the project's construction review-policy preset: vibes (auto-approve everything short of the deploy/spend/schema risk floor), checkpoints (approval at the contract commit + construction dispatch + merge), or full (approval at every step). Any other preset value is rejected.", InputSchema: setReviewPolicyInputSchema(), OutputSchema: setReviewPolicyOutputSchema()}, h.handleSetReviewPolicy)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionSubmitPhaseDecision", Description: "Record a review verdict (approve or send-back) for the gate an activity is waiting at: a lifecycle phase, or \"merge\" for the local merge hold (approve only). Send-back must carry feedback notes. Refused as FailedPrecondition unless the activity's session is awaiting exactly that gate, and for a send-back at a gate whose redraft budget is spent.", InputSchema: submitPhaseDecisionInputSchema(), OutputSchema: submitPhaseDecisionOutputSchema()}, h.handleSubmitPhaseDecision)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionUpdateReviewPolicy", Description: "Replace the construction review-routing policy (which reviewers gate which produced artifacts) for a project.", InputSchema: updateReviewPolicyInputSchema(), OutputSchema: updateReviewPolicyOutputSchema()}, h.handleUpdateReviewPolicy)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionListEpisodesForActivity", Description: "List the agentic episode records (dispatch runs, or gaps) captured against one construction activity. Read-only.", InputSchema: listEpisodesForActivityInputSchema(), OutputSchema: listEpisodesForActivityOutputSchema()}, h.handleListEpisodesForActivity)
	mcp.AddTool(srv, &mcp.Tool{Name: "constructionGetEpisodeTimeline", Description: "Return one agentic episode's full timeline: its record (usage, cost, outcome, lineage) plus the sequenced trace events mined from its run. Read-only.", InputSchema: getEpisodeTimelineInputSchema(), OutputSchema: getEpisodeTimelineOutputSchema()}, h.handleGetEpisodeTimeline)
}

type executeNextActivityInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
	TickID    string        `json:"tickID"`
}

type executeNextActivityOutput struct {
	Result mgr.PumpResult `json:"result"`
}

type getSessionStateInput struct {
	ProjectID  mgr.ProjectID   `json:"projectID"`
	ActivityID *mgr.ActivityID `json:"activityID,omitempty"`
}

type getSessionStateOutput struct {
	Result mgr.ConstructionSessionView `json:"result"`
}

type overrideActivityInput struct {
	ProjectID  mgr.ProjectID        `json:"projectID"`
	ActivityID mgr.ActivityID       `json:"activityID"`
	Override   mgr.ActivityOverride `json:"override"`
}

type overrideActivityOutput struct{}

type pauseProjectInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
	Reason    string        `json:"reason"`
}

type pauseProjectOutput struct{}

type runReplanSweepInput struct {
	ProjectID *mgr.ProjectID `json:"projectID,omitempty"`
	TickID    string         `json:"tickID"`
}

type runReplanSweepOutput struct {
	Result mgr.ReplanSweepResult `json:"result"`
}

type setReviewPolicyInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
	Preset    string        `json:"preset"`
}

type setReviewPolicyOutput struct{}

type submitPhaseDecisionInput struct {
	ProjectID  mgr.ProjectID       `json:"projectID"`
	ActivityID mgr.ActivityID      `json:"activityID"`
	Phase      string              `json:"phase"`
	Decision   mgr.PhaseDecision   `json:"decision"`
	Feedback   *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type submitPhaseDecisionOutput struct{}

type updateReviewPolicyInput struct {
	ProjectID mgr.ProjectID         `json:"projectID"`
	Policy    mgr.ReviewPolicyInput `json:"policy"`
}

type updateReviewPolicyOutput struct{}

type listEpisodesForActivityInput struct {
	ProjectID  mgr.ProjectID `json:"projectID"`
	ActivityID string        `json:"activityID"`
}

type listEpisodesForActivityOutput struct {
	Result []mgr.EpisodeRecordView `json:"result"`
}

type getEpisodeTimelineInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
	EpisodeID string        `json:"episodeID"`
}

type getEpisodeTimelineOutput struct {
	Result mgr.EpisodeTimeline `json:"result"`
}

// executeNextActivityInputSchema is the explicit MCP input schema for the ExecuteNextActivity operation.
func executeNextActivityInputSchema() *jsonschema.Schema {
	s := objectSchema[executeNextActivityInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "tickID"}
	return s
}

// getSessionStateInputSchema is the explicit MCP input schema for the GetSessionState operation.
func getSessionStateInputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID"}
	return s
}

// overrideActivityInputSchema is the explicit MCP input schema for the OverrideActivity operation.
func overrideActivityInputSchema() *jsonschema.Schema {
	s := objectSchema[overrideActivityInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "activityID", "override"}
	return s
}

// pauseProjectInputSchema is the explicit MCP input schema for the PauseProject operation.
func pauseProjectInputSchema() *jsonschema.Schema {
	s := objectSchema[pauseProjectInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "reason"}
	return s
}

// runReplanSweepInputSchema is the explicit MCP input schema for the RunReplanSweep operation.
func runReplanSweepInputSchema() *jsonschema.Schema {
	s := objectSchema[runReplanSweepInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"tickID"}
	return s
}

// setReviewPolicyInputSchema is the explicit MCP input schema for the SetReviewPolicy operation.
func setReviewPolicyInputSchema() *jsonschema.Schema {
	s := objectSchema[setReviewPolicyInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "preset"}
	return s
}

// submitPhaseDecisionInputSchema is the explicit MCP input schema for the SubmitPhaseDecision operation.
func submitPhaseDecisionInputSchema() *jsonschema.Schema {
	s := objectSchema[submitPhaseDecisionInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "activityID", "phase", "decision"}
	s.Properties["decision"] = enumSchemaPhaseDecision()
	return s
}

// updateReviewPolicyInputSchema is the explicit MCP input schema for the UpdateReviewPolicy operation.
func updateReviewPolicyInputSchema() *jsonschema.Schema {
	s := objectSchema[updateReviewPolicyInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "policy"}
	return s
}

// listEpisodesForActivityInputSchema is the explicit MCP input schema for the ListEpisodesForActivity operation.
func listEpisodesForActivityInputSchema() *jsonschema.Schema {
	s := objectSchema[listEpisodesForActivityInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "activityID"}
	return s
}

// getEpisodeTimelineInputSchema is the explicit MCP input schema for the GetEpisodeTimeline operation.
func getEpisodeTimelineInputSchema() *jsonschema.Schema {
	s := objectSchema[getEpisodeTimelineInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "episodeID"}
	return s
}

// executeNextActivityOutputSchema is the explicit MCP output schema for the ExecuteNextActivity operation.
func executeNextActivityOutputSchema() *jsonschema.Schema {
	s := objectSchema[executeNextActivityOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[executeNextActivityOutput]())
	return s
}

// getSessionStateOutputSchema is the explicit MCP output schema for the GetSessionState operation.
func getSessionStateOutputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[getSessionStateOutput]())
	return s
}

// overrideActivityOutputSchema is the explicit MCP output schema for the OverrideActivity operation.
func overrideActivityOutputSchema() *jsonschema.Schema {
	s := objectSchema[overrideActivityOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[overrideActivityOutput]())
	return s
}

// pauseProjectOutputSchema is the explicit MCP output schema for the PauseProject operation.
func pauseProjectOutputSchema() *jsonschema.Schema {
	s := objectSchema[pauseProjectOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[pauseProjectOutput]())
	return s
}

// runReplanSweepOutputSchema is the explicit MCP output schema for the RunReplanSweep operation.
func runReplanSweepOutputSchema() *jsonschema.Schema {
	s := objectSchema[runReplanSweepOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[runReplanSweepOutput]())
	return s
}

// setReviewPolicyOutputSchema is the explicit MCP output schema for the SetReviewPolicy operation.
func setReviewPolicyOutputSchema() *jsonschema.Schema {
	s := objectSchema[setReviewPolicyOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[setReviewPolicyOutput]())
	return s
}

// submitPhaseDecisionOutputSchema is the explicit MCP output schema for the SubmitPhaseDecision operation.
func submitPhaseDecisionOutputSchema() *jsonschema.Schema {
	s := objectSchema[submitPhaseDecisionOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[submitPhaseDecisionOutput]())
	return s
}

// updateReviewPolicyOutputSchema is the explicit MCP output schema for the UpdateReviewPolicy operation.
func updateReviewPolicyOutputSchema() *jsonschema.Schema {
	s := objectSchema[updateReviewPolicyOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[updateReviewPolicyOutput]())
	return s
}

// listEpisodesForActivityOutputSchema is the explicit MCP output schema for the ListEpisodesForActivity operation.
func listEpisodesForActivityOutputSchema() *jsonschema.Schema {
	s := objectSchema[listEpisodesForActivityOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[listEpisodesForActivityOutput]())
	return s
}

// getEpisodeTimelineOutputSchema is the explicit MCP output schema for the GetEpisodeTimeline operation.
func getEpisodeTimelineOutputSchema() *jsonschema.Schema {
	s := objectSchema[getEpisodeTimelineOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[getEpisodeTimelineOutput]())
	return s
}

// contractFieldDescriptions is the contract's own property documentation,
// keyed by the Go type modelgen emits for each documenting $def. modelgen
// carries no description into those types, so the inferred output schema
// would otherwise show an agent a field's shape but never the contract's
// statement of when that field means nothing.
var contractFieldDescriptions = map[reflect.Type]map[string]string{
	reflect.TypeFor[mgr.ConstructionSessionView](): {
		"attempt":          "The current supervision attempt, 1-based: a variance retry, an operator Retry and an escalation's re-dispatch each start the next one. 0 before the first attempt and on the project-level view.",
		"attemptBudget":    "How many supervision attempts the activity gets before it fails with VarianceExhausted, so a client never hardcodes the number. 0 on the project-level view.",
		"awaitingGate":     "The gate this activity is waiting at, set only while stage is awaitingApproval or awaitingTakeover: a lifecycle phase's wire name (requirements, detailed_design, test_plan, construction or integration) for a phase approval gate, \"merge\" for the local merge hold, or \"takeover\" for an escalation. It is the key a decision must address. Omitted in every other stage and on the project-level view.",
		"awaitingSince":    "When this occurrence of the human stage began, in workflow time. A send-back's redraft re-enters its gate with a new awaitingSince, so the pair (awaitingGate, awaitingSince) identifies one gate occurrence. Omitted whenever awaitingGate is.",
		"awaitingUntil":    "When an escalation stops waiting and fails the activity: awaitingSince plus the escalation-wait window. Omitted for phase approval gates and the merge hold, and for an escalation that waits indefinitely.",
		"redraftExhausted": "True when the phase gate this activity is waiting at can take no further SendBack redraft: a gate redrafts at most 4 times and refuses the fifth send-back, so approve it, or steer the activity with OverrideActivity. Recomputed on entry to every gate; false at the merge hold and at an escalation.",
	},
}

// describeContractFields stamps contractFieldDescriptions onto an inferred
// schema, walking it in step with the Go type it was inferred from, so a
// description lands only on the property the contract documents — wherever
// that type appears in the output (a map value, a slice element, a field).
// It runs LAST: relaxRawJSON may replace a node wholesale, and a description
// written before that would be lost with it.
func describeContractFields(s *jsonschema.Schema, t reflect.Type) {
	if s == nil {
		return
	}
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	k := t.Kind()
	if k == reflect.Slice || k == reflect.Array {
		describeContractFields(s.Items, t.Elem())
		return
	}
	if k == reflect.Map {
		describeContractFields(s.AdditionalProperties, t.Elem())
		return
	}
	if k != reflect.Struct {
		return
	}
	descs := contractFieldDescriptions[t]
	for i := range t.NumField() {
		f := t.Field(i)
		name := jsonFieldName(f)
		p, ok := s.Properties[name]
		if name == "" || !ok {
			continue
		}
		if d, ok := descs[name]; ok {
			p.Description = d
		}
		describeContractFields(p, f.Type)
	}
}

// jsonFieldName is the wire key encoding/json uses for a struct field ("" for
// an unexported or json:"-" field, which no schema property stands for).
func jsonFieldName(f reflect.StructField) string {
	if !f.IsExported() {
		return ""
	}
	name, _, _ := strings.Cut(f.Tag.Get("json"), ",")
	switch name {
	case "-":
		return ""
	case "":
		return f.Name
	}
	return name
}

// enumSchemaPhaseDecision describes the PhaseDecision enum: its allowed values and their meanings.
func enumSchemaPhaseDecision() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2},
		Description: "PhaseDecision. Allowed values: 0=PhaseDecisionUnknown, 1=PhaseApprove, 2=PhaseSendBack.",
	}
}

// handleExecuteNextActivity is the MCP tool handler for the ExecuteNextActivity operation.
func (h *Handler) handleExecuteNextActivity(ctx context.Context, _ *mcp.CallToolRequest, in executeNextActivityInput) (*mcp.CallToolResult, executeNextActivityOutput, error) {
	var out executeNextActivityOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ExecuteNextActivity(rc, in.ProjectID, in.TickID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetSessionState is the MCP tool handler for the GetSessionState operation.
func (h *Handler) handleGetSessionState(ctx context.Context, _ *mcp.CallToolRequest, in getSessionStateInput) (*mcp.CallToolResult, getSessionStateOutput, error) {
	var out getSessionStateOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetSessionState(rc, in.ProjectID, in.ActivityID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleOverrideActivity is the MCP tool handler for the OverrideActivity operation.
func (h *Handler) handleOverrideActivity(ctx context.Context, _ *mcp.CallToolRequest, in overrideActivityInput) (*mcp.CallToolResult, overrideActivityOutput, error) {
	var out overrideActivityOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.OverrideActivity(rc, in.ProjectID, in.ActivityID, in.Override); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handlePauseProject is the MCP tool handler for the PauseProject operation.
func (h *Handler) handlePauseProject(ctx context.Context, _ *mcp.CallToolRequest, in pauseProjectInput) (*mcp.CallToolResult, pauseProjectOutput, error) {
	var out pauseProjectOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.PauseProject(rc, in.ProjectID, in.Reason); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleRunReplanSweep is the MCP tool handler for the RunReplanSweep operation.
func (h *Handler) handleRunReplanSweep(ctx context.Context, _ *mcp.CallToolRequest, in runReplanSweepInput) (*mcp.CallToolResult, runReplanSweepOutput, error) {
	var out runReplanSweepOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.RunReplanSweep(rc, in.ProjectID, in.TickID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSetReviewPolicy is the MCP tool handler for the SetReviewPolicy operation.
func (h *Handler) handleSetReviewPolicy(ctx context.Context, _ *mcp.CallToolRequest, in setReviewPolicyInput) (*mcp.CallToolResult, setReviewPolicyOutput, error) {
	var out setReviewPolicyOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SetReviewPolicy(rc, in.ProjectID, in.Preset); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleSubmitPhaseDecision is the MCP tool handler for the SubmitPhaseDecision operation.
func (h *Handler) handleSubmitPhaseDecision(ctx context.Context, _ *mcp.CallToolRequest, in submitPhaseDecisionInput) (*mcp.CallToolResult, submitPhaseDecisionOutput, error) {
	var out submitPhaseDecisionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SubmitPhaseDecision(rc, in.ProjectID, in.ActivityID, in.Phase, in.Decision, in.Feedback); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleUpdateReviewPolicy is the MCP tool handler for the UpdateReviewPolicy operation.
func (h *Handler) handleUpdateReviewPolicy(ctx context.Context, _ *mcp.CallToolRequest, in updateReviewPolicyInput) (*mcp.CallToolResult, updateReviewPolicyOutput, error) {
	var out updateReviewPolicyOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.UpdateReviewPolicy(rc, in.ProjectID, in.Policy); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleListEpisodesForActivity is the MCP tool handler for the ListEpisodesForActivity operation.
func (h *Handler) handleListEpisodesForActivity(ctx context.Context, _ *mcp.CallToolRequest, in listEpisodesForActivityInput) (*mcp.CallToolResult, listEpisodesForActivityOutput, error) {
	var out listEpisodesForActivityOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ListEpisodesForActivity(rc, in.ProjectID, in.ActivityID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetEpisodeTimeline is the MCP tool handler for the GetEpisodeTimeline operation.
func (h *Handler) handleGetEpisodeTimeline(ctx context.Context, _ *mcp.CallToolRequest, in getEpisodeTimelineInput) (*mcp.CallToolResult, getEpisodeTimelineOutput, error) {
	var out getEpisodeTimelineOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetEpisodeTimeline(rc, in.ProjectID, in.EpisodeID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// --- helpers ---------------------------------------------------------------

// objectSchema infers the base object JSON Schema for a tool input struct via
// the SDK's reflection (the same inference the SDK would run for a nil input
// schema), so nested object/array params keep their structural shape; callers
// then override the required list and any enum properties. It panics on an
// un-inferrable type — a build-time contract error surfaced at server start.
func objectSchema[T any]() *jsonschema.Schema {
	s, err := jsonschema.For[T](nil)
	if err != nil {
		panic(fmt.Sprintf("mcp input schema inference: %v", err))
	}
	if s.Properties == nil {
		s.Properties = map[string]*jsonschema.Schema{}
	}
	return s
}

// fixUUIDStrings walks an inferred schema and retypes every uuid.UUID ([16]byte)
// property from the SDK's structural inference (an array of 16 0-255 bytes) to
// the schema the value actually marshals as on the wire: a string in RFC 4122
// form. It MUST run before relaxRawJSON, which would otherwise blank the same
// node as an indistinguishable raw-byte-array signature (T11 finding).
func fixUUIDStrings(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isUUIDArray(s) {
		*s = jsonschema.Schema{Type: "string", Format: "uuid"}
		return
	}
	for _, p := range s.Properties {
		fixUUIDStrings(p)
	}
	fixUUIDStrings(s.Items)
	fixUUIDStrings(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		fixUUIDStrings(p)
	}
}

// isUUIDArray reports whether a schema is the jsonschema-go signature of a Go
// uuid.UUID ([16]byte): the same raw-byte-array shape as isRawByteArray, further
// narrowed to exactly 16 items (a fixed-size array), which is unique to UUIDs
// among this codebase's byte-carrier fields.
func isUUIDArray(s *jsonschema.Schema) bool {
	if !isRawByteArray(s) {
		return false
	}
	return s.MinItems != nil && *s.MinItems == 16 && s.MaxItems != nil && *s.MaxItems == 16
}

// relaxRawJSON walks an inferred schema and relaxes every json.RawMessage /
// []byte JSON-carrier property to a permissive (accept-anything) schema. The SDK
// infers such a Go field as an array of 0-255 bytes, which rejects the real JSON
// object/string the manager actually emits or accepts (QA finding F26); the rest
// of the inferred shape is preserved. The permissive schema carries a
// Description so it marshals as a JSON OBJECT (`{"description":...}`) rather
// than the zero-value Schema{}, which the library marshals as bare JSON `true`
// — valid JSON Schema, but rejected by the TS MCP SDK's Zod validator, which
// requires every property schema to be an object (T11 finding).
func relaxRawJSON(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isRawByteArray(s) {
		*s = jsonschema.Schema{Description: "any JSON value"}
		return
	}
	for _, p := range s.Properties {
		relaxRawJSON(p)
	}
	relaxRawJSON(s.Items)
	relaxRawJSON(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		relaxRawJSON(p)
	}
}

// isRawByteArray reports whether a schema is the jsonschema-go signature of a Go
// []byte / json.RawMessage: an array (possibly nullable) whose items are bytes
// (integer, 0..255).
func isRawByteArray(s *jsonschema.Schema) bool {
	isArray := s.Type == "array"
	for _, t := range s.Types {
		if t == "array" {
			isArray = true
		}
	}
	if !isArray || s.Items == nil {
		return false
	}
	it := s.Items
	if it.Type != "integer" {
		return false
	}
	return it.Minimum != nil && *it.Minimum == 0 && it.Maximum != nil && *it.Maximum == 255
}

// allowNullMaps walks an inferred schema and unions "null" into every Go-map
// node's type. jsonschema-go infers a Go map as a bare {type:"object"}, but a
// nil map marshals to JSON null (unlike a nil slice, which the library already
// types as ["null","array"]). Read models legitimately emit nil maps in early
// project phases (e.g. ProjectState.ActivityConstruction before construction),
// so the honest schema must accept null there — otherwise the SDK's output
// validation rejects a payload the HTTP surface serves fine (QA finding F29).
func allowNullMaps(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isMapNode(s) {
		s.Types = []string{"null", "object"}
		s.Type = ""
	}
	for _, p := range s.Properties {
		allowNullMaps(p)
	}
	allowNullMaps(s.Items)
	allowNullMaps(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		allowNullMaps(p)
	}
}

// isMapNode reports whether a schema node is jsonschema-go's inference of a Go
// map: an object node carrying an additionalProperties element schema. A struct
// is also typed "object" but sets additionalProperties to the false schema
// (Not set), which this distinguishes so struct nodes are never made nullable.
func isMapNode(s *jsonschema.Schema) bool {
	isObject := s.Type == "object"
	for _, t := range s.Types {
		if t == "object" {
			isObject = true
		}
	}
	ap := s.AdditionalProperties
	return isObject && ap != nil && ap.Not == nil
}

func mapManagerError(err error) error {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		return fmt.Errorf("%s: %s", me.Kind.String(), me.Detail)
	}
	return err
}
