// Code generated by testgen. DO NOT EDIT.
package goodeng_test

import (
	"testing"

	"example.com/layoutapp/internal/engine/goodeng"
)

func TestScenario_Compute(t *testing.T) {
	g := &goodeng.Engine{}
	if v, err := g.Compute(1); err != nil || v != 2 {
		t.Fatalf("Compute(1) = %d, %v", v, err)
	}
}
