// Code generated by testgen. DO NOT EDIT.
package goodmgr_test

import (
	"testing"

	"example.com/layoutapp/internal/manager/goodmgr"
)

// manager_scenarios.gen_test.go stands in for the testgen-emitted scenario
// file: black-box (package goodmgr_test) and correctly named — ".gen" marks it
// generated, "_test.go" keeps it a Go test file.
func TestScenario_Do(t *testing.T) {
	m := &goodmgr.Manager{}
	if err := m.Do(); err != nil {
		t.Fatal(err)
	}
}
