// Code generated by fakegen. DO NOT EDIT.

// Package fake is collabeng's generated test double. It is not a component
// package, so a hooks file may import it only when the consuming module names
// it in Spec.HooksImportAllowlist.
package fake

// FakeEngine stands in for collabeng.Engine.
type FakeEngine struct{ PriceResult int }

// Price returns the canned result.
func (f *FakeEngine) Price(int) (int, error) { return f.PriceResult, nil }
