package testgen

import (
	"encoding/json"
	"go/format"
	"maps"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/mixofreality-studio/archistrator-platform/framework-go/methodcheck"
)

const (
	toolsGen   = "internal/client/mcp/client_scenarios.gen_test.go"
	toolsHooks = "internal/client/mcp/client_hooks_test.go"
)

// fixtureDoc is the shared fixture decoded for mutation.
func fixtureDoc(t *testing.T) map[string]any {
	t.Helper()
	raw, err := os.ReadFile("testdata/project_tp.json")
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	return doc
}

func generateDoc(t *testing.T, doc map[string]any) (Output, error) {
	t.Helper()
	raw, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}
	return Generate(raw, Config{ModulePath: "example.com/app/server"})
}

// withShopTools adds an MCP client to the fixture (DCT §12 B1): component
// shop-tools, contract shopTools in internal/client/mcp with one op per
// generated tool (OrderGetOrder → tool orderGetOrder, OrderCancelOrder →
// orderCancelOrder), drawn into track-order's ask-order step ahead of the
// customer's own call, and a plan binding track-order-P1's one stimulus into
// shopTools — a direct tool call, a same-contract probe (inline) and a probe
// on orderManager (a hook).
func withShopTools(t *testing.T, doc map[string]any) {
	t.Helper()
	design := doc["slots"].(map[string]any)["5"].(map[string]any)["model"].(map[string]any)
	design["components"] = append(design["components"].([]any), map[string]any{
		"id": "shop-tools", "name": "ShopTools", "kind": "client", "layer": "client", "encapsulates": "", "atomicBusinessVerbs": nil,
	})
	for _, v := range design["dynamicViews"].([]any) {
		view := v.(map[string]any)
		if view["useCaseId"] != "track-order" {
			continue
		}
		step := view["steps"].([]any)[0].(map[string]any)
		step["calls"] = append([]any{map[string]any{"from": "customer", "to": "shop-tools", "mode": "sync", "label": "OrderGetOrder", "alt": nil}}, step["calls"].([]any)...)
	}
	orderID := map[string]any{"type": "string"}
	doc["serviceContracts"].(map[string]any)["shopTools"] = map[string]any{
		"component": "shopTools", "layer": "Client", "title": "shop MCP tools", "goPackage": "internal/client/mcp",
		"$defs": map[string]any{},
		"interface": map[string]any{"name": "ShopTools", "layer": "client", "operations": []any{
			map[string]any{"name": "OrderGetOrder", "params": []any{map[string]any{"name": "orderId", "schema": orderID}}, "result": map[string]any{"type": "object"}, "error": true},
			map[string]any{"name": "OrderCancelOrder", "params": []any{map[string]any{"name": "orderId", "schema": orderID}}, "error": true},
		}},
	}
	doc["phaseArtifacts"].(map[string]any)["testPlan"].(map[string]any)["shopTools"] = map[string]any{
		"component": "shopTools",
		"bindings": []any{map[string]any{"scenario": "track-order-P1", "skip": nil, "steps": []any{map[string]any{
			"seq": 1, "operation": "OrderGetOrder", "hook": false,
			"inputs": []any{map[string]any{"name": "orderId", "value": "o-1"}},
			"expect": map[string]any{"result": `{"result":{"state":"open"}}`, "errorExpected": false},
			"probes": []any{
				map[string]any{"for": "Order[open]", "component": "shopTools", "operation": "OrderGetOrder",
					"inputs": []any{map[string]any{"name": "orderId", "value": "o-1"}},
					"expect": map[string]any{"result": `{"result":{"id":"o-1"}}`, "errorExpected": false}},
				map[string]any{"for": "Order[open]", "component": "orderManager", "operation": "GetOrder",
					"inputs": []any{map[string]any{"name": "orderId", "value": "o-1"}},
					"expect": map[string]any{"result": `{"id":"o-1"}`, "errorExpected": false}},
			},
			"unobservable": []any{},
		}}}},
	}
}

func generateShopTools(t *testing.T) Output {
	t.Helper()
	doc := fixtureDoc(t)
	withShopTools(t, doc)
	out, err := generateDoc(t, doc)
	if err != nil {
		t.Fatal(err)
	}
	return out
}

// TestGenerate_MCPClientCallsToolsInProcess pins B1's MCP dialect: a client
// contract whose operations are tools gets a Go scenarios file in its
// goPackage that serves the hooks' generated tools handlers on an in-process
// MCP server and calls each bound op as the tool LowerFirst(op) over an
// in-memory transport — never a Playwright spec.
func TestGenerate_MCPClientCallsToolsInProcess(t *testing.T) {
	out := generateShopTools(t)
	src, ok := out.Generated[toolsGen]
	if !ok {
		t.Fatalf("missing %s; have %v", toolsGen, keys(out.Generated))
	}
	for _, want := range []string{
		"// Code generated by testgen. DO NOT EDIT.",
		"package mcp_test",
		"func TestMain(m *testing.M) { scenariohost.Main(m, \"shopTools\") }",
		"func TestScenario_track_order_P1(t *testing.T) {",
		"h.RunScenario(t, \"shopTools\", \"track-order-P1\", func(t *testing.T) {",
		"subject := serveTools(t, h, newSubject(t, h))",
		"// step 1: OrderGetOrder → tool orderGetOrder (node ask-order)",
		"out1, err1 := subject.Call(h.Context(t), \"orderGetOrder\", `{\"orderId\":\"o-1\"}`)",
		"expect(t, \"track-order-P1\", 1, out1, err1, `{\"result\":\"{\\\"result\\\":{\\\"state\\\":\\\"open\\\"}}\",\"errorExpected\":false}`)",
		// the same-contract probe is a tool call inline
		"pout1_1, perr1_1 := subject.Call(h.Context(t), \"orderGetOrder\", `{\"orderId\":\"o-1\"}`)",
		// a probe on another component is a hook
		"pout1_2, perr1_2 := probeTrackOrderP1S1N2(t, h, subject)",
		"\"github.com/modelcontextprotocol/go-sdk/mcp\"",
		"\"github.com/mixofreality-studio/archistrator-platform/framework-go-scenariohost\"",
		"type toolRegistrar interface {",
		"Register(srv *mcp.Server)",
		"type toolServer struct {",
		"type toolSession struct {",
		"func (s *toolSession) Call(ctx context.Context, name, args string) (any, error) {",
		"mcp.NewInMemoryTransports()",
		"res.IsError",
		"res.StructuredContent",
	} {
		if !strings.Contains(string(src), want) {
			t.Errorf("missing %q in\n%s", want, src)
		}
	}
	for _, bad := range []string{"example.com/app/server/internal/client/mcp\"", "callContext", "MainWithWorkflows"} {
		if strings.Contains(string(src), bad) {
			t.Errorf("an MCP client file must not carry %q:\n%s", bad, src)
		}
	}
	if _, err := format.Source(src); err != nil {
		t.Fatalf("not gofmt-able: %v", err)
	}
	for p := range out.Generated {
		if strings.Contains(p, "shopTools") {
			t.Errorf("an MCP client must not get Playwright output: %s", p)
		}
	}
}

// TestGenerate_MCPClientHooksNeedNoSDK: the hooks file builds the tools
// server from the generated tools packages' handlers and fills hooked steps
// through the session the generated file hands it, so it imports only what
// any hooks file does — the MCP SDK stays in the generated file.
func TestGenerate_MCPClientHooksNeedNoSDK(t *testing.T) {
	doc := fixtureDoc(t)
	withShopTools(t, doc)
	step := doc["phaseArtifacts"].(map[string]any)["testPlan"].(map[string]any)["shopTools"].(map[string]any)["bindings"].([]any)[0].(map[string]any)["steps"].([]any)[0].(map[string]any)
	step["hook"] = true
	out, err := generateDoc(t, doc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out.Generated[toolsGen])
	if !strings.Contains(src, "out1, err1 := stepTrackOrderP1S1(t, h, subject, `{\"orderId\":\"o-1\"}`)") {
		t.Errorf("hooked tool step must call its hook with the tool arguments:\n%s", src)
	}
	hooks, ok := out.HooksOnce[toolsHooks]
	if !ok {
		t.Fatalf("missing %s; have %v", toolsHooks, keys(out.HooksOnce))
	}
	for _, want := range []string{
		"// Hooks for shopTools scenario tests. Generated ONCE by testgen; owned by the construction agent.",
		"package mcp_test",
		"func newSubject(t *testing.T, h *scenariohost.Host) toolServer {",
		"func stepTrackOrderP1S1(t *testing.T, h *scenariohost.Host, subject *toolSession, args string) (any, error) {",
		"func probeTrackOrderP1S1N2(t *testing.T, h *scenariohost.Host, subject *toolSession) (any, error) {",
		"orderGetOrder",
	} {
		if !strings.Contains(string(hooks), want) {
			t.Errorf("hooks stub missing %q in\n%s", want, hooks)
		}
	}
	if strings.Contains(string(hooks), "modelcontextprotocol") || strings.Contains(string(hooks), "replayWorkflows") {
		t.Errorf("hooks must import neither the MCP SDK nor declare replay:\n%s", hooks)
	}
	if _, err := format.Source(hooks); err != nil {
		t.Fatalf("hooks not gofmt-able: %v", err)
	}
	root := t.TempDir()
	writeAll(t, root, out.Generated)
	writeAll(t, root, out.HooksOnce)
	msgs, err := Drift(root, out)
	if err != nil {
		t.Fatal(err)
	}
	if len(msgs) != 0 {
		t.Fatalf("fresh MCP tree drifted: %v", msgs)
	}
}

// TestGenerate_MCPClientWithoutGoPackageWarns: the in-process dialect lands
// in a Go package; a tools client naming none is reported, not guessed.
func TestGenerate_MCPClientWithoutGoPackageWarns(t *testing.T) {
	doc := fixtureDoc(t)
	withShopTools(t, doc)
	delete(doc["serviceContracts"].(map[string]any)["shopTools"].(map[string]any), "goPackage")
	out, err := generateDoc(t, doc)
	if err != nil {
		t.Fatal(err)
	}
	for p := range out.Generated {
		if strings.Contains(p, "shopTools") || strings.HasPrefix(p, "internal/client/") {
			t.Errorf("a tools client without goPackage must emit nothing: %s", p)
		}
	}
	if !slices.Contains(out.Warnings, "testgen: shopTools is an MCP client with no goPackage; no tests generated") {
		t.Errorf("warning missing: %v", out.Warnings)
	}
}

// TestGenerate_ClientMixingDialectsIsAnError: an op taking the web dialect's
// one `action` param and a tool op cannot share a contract — the surface is
// either a browser or an MCP server.
func TestGenerate_ClientMixingDialectsIsAnError(t *testing.T) {
	doc := fixtureDoc(t)
	withShopTools(t, doc)
	shop := doc["serviceContracts"].(map[string]any)["shopClient"].(map[string]any)
	iface := shop["interface"].(map[string]any)
	iface["operations"] = append(iface["operations"].([]any), map[string]any{
		"name": "OrderGetOrder", "params": []any{map[string]any{"name": "orderId", "schema": map[string]any{"type": "string"}}}, "error": true,
	})
	_, err := generateDoc(t, doc)
	if err == nil || !strings.Contains(err.Error(), "shopClient mixes web actions (OpenOrders) and MCP tools (OrderGetOrder)") {
		t.Fatalf("want a mixed-dialect error, got %v", err)
	}
}

// TestGenerate_WebClientIsTheActionDialect: a client whose ops take the one
// `action` param is the browser surface (Playwright), even when it names a
// goPackage (its REST transport's package, say).
func TestGenerate_WebClientIsTheActionDialect(t *testing.T) {
	doc := fixtureDoc(t)
	doc["serviceContracts"].(map[string]any)["shopClient"].(map[string]any)["goPackage"] = "internal/client/web"
	out, err := generateDoc(t, doc)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := out.Generated[shopSpec]; !ok {
		t.Errorf("web client must stay Playwright; have %v", keys(out.Generated))
	}
	for p := range out.Generated {
		if strings.HasPrefix(p, "internal/client/web/") {
			t.Errorf("web client must not get a Go scenarios file: %s", p)
		}
	}
}

// TestClientDialect pins the classification table.
func TestClientDialect(t *testing.T) {
	action := map[string]any{"name": "action", "schema": map[string]any{"type": "object"}}
	arg := map[string]any{"name": "orderId", "schema": map[string]any{"type": "string"}}
	for _, tc := range []struct {
		name      string
		goPackage string
		ops       []any
		want      dialect
	}{
		{"web actions", "", []any{map[string]any{"name": "Open", "params": []any{action}}}, dialectWeb},
		{"web actions with a package", "internal/client/web", []any{map[string]any{"name": "Open", "params": []any{action}}}, dialectWeb},
		{"tools", "internal/client/mcp", []any{map[string]any{"name": "OrderGetOrder", "params": []any{arg}}}, dialectMCP},
		{"tool with no params", "internal/client/mcp", []any{map[string]any{"name": "OrderList", "params": []any{}}}, dialectMCP},
		{"tool taking action among others", "internal/client/mcp", []any{map[string]any{"name": "Steer", "params": []any{action, arg}}}, dialectMCP},
		{"no ops, a package", "internal/client/mcp", nil, dialectMCP},
		{"no ops, no package", "", nil, dialectWeb},
	} {
		raw, err := json.Marshal(map[string]any{"component": "c", "layer": "Client", "goPackage": tc.goPackage, "interface": map[string]any{"name": "C", "layer": "client", "operations": tc.ops}})
		if err != nil {
			t.Fatal(err)
		}
		var sc methodcheck.ServiceContract
		if err := json.Unmarshal(raw, &sc); err != nil {
			t.Fatal(err)
		}
		got, err := clientDialect("c", sc)
		if err != nil {
			t.Errorf("%s: %v", tc.name, err)
			continue
		}
		if got != tc.want {
			t.Errorf("%s: dialect %v, want %v", tc.name, got, tc.want)
		}
	}
}

// TestGenerate_MCPClientSkippedBindingNeedsNoHooks: a package whose MCP
// bindings are all skipped still gets its generated file (TestMain + the
// skipped test, so the gap stays visible) but no hooks file, and imports
// nothing a runnable binding would need.
func TestGenerate_MCPClientSkippedBindingNeedsNoHooks(t *testing.T) {
	doc := fixtureDoc(t)
	withShopTools(t, doc)
	binding := doc["phaseArtifacts"].(map[string]any)["testPlan"].(map[string]any)["shopTools"].(map[string]any)["bindings"].([]any)[0].(map[string]any)
	binding["skip"] = map[string]any{"reason": "orderManager not integrated", "until": "orderManager"}
	binding["steps"] = []any{}
	out, err := generateDoc(t, doc)
	if err != nil {
		t.Fatal(err)
	}
	src := string(out.Generated[toolsGen])
	for _, want := range []string{
		"func TestMain(m *testing.M) { scenariohost.Main(m, \"shopTools\") }",
		"t.Skip(\"orderManager not integrated (until orderManager)\")",
	} {
		if !strings.Contains(src, want) {
			t.Errorf("missing %q in\n%s", want, src)
		}
	}
	for _, bad := range []string{"modelcontextprotocol", "serveTools", "newSubject"} {
		if strings.Contains(src, bad) {
			t.Errorf("an all-skipped MCP file must not carry %q:\n%s", bad, src)
		}
	}
	if _, ok := out.HooksOnce[toolsHooks]; ok {
		t.Errorf("an all-skipped MCP package must not get a hooks file")
	}
}

// TestGenerate_MCPPackageServesOneSurface: two MCP client contracts in one
// goPackage are an error — one package serves one tools surface.
func TestGenerate_MCPPackageServesOneSurface(t *testing.T) {
	doc := fixtureDoc(t)
	withShopTools(t, doc)
	contracts := doc["serviceContracts"].(map[string]any)
	twin := maps.Clone(contracts["shopTools"].(map[string]any))
	twin["component"] = "shopToolsTwin"
	contracts["shopToolsTwin"] = twin
	plans := doc["phaseArtifacts"].(map[string]any)["testPlan"].(map[string]any)
	plans["shopToolsTwin"] = map[string]any{"component": "shopToolsTwin", "bindings": []any{}}
	_, err := generateDoc(t, doc)
	if err == nil || !strings.Contains(err.Error(), "internal/client/mcp hosts several MCP client contracts (shopTools, shopToolsTwin)") {
		t.Fatalf("want a one-surface error, got %v", err)
	}
}

// TestGenerate_MCPClientCannotShareALayerPackage: an MCP client and a layer
// contract cannot share a goPackage (their files would carry different
// stereotypes in one leaf).
func TestGenerate_MCPClientCannotShareALayerPackage(t *testing.T) {
	doc := fixtureDoc(t)
	withShopTools(t, doc)
	doc["serviceContracts"].(map[string]any)["shopTools"].(map[string]any)["goPackage"] = "internal/manager/order"
	_, err := generateDoc(t, doc)
	if err == nil || !strings.Contains(err.Error(), "hosts contracts of different layers") {
		t.Fatalf("want a mixed-layer error, got %v", err)
	}
}
