package testgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"path"
	"slices"
	"sort"
	"strconv"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/mixofreality-studio/archistrator-platform/framework-go-app-generator/modelgen"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/methodcheck"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/scenario"
)

// scenarioHostImport is the scenario host every generated Go test boots
// through; its package name is scenariohost.
const scenarioHostImport = "github.com/mixofreality-studio/archistrator-platform/framework-go-scenariohost"

// genHeader is the first line of every generated file (Global Constraints).
const genHeader = "// Code generated by testgen. DO NOT EDIT."

// layerPkg is the framework package whose call Context a layer's contract
// methods take first, mirroring modelgen's layer table: alias, import path
// and whether the Context carries an idempotency key.
type layerPkg struct {
	alias, path string
	idempotent  bool
}

var layerPkgs = map[string]layerPkg{
	"manager":        {"fwm", "github.com/mixofreality-studio/archistrator-platform/framework-go/manager", false},
	"engine":         {"fweng", "github.com/mixofreality-studio/archistrator-platform/framework-go/engine", false},
	"resourceaccess": {"fwra", "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess", true},
	"utility":        {"fwra", "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess", true},
}

// goEmit is one Go package's emission state: the generated file body, the
// hooks file body, and the imports each needs.
type goEmit struct {
	cfg     Config
	goPkg   string
	pkg     string // package name == import alias (modelgen names the package after goPkg's last segment)
	layer   layerPkg
	multi   bool // several contracts share the package: names carry the interface infix
	manager bool // a manager package: its TestMain hands the host workflows to replay
	body    bytes.Buffer
	imports map[string]bool   // extra import paths (x-go-import bindings)
	subject bool              // ≥1 contract has a runnable binding
	owners  map[string]string // declared Go name → the binding that declares it (claim)
}

// emitGo emits one Go package's generated scenarios file and, when any
// binding is runnable, its once-emitted hooks file.
func emitGo(out *Output, cfg Config, goPkg string, plans []componentPlan) error {
	stereotype, err := sharedStereotype(goPkg, plans)
	if err != nil {
		return err
	}
	layer, ok := layerPkgs[layerKey(plans[0].Contract)]
	if !ok {
		return fmt.Errorf("testgen: %s: layer %q has no framework call context", goPkg, plans[0].Contract.Layer)
	}
	g := &goEmit{
		cfg: cfg, goPkg: goPkg, pkg: path.Base(goPkg), layer: layer,
		multi: len(plans) > 1, manager: layerKey(plans[0].Contract) == "manager",
		imports: map[string]bool{}, owners: map[string]string{},
	}
	for _, plan := range plans {
		if err := g.claimPlan(plan); err != nil {
			return err
		}
		g.emitPlan(plan)
	}
	src, err := g.generatedFile(plans)
	if err != nil {
		return err
	}
	out.Generated[path.Join(goPkg, stereotype+"_scenarios.gen_test.go")] = src
	if g.subject {
		hooks, err := g.hooksFile(plans)
		if err != nil {
			return err
		}
		out.HooksOnce[path.Join(goPkg, stereotype+"_hooks_test.go")] = hooks
	}
	return nil
}

// sharedStereotype is the one file stereotype of every contract in the
// package; contracts of different layers cannot share a package.
func sharedStereotype(goPkg string, plans []componentPlan) (string, error) {
	st := stereotypeOf(plans[0].Contract)
	for _, p := range plans[1:] {
		if s := stereotypeOf(p.Contract); s != st {
			return "", fmt.Errorf("testgen: %s hosts contracts of different layers (%s, %s)", goPkg, st, s)
		}
	}
	return st, nil
}

// ---- naming ----

// tag is the infix every per-binding name carries in a package several
// contracts share (two contracts there can bind the SAME scenario id).
func (g *goEmit) tag(plan componentPlan) string {
	if !g.multi {
		return ""
	}
	return ifaceName(plan)
}

// ifaceName is the contract's Go interface name, falling back to the
// exported contract key for a contract that names none.
func ifaceName(plan componentPlan) string {
	if n := plan.Contract.Interface.Name; n != "" {
		return n
	}
	return exportName(plan.Key)
}

func exportName(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func (g *goEmit) subjectType(plan componentPlan) string { return g.pkg + "." + ifaceName(plan) }
func (g *goEmit) subjectName(plan componentPlan) string {
	return hookName(subjectPrefix, g.tag(plan), "", 0, 0)
}

// testName keeps the spec's TestScenario_<id> spelling: revive exempts Test*
// funcs in test files, and `make test-scenarios` and the construct workflow
// select the tests with -run 'TestScenario_'.
func (g *goEmit) testName(plan componentPlan, id string) string {
	tag := ""
	if g.multi {
		tag = "_" + ident(ifaceName(plan))
	}
	return "TestScenario" + tag + "_" + ident(id)
}
func (g *goEmit) inputName(plan componentPlan, id string, seq int) string {
	return hookName(inputPrefix, g.tag(plan), id, seq, 0)
}
func (g *goEmit) stepName(plan componentPlan, id string, seq int) string {
	return hookName(stepPrefix, g.tag(plan), id, seq, 0)
}
func (g *goEmit) probeName(plan componentPlan, id string, seq, n int) string {
	return hookName(probePrefix, g.tag(plan), id, seq, n)
}

// claimPlan claims every name one contract's bindings declare in the package:
// the subject constructor, each scenario test, each step's input type, each
// hooked step and each hooked probe.
func (g *goEmit) claimPlan(plan componentPlan) error {
	if err := g.claim(g.subjectName(plan), plan.Key); err != nil {
		return err
	}
	for _, bs := range plan.Scenarios {
		id := bs.Scenario.ID
		owner := plan.Key + " " + id
		if err := g.claim(g.testName(plan, id), owner); err != nil {
			return err
		}
		for _, st := range bs.Steps {
			if err := g.claimStep(plan, bs, st, fmt.Sprintf("%s step %d", owner, st.Bind.Seq)); err != nil {
				return err
			}
		}
	}
	return nil
}

func (g *goEmit) claimStep(plan componentPlan, bs boundScenario, st boundStep, owner string) error {
	id, seq := bs.Scenario.ID, st.Bind.Seq
	names := []string{g.inputName(plan, id, seq), g.stepName(plan, id, seq)}
	for i, pr := range st.Bind.Probes {
		if _, inline := g.inlineProbe(plan, pr); !inline {
			names = append(names, g.probeName(plan, id, seq, i+1))
		}
	}
	for _, n := range names {
		if err := g.claim(n, owner); err != nil {
			return err
		}
	}
	return nil
}

// ---- generated file ----

func (g *goEmit) emitPlan(plan componentPlan) {
	for _, bs := range plan.Scenarios {
		if bs.Binding.Skip == nil {
			g.subject = true
			for _, st := range bs.Steps {
				g.emitInputType(plan, bs, st)
			}
		}
		g.emitScenario(plan, bs)
	}
}

// emitInputType declares the named struct a step's inputs decode into: one
// exported field per contract parameter, typed as modelgen types it.
func (g *goEmit) emitInputType(plan componentPlan, bs boundScenario, st boundStep) {
	name := g.inputName(plan, bs.Scenario.ID, st.Bind.Seq)
	fmt.Fprintf(&g.body, "// %s is step %d's parameters of %s, decoded from the binding's inputs.\n", name, st.Bind.Seq, st.Op.Name)
	fmt.Fprintf(&g.body, "type %s %s\n\n", name, g.paramsStruct(st.Op))
}

// paramsStruct spells an operation's parameter list as a struct type literal.
func (g *goEmit) paramsStruct(op methodcheck.ContractOperation) string {
	if len(op.Params) == 0 {
		return "struct{}"
	}
	var b strings.Builder
	b.WriteString("struct {\n")
	for _, p := range op.Params {
		fmt.Fprintf(&b, "\t%s %s `json:%q`\n", exportName(p.Name), g.paramType(p), p.Name)
	}
	b.WriteString("}")
	return b.String()
}

// paramType is the Go type of one parameter as spelled from outside the
// contract package, recording any x-go-import the type needs.
func (g *goEmit) paramType(p methodcheck.ContractParam) string {
	typ, imports := modelgen.GoTypeFor(decodeSchema(p.Schema), g.pkg)
	for _, imp := range imports {
		g.imports[imp] = true
	}
	if p.Pointer {
		typ = "*" + typ
	}
	return typ
}

func decodeSchema(raw json.RawMessage) *jsonschema.Schema {
	if len(raw) == 0 || string(raw) == "null" {
		return nil
	}
	var s jsonschema.Schema
	if err := json.Unmarshal(raw, &s); err != nil {
		return nil
	}
	return &s
}

func (g *goEmit) emitScenario(plan componentPlan, bs boundScenario) {
	name := g.testName(plan, bs.Scenario.ID)
	fmt.Fprintf(&g.body, "// %s — %s (use case %s; path %s).\n", name, bs.Scenario.Title, bs.Scenario.UseCase, strings.Join(bs.Scenario.Path, " → "))
	fmt.Fprintf(&g.body, "func %s(t *testing.T) {\n", name)
	g.body.WriteString("\th := scenariohost.Start(t)\n")
	// The verdict is keyed by (component, scenario): facets sharing this
	// package can bind the same scenario id, each into its own results.json.
	fmt.Fprintf(&g.body, "\th.RunScenario(t, %q, %q, func(t *testing.T) {\n", plan.Key, bs.Scenario.ID)
	switch {
	case bs.Binding.Skip != nil:
		fmt.Fprintf(&g.body, "\t\tt.Skip(%q)\n", bs.Binding.Skip.Reason+" (until "+bs.Binding.Skip.Until+")")
	default:
		fmt.Fprintf(&g.body, "\t\tvar subject %s = %s(t, h)\n", g.subjectType(plan), g.subjectName(plan))
		if len(bs.Steps) == 0 {
			g.body.WriteString("\t\t_ = subject // the binding carries no steps\n")
		}
		for _, st := range bs.Steps {
			g.emitStep(plan, bs, st)
		}
	}
	g.body.WriteString("\t})\n}\n\n")
}

// emitStep emits one bound stimulus: decode inputs, call (hook or direct),
// assert the expectation, then run the probes.
func (g *goEmit) emitStep(plan componentPlan, bs boundScenario, st boundStep) {
	id, seq := bs.Scenario.ID, st.Bind.Seq
	fmt.Fprintf(&g.body, "\t\t// step %d: %s (node %s%s)\n", seq, st.Op.Name, st.Stim.Node, guardNote(bs.Scenario))
	fmt.Fprintf(&g.body, "\t\tvar in%d %s\n", seq, g.inputName(plan, id, seq))
	fmt.Fprintf(&g.body, "\t\tmustUnmarshal(t, %s, &in%d)\n", rawString(inputsJSON(plan.Contract, st.Op, st.Bind.Inputs)), seq)
	fmt.Fprintf(&g.body, "\t\tvar out%d any\n\t\tvar err%d error\n", seq, seq)
	if st.Bind.Hook {
		fmt.Fprintf(&g.body, "\t\tout%d, err%d = %s(t, h, subject, in%d)\n", seq, seq, g.stepName(plan, id, seq), seq)
	} else {
		g.body.WriteString("\t\t" + callLine(st.Op, fmt.Sprintf("out%d", seq), fmt.Sprintf("err%d", seq), fmt.Sprintf("in%d", seq), strconv.Itoa(seq)) + "\n")
	}
	fmt.Fprintf(&g.body, "\t\texpect(t, %q, %d, out%d, err%d, %s)\n", id, seq, seq, seq, rawString(expectJSON(st.Bind.Expect)))
	if len(st.Bind.Unobservable) > 0 {
		fmt.Fprintf(&g.body, "\t\t// unobservable: %s\n", strings.Join(st.Bind.Unobservable, ", "))
	}
	for i, pr := range st.Bind.Probes {
		g.emitProbe(plan, bs, st, i+1, pr)
	}
}

// emitProbe emits one probe: inline when it reads the subject's own contract,
// a probe hook when it reads another component.
func (g *goEmit) emitProbe(plan componentPlan, bs boundScenario, st boundStep, n int, pr methodcheck.Probe) {
	id, seq := bs.Scenario.ID, st.Bind.Seq
	v := fmt.Sprintf("%d_%d", seq, n)
	label := fmt.Sprintf("%s probe %d.%d", id, seq, n)
	op, inline := g.inlineProbe(plan, pr)
	fmt.Fprintf(&g.body, "\t\t// probe %d.%d: %s.%s for %s\n", seq, n, pr.Component, pr.Operation, pr.For)
	fmt.Fprintf(&g.body, "\t\tvar pout%s any\n\t\tvar perr%s error\n", v, v)
	if inline {
		fmt.Fprintf(&g.body, "\t\tvar probe%s %s\n", v, g.paramsStruct(op))
		fmt.Fprintf(&g.body, "\t\tmustUnmarshal(t, %s, &probe%s)\n", rawString(inputsJSON(plan.Contract, op, pr.Inputs)), v)
		g.body.WriteString("\t\t" + callLine(op, "pout"+v, "perr"+v, "probe"+v, fmt.Sprintf("%d.%d", seq, n)) + "\n")
	} else {
		fmt.Fprintf(&g.body, "\t\tpout%s, perr%s = %s(t, h, subject)\n", v, v, g.probeName(plan, id, seq, n))
	}
	fmt.Fprintf(&g.body, "\t\texpect(t, %q, %d, pout%s, perr%s, %s)\n", label, seq, v, v, rawString(expectJSON(pr.Expect)))
}

// inlineProbe reports whether pr reads the subject's own contract, with the
// operation it names when so.
func (g *goEmit) inlineProbe(plan componentPlan, pr methodcheck.Probe) (methodcheck.ContractOperation, bool) {
	if scenario.Normalize(pr.Component) != scenario.Normalize(plan.Key) {
		return methodcheck.ContractOperation{}, false
	}
	return operationNamed(plan.Contract, pr.Operation)
}

// callLine spells a direct call of op on subject with the decoded inputs in
// inVar, assigning whatever the op returns to outVar / errVar.
func callLine(op methodcheck.ContractOperation, outVar, errVar, inVar, step string) string {
	args := []string{fmt.Sprintf("callContext(t, h, %q)", step)}
	for _, p := range op.Params {
		args = append(args, inVar+"."+exportName(p.Name))
	}
	call := fmt.Sprintf("subject.%s(%s)", op.Name, strings.Join(args, ", "))
	hasResult := len(op.Result) > 0 && string(op.Result) != "null"
	switch {
	case hasResult && op.Error:
		return outVar + ", " + errVar + " = " + call
	case hasResult:
		return outVar + " = " + call
	case op.Error:
		return errVar + " = " + call
	default:
		return call
	}
}

func guardNote(s scenario.Scenario) string {
	var gs []string
	for _, g := range s.Guards {
		gs = append(gs, g.At+"="+g.Guard)
	}
	if len(gs) == 0 {
		return ""
	}
	return "; guards " + strings.Join(gs, ", ")
}

// inputsJSON builds the JSON object a step's inputs decode from: one key per
// contract parameter, in contract order, carrying the binding's value — raw
// when it parses as JSON and the parameter is not string-typed, quoted
// otherwise. A parameter the binding leaves unnamed is omitted (zero value).
func inputsJSON(sc methodcheck.ServiceContract, op methodcheck.ContractOperation, inputs []methodcheck.TestArg) string {
	var parts []string
	for _, p := range op.Params {
		arg, ok := argNamed(inputs, p.Name)
		if !ok {
			continue
		}
		parts = append(parts, strconv.Quote(p.Name)+":"+jsonValue(arg.Value, isStringSchema(sc, p.Schema)))
	}
	return "{" + strings.Join(parts, ",") + "}"
}

func argNamed(inputs []methodcheck.TestArg, name string) (methodcheck.TestArg, bool) {
	for _, a := range inputs {
		if a.Name == name {
			return a, true
		}
	}
	return methodcheck.TestArg{}, false
}

func jsonValue(value string, stringTyped bool) string {
	if !stringTyped && json.Valid([]byte(value)) {
		return value
	}
	quoted, _ := json.Marshal(value)
	return string(quoted)
}

// isStringSchema reports whether a parameter schema is string-typed, following
// one $ref into the contract's $defs.
func isStringSchema(sc methodcheck.ServiceContract, raw json.RawMessage) bool {
	s := decodeSchema(raw)
	if s == nil {
		return false
	}
	if s.Ref != "" {
		def, ok := sc.Defs[strings.TrimPrefix(s.Ref, "#/$defs/")]
		if !ok {
			return false
		}
		s = decodeSchema(def)
		if s == nil {
			return false
		}
	}
	return s.Type == "string" || slices.Contains(s.Types, "string")
}

// expectJSON is the binding expectation as the generated expect helper reads it.
func expectJSON(e methodcheck.TestExpect) string {
	raw, _ := json.Marshal(e)
	return string(raw)
}

// rawString spells s as a Go string literal: a raw literal when it carries no
// backtick, an interpreted one otherwise.
func rawString(s string) string {
	if strings.Contains(s, "`") {
		return strconv.Quote(s)
	}
	return "`" + s + "`"
}

// generatedFile assembles header, package clause, imports, TestMain, the
// scenario tests and the helpers, gofmt'd.
func (g *goEmit) generatedFile(plans []componentPlan) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(genHeader + "\n")
	for _, plan := range plans {
		fmt.Fprintf(&b, "// Source: project.json .phaseArtifacts.testPlan.%s × scenario.ForComponent(%q)\n", plan.Key, plan.Key)
	}
	fmt.Fprintf(&b, "\npackage %s_test\n\n", g.pkg)
	g.writeImports(&b, g.generatedImports())
	// Main names every component whose scenarios live here, so each gets its
	// own results.json (an empty one when none of its scenarios ran).
	comps := make([]string, 0, len(plans))
	for _, plan := range plans {
		comps = append(comps, strconv.Quote(plan.Key))
	}
	if g.replays() {
		// A manager's workflows are replayed at every flush (DCT §12 B4): the
		// hooks file's replayWorkflows registers them with the host.
		fmt.Fprintf(&b, "func TestMain(m *testing.M) {\n\tscenariohost.MainWithWorkflows(m, %s(), %s)\n}\n\n", replayHook, strings.Join(comps, ", "))
	} else {
		fmt.Fprintf(&b, "func TestMain(m *testing.M) { scenariohost.Main(m, %s) }\n\n", strings.Join(comps, ", "))
	}
	b.Write(g.body.Bytes())
	if g.subject {
		g.writeHelpers(&b)
	}
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("testgen: %s: generated file does not format: %w\n%s", g.goPkg, err, b.String())
	}
	return src, nil
}

// replays reports whether the package's scenarios are replay-gated: a
// manager package with a runnable binding (one that has a hooks file to
// declare replayWorkflows; with none, no scenario runs a workflow).
func (g *goEmit) replays() bool { return g.manager && g.subject }

// generatedImports is the import set of the generated file: the test
// essentials always; the helpers', the layer's and the contract package's when
// any binding runs.
func (g *goEmit) generatedImports() map[string]string {
	imps := map[string]string{"testing": "", scenarioHostImport: ""}
	if !g.subject {
		return imps
	}
	for _, p := range []string{"encoding/json", "errors", "reflect", "strings"} {
		imps[p] = ""
	}
	imps[g.layer.path] = g.layer.alias
	imps[g.cfg.ModulePath+"/"+g.goPkg] = ""
	for p := range g.imports {
		imps[p] = ""
	}
	return imps
}

// writeImports writes one import block, standard library first; gofmt sorts
// within each group.
func (g *goEmit) writeImports(b *bytes.Buffer, imps map[string]string) {
	var std, rest []string
	for p := range imps {
		if strings.Contains(strings.SplitN(p, "/", 2)[0], ".") {
			rest = append(rest, p)
		} else {
			std = append(std, p)
		}
	}
	sort.Strings(std)
	sort.Strings(rest)
	b.WriteString("import (\n")
	for _, p := range std {
		writeImport(b, p, imps[p])
	}
	if len(rest) > 0 {
		b.WriteString("\n")
	}
	for _, p := range rest {
		writeImport(b, p, imps[p])
	}
	b.WriteString(")\n\n")
}

func writeImport(b *bytes.Buffer, p, alias string) {
	if alias != "" {
		fmt.Fprintf(b, "\t%s %q\n", alias, p)
		return
	}
	fmt.Fprintf(b, "\t%q\n", p)
}

// writeHelpers emits the per-file assertion helpers. They are duplicated per
// generated file on purpose: the file is black-box and self-contained, and the
// scenario host stays a boot-and-record concern.
func (g *goEmit) writeHelpers(b *bytes.Buffer) {
	a := g.layer.alias
	key := ""
	if g.layer.idempotent {
		key = ", IdempotencyKey: " + a + ".IdempotencyKey(t.Name() + \"/\" + step)"
	}
	fmt.Fprintf(b, goHelpers, a, key, "`")
}

// goHelpers is the helper block's template: %[1]s is the layer package alias,
// %[2]s the extra Context fields an idempotent layer's call context carries,
// %[3]s a backtick (the struct tags; a raw literal cannot hold one).
const goHelpers = `// callContext is the %[1]s call context a generated step calls the subject with:
// the test's own context, a zero principal and, on an idempotent layer, a key
// unique to the step. A step that needs an identity is a Hook:true step.
func callContext(t *testing.T, h *scenariohost.Host, step string) %[1]s.Context {
	t.Helper()
	_ = step
	return %[1]s.Context{Context: h.Context(t)%[2]s}
}

func mustUnmarshal(t *testing.T, raw string, into any) {
	t.Helper()
	if err := json.Unmarshal([]byte(raw), into); err != nil {
		t.Fatalf("testgen: decode %%s: %%v", raw, err)
	}
}

// expect checks one step's outcome against its binding's expectation: an
// expected error must arrive (carrying the expected code, when one is named);
// an unexpected error fails; a named result must be a JSON subset of the
// marshalled outcome.
func expect(t *testing.T, scenario string, seq int, out any, err error, expectJSON string) {
	t.Helper()
	var want struct {
		Result        string %[3]sjson:"result"%[3]s
		ErrorExpected bool   %[3]sjson:"errorExpected"%[3]s
		ErrorCode     string %[3]sjson:"errorCode"%[3]s
	}
	mustUnmarshal(t, expectJSON, &want)
	if want.ErrorExpected {
		if err == nil {
			t.Fatalf("%%s step %%d: expected error %%q, got nil", scenario, seq, want.ErrorCode)
		}
		if want.ErrorCode != "" && !errorHasCode(err, want.ErrorCode) {
			t.Fatalf("%%s step %%d: expected error code %%q, got %%v", scenario, seq, want.ErrorCode, err)
		}
		return
	}
	if err != nil {
		t.Fatalf("%%s step %%d: unexpected error: %%v", scenario, seq, err)
	}
	if want.Result != "" && !resultMatches(want.Result, out) {
		got, _ := json.Marshal(out)
		t.Fatalf("%%s step %%d: result %%s is not a subset of %%s", scenario, seq, want.Result, got)
	}
}

// errorHasCode matches the layer error's kind name, or the code as a substring
// of the error text for a component-specific code.
func errorHasCode(err error, code string) bool {
	var le *%[1]s.Error
	if errors.As(err, &le) && le.Kind.String() == code {
		return true
	}
	return strings.Contains(err.Error(), code)
}

// resultMatches decodes the expectation (a JSON document, or a bare string)
// and the marshalled outcome, and compares them as a subset.
func resultMatches(wantRaw string, got any) bool {
	var want any
	if json.Unmarshal([]byte(wantRaw), &want) != nil {
		want = wantRaw
	}
	raw, err := json.Marshal(got)
	if err != nil {
		return false
	}
	var g any
	if json.Unmarshal(raw, &g) != nil {
		return false
	}
	return subset(want, g)
}

// subset: every key of an expected object is present and matches; an expected
// array matches element-wise; a scalar must be equal.
func subset(want, got any) bool {
	switch w := want.(type) {
	case map[string]any:
		g, ok := got.(map[string]any)
		if !ok {
			return false
		}
		for k, wv := range w {
			gv, ok := g[k]
			if !ok || !subset(wv, gv) {
				return false
			}
		}
		return true
	case []any:
		g, ok := got.([]any)
		if !ok || len(g) != len(w) {
			return false
		}
		for i := range w {
			if !subset(w[i], g[i]) {
				return false
			}
		}
		return true
	default:
		return reflect.DeepEqual(want, got)
	}
}
`
