package testgen

import (
	"encoding/json"
	"go/format"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

const (
	billingGen   = "internal/manager/billing/manager_scenarios.gen_test.go"
	billingHooks = "internal/manager/billing/manager_hooks_test.go"
	orderGen     = "internal/manager/order/manager_scenarios.gen_test.go"
	shopSpec     = "uitests/generated/shopClient/browse-orders-P1.spec.gen.ts"
	shopConfig   = "uitests/generated/shopClient/playwright.config.gen.ts"
	shopReporter = "uitests/generated/shopClient/reporter.gen.ts"
	shopHooks    = "uitests/generated/shopClient/hooks.ts"
)

func keys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	slices.Sort(out)
	return out
}

func generate(t *testing.T) Output {
	t.Helper()
	raw, err := os.ReadFile("testdata/project_tp.json")
	if err != nil {
		t.Fatal(err)
	}
	out, err := Generate(raw, Config{ModulePath: "example.com/app/server"})
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func TestGenerate_GoScenarioFileShape(t *testing.T) {
	out := generate(t)
	src, ok := out.Generated[billingGen]
	if !ok {
		t.Fatalf("missing generated file; have %v", keys(out.Generated))
	}
	for _, want := range []string{
		"// Code generated by testgen. DO NOT EDIT.",
		"package billing_test",
		"func TestMain(m *testing.M)",
		"scenariohost.Main(m, \"billingManager\")",
		"scenariohost.Start(",
		"func TestScenario_process_order_P2(",
		"func TestScenario_track_order_P1(",
		"h.RunScenario(t, \"process-order-P2\"",
		"Step_process_order_P2_1(t, h, subject, in1)",                 // hook call for Hook:true steps
		"subject.GetInvoice(callContext(t, h, \"1\"), in1.InvoiceId)", // direct call for Hook:false steps
		"\"example.com/app/server/internal/manager/billing\"",
		"fwm \"github.com/mixofreality-studio/archistrator-platform/framework-go/manager\"",
		"\"github.com/mixofreality-studio/archistrator-platform/framework-go-scenariohost\"",
		"expect(t, \"track-order-P1\", 1, out1, err1, `{\"result\":\"{\\\"id\\\":\\\"inv-o-2\\\",\\\"state\\\":\\\"paid\\\"}\",\"errorExpected\":false}`)",
	} {
		if !strings.Contains(string(src), want) {
			t.Errorf("missing %q in\n%s", want, src)
		}
	}
	if strings.Contains(string(src), "Probe_") {
		t.Errorf("same-component probe must be inlined, not hooked:\n%s", src)
	}
	if !strings.Contains(string(src), "subject.GetInvoice(callContext(t, h, \"1.1\"), probe1_1.InvoiceId)") {
		t.Errorf("same-component probe call missing in\n%s", src)
	}
	if _, err := format.Source(src); err != nil {
		t.Fatalf("not gofmt-able: %v", err)
	}
	hooks := out.HooksOnce[billingHooks]
	for _, want := range []string{
		"// Hooks for billingManager scenario tests. Generated ONCE by testgen; owned by the construction agent.",
		"package billing_test",
		"func newSubject(t *testing.T, h *scenariohost.Host) billing.BillingManager",
		"func Step_process_order_P2_1(t *testing.T, h *scenariohost.Host, subject billing.BillingManager, in Input_process_order_P2_1) (any, error)",
	} {
		if !strings.Contains(string(hooks), want) {
			t.Errorf("hooks stub missing %q in\n%s", want, hooks)
		}
	}
	for _, want := range []string{
		"type Input_process_order_P2_1 struct {",
		"InvoiceId string `json:\"invoiceId\"`",
		"Amount    int64  `json:\"amount\"`",
	} {
		if !strings.Contains(string(src), want) {
			t.Errorf("input type missing %q in\n%s", want, src)
		}
	}
	if _, err := format.Source(hooks); err != nil {
		t.Fatalf("hooks not gofmt-able: %v", err)
	}
}

func TestGenerate_CrossComponentProbeIsHooked(t *testing.T) {
	out := generate(t)
	src := string(out.Generated[orderGen])
	if !strings.Contains(src, "Probe_process_order_P2_1_1(t, h, subject)") {
		t.Errorf("probe on billingManager from orderManager must be a hook call:\n%s", src)
	}
	hooks := string(out.HooksOnce["internal/manager/order/manager_hooks_test.go"])
	if !strings.Contains(hooks, "func Probe_process_order_P2_1_1(t *testing.T, h *scenariohost.Host, subject order.OrderManager) (any, error)") {
		t.Errorf("probe hook stub missing:\n%s", hooks)
	}
	// A $ref param is spelled through the contract package.
	if !strings.Contains(src, "Order order.Order `json:\"order\"`") {
		t.Errorf("$ref param type must be package-qualified:\n%s", src)
	}
}

func TestGenerate_PlaywrightSpec(t *testing.T) {
	out := generate(t)
	spec, ok := out.Generated[shopSpec]
	if !ok {
		t.Fatalf("missing playwright spec; have %v", keys(out.Generated))
	}
	for _, want := range []string{
		"// Code generated by testgen. DO NOT EDIT.",
		"test('browse-orders-P1",
		"await page.goto('/orders');",
		"await page.getByTestId('orders-tab').click();",
		"await hooks.step('browse-orders-P1', 1, page);",
		"await expect(page.getByTestId('orders-list')).toBeVisible();",
		"{ type: 'scenario', description: 'browse-orders-P1' }",
	} {
		if !strings.Contains(string(spec), want) {
			t.Errorf("missing %q in\n%s", want, spec)
		}
	}
	cfg := string(out.Generated[shopConfig])
	for _, want := range []string{"video: 'on'", "trace: 'on'", "outputDir: '../../test-results/shopClient'", "'../../test-results/shopClient/playwright.json'"} {
		if !strings.Contains(cfg, want) {
			t.Errorf("missing %q in config\n%s", want, cfg)
		}
	}
	if _, ok := out.Generated[shopReporter]; !ok {
		t.Errorf("missing reporter.gen.ts; have %v", keys(out.Generated))
	}
	hooks := string(out.HooksOnce[shopHooks])
	if !strings.Contains(hooks, "before") || !strings.Contains(hooks, "step") || !strings.Contains(hooks, "FILL") {
		t.Errorf("hooks.ts must stub before/step with FILL:\n%s", hooks)
	}
}

func TestGenerate_NoGoPackageWarns(t *testing.T) {
	raw, err := os.ReadFile("testdata/project_tp.json")
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	order := doc["serviceContracts"].(map[string]any)["orderManager"].(map[string]any)
	if _, ok := order["goPackage"]; !ok {
		t.Fatal("fixture no longer carries orderManager's goPackage")
	}
	delete(order, "goPackage")
	stripped, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}
	out, err := Generate(stripped, Config{ModulePath: "example.com/app/server"})
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := out.Generated[orderGen]; ok {
		t.Errorf("orderManager without goPackage must emit nothing; have %v", keys(out.Generated))
	}
	if !slices.Contains(out.Warnings, "testgen: orderManager has no goPackage; no tests generated") {
		t.Errorf("warning missing: %v", out.Warnings)
	}
}

func writeAll(t *testing.T, root string, files map[string][]byte) {
	t.Helper()
	for p, b := range files {
		full := filepath.Join(root, filepath.FromSlash(p))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, b, 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestDrift_CleanTreeIsSilent(t *testing.T) {
	out := generate(t)
	root := t.TempDir()
	writeAll(t, root, out.Generated)
	writeAll(t, root, out.HooksOnce)
	msgs, err := Drift(root, out)
	if err != nil {
		t.Fatal(err)
	}
	if len(msgs) != 0 {
		t.Fatalf("clean tree drifted: %v", msgs)
	}
}

func TestDrift_OrphanHook(t *testing.T) {
	out := generate(t)
	root := t.TempDir()
	writeAll(t, root, out.Generated)
	writeAll(t, root, out.HooksOnce)
	hooks := string(out.HooksOnce[billingHooks]) + "\nfunc Step_zzz(t *testing.T) {}\n"
	writeAll(t, root, map[string][]byte{billingHooks: []byte(hooks)})
	msgs, err := Drift(root, out)
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Contains(msgs, "orphan hook Step_zzz in "+billingHooks) {
		t.Fatalf("orphan not reported: %v", msgs)
	}
}

func TestDrift_MissingHookAndStaleFile(t *testing.T) {
	out := generate(t)
	root := t.TempDir()
	writeAll(t, root, out.Generated)
	writeAll(t, root, out.HooksOnce)
	hooks := strings.Replace(string(out.HooksOnce[billingHooks]), "func Step_process_order_P2_1(", "func Step_renamed(", 1)
	writeAll(t, root, map[string][]byte{
		billingHooks: []byte(hooks),
		orderGen:     []byte("// edited by hand\n"),
	})
	if err := os.Remove(filepath.Join(root, filepath.FromSlash(shopHooks))); err != nil {
		t.Fatal(err)
	}
	msgs, err := Drift(root, out)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"missing hook Step_process_order_P2_1 in " + billingHooks,
		"orphan hook Step_renamed in " + billingHooks,
		"stale: " + orderGen,
		"missing hooks file " + shopHooks,
	} {
		if !slices.Contains(msgs, want) {
			t.Errorf("missing %q in %v", want, msgs)
		}
	}
}

func TestGenerate_ZeroBindingPackageStillGetsTestMain(t *testing.T) {
	raw, err := os.ReadFile("testdata/project_tp.json")
	if err != nil {
		t.Fatal(err)
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	plans := doc["phaseArtifacts"].(map[string]any)["testPlan"].(map[string]any)
	plans["billingManager"] = map[string]any{"component": "billingManager", "bindings": []any{}}
	emptied, err := json.Marshal(doc)
	if err != nil {
		t.Fatal(err)
	}
	out, err := Generate(emptied, Config{ModulePath: "example.com/app/server"})
	if err != nil {
		t.Fatal(err)
	}
	src := string(out.Generated[billingGen])
	if !strings.Contains(src, "func TestMain(m *testing.M)") || strings.Contains(src, "func TestScenario_") {
		t.Errorf("zero-binding package must carry TestMain only:\n%s", src)
	}
	if _, err := format.Source([]byte(src)); err != nil {
		t.Fatalf("not gofmt-able: %v", err)
	}
}
