// Code generated by cmd/clientgen (mcpemit). DO NOT EDIT.
// Source contract:

package systemdesign

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	mgr "github.com/mixofreality-studio/archistrator/server/internal/manager/systemdesign"
)

// shellResourceURI is the single MCP-Apps UI resource all view-bearing tools reference.
const shellResourceURI = "ui://archistrator/shell.html"

// Handler binds the SystemDesignManager manager to MCP tools.
type Handler struct {
	Manager mgr.SystemDesignManager
}

// Register adds every operation as an mcp.Tool on srv, each carrying an
// explicit human description and an explicit input JSON Schema (enum values +
// meanings, REST-matching optionality) so an agentic consumer needs no source.
func (h *Handler) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignAdvancePhase", Description: "Advance the project from System Design (phase 1) to Project Design (phase 2). Requires every phase-1 artifact to be committed and reviewed; returns the resulting phase plus any reason the advance was gated.", InputSchema: advancePhaseInputSchema(), OutputSchema: advancePhaseOutputSchema()}, h.handleAdvancePhase)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignCreateProject", Description: "Create a new archistrator project owned by the given owner scope, with the given display name, and return its generated project ID.", InputSchema: createProjectInputSchema(), OutputSchema: createProjectOutputSchema()}, h.handleCreateProject)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignGetProject", Description: "Return the project head-state: its ID, current Method phase, name, owner, and high-level progress.", InputSchema: getProjectInputSchema(), OutputSchema: getProjectOutputSchema()}, h.handleGetProject)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignGetSessionState", Description: "Return the current draft/review session state for one System-Design artifact (selected by kind): its stage, the latest AI draft, and any review feedback. Read-only.", InputSchema: getSessionStateInputSchema(), OutputSchema: getSessionStateOutputSchema(), Meta: mcp.Meta{"ui": map[string]any{"resourceUri": shellResourceURI, "view": "system-design-session"}}}, h.handleGetSessionState)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignGetDesignHealth", Description: "Return the live Design Health for a project: the mechanical Method-rule findings evaluated render-on-read over the committed system design (each with a rule id, severity, and message), plus the committed waiver and attestation ledgers and the state revision the findings ran against. Read-only.", InputSchema: getDesignHealthInputSchema(), OutputSchema: getDesignHealthOutputSchema(), Meta: mcp.Meta{"ui": map[string]any{"resourceUri": shellResourceURI, "view": "design-health"}}}, h.handleGetDesignHealth)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignListProjects", Description: "List every project visible to the given owner scope, most-recently-updated first.", InputSchema: listProjectsInputSchema(), OutputSchema: listProjectsOutputSchema()}, h.handleListProjects)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignRequestArtifactDraft", Description: "Kick off (or re-run) the AI drafting of one System-Design artifact (selected by kind, e.g. the mission, glossary, or volatilities). Pass feedback to re-draft an existing artifact against review notes. Returns a handle to the asynchronous drafting session.", InputSchema: requestArtifactDraftInputSchema(), OutputSchema: requestArtifactDraftOutputSchema()}, h.handleRequestArtifactDraft)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSetOperatingModel", Description: "Set the project's operating model — selfOperated (the customer runs the built app in their own infrastructure; the default) or archistratorOperated (archistrator operates the app on the platform, which constrains the deployment design to the platform palette: CNPG Postgres, Temporal, Keycloak, the otel stack, deployed to the platform Kubernetes cluster). Choose at creation, before starting System Design. Returns the new project state version.", InputSchema: setOperatingModelInputSchema(), OutputSchema: setOperatingModelOutputSchema()}, h.handleSetOperatingModel)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSetResearchInput", Description: "Attach or replace the raw research corpus the architect distils the mission, glossary, and volatilities from. Returns the new project state version.", InputSchema: setResearchInputInputSchema(), OutputSchema: setResearchInputOutputSchema()}, h.handleSetResearchInput)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignAskQuestions", Description: "Ask one or more clarifying QUESTIONS about a System-Design artifact (selected by kind) addressed to a role (pm or architect), WITHOUT sending the draft back for a redraft. The questions are appended to the artifact's review ledger as question-type entries and a lightweight answer job is dispatched so the addressed role answers each in place. Works on a committed artifact too (seeds a question-only thread without opening an amendment). Unlike change-request comments, open questions do NOT block approve.", InputSchema: askQuestionsInputSchema(), OutputSchema: askQuestionsOutputSchema()}, h.handleAskQuestions)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignAcknowledgeStaleBasis", Description: "Mark a stale committed System-Design artifact 'reviewed — unaffected': clear its stale-basis flag WITHOUT a redraft, recording the reviewer's note as a durable audit entry in the review thread. Use when an upstream change does not actually affect this artifact (so a reconcile amendment would be a byte-identical no-op).", InputSchema: acknowledgeStaleBasisInputSchema(), OutputSchema: acknowledgeStaleBasisOutputSchema()}, h.handleAcknowledgeStaleBasis)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSetReviewCommentStatus", Description: "Change the status of one durable review-ledger comment on a System-Design artifact (selected by kind): waive an open comment to dismiss it, or reopen an addressed comment to send it back. Approve is blocked while any comment is still open.", InputSchema: setReviewCommentStatusInputSchema(), OutputSchema: setReviewCommentStatusOutputSchema()}, h.handleSetReviewCommentStatus)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignStartSystemDesign", Description: "Begin the System-Design phase for a project, seeding the artifact spine (mission first). Returns a handle to the kickoff session.", InputSchema: startSystemDesignInputSchema(), OutputSchema: startSystemDesignOutputSchema()}, h.handleStartSystemDesign)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignSubmitReviewDecision", Description: "Record a review verdict (approve / reject / withdraw) on the current draft of a System-Design artifact (selected by kind). Reject and withdraw should carry feedback; approve commits the artifact and unblocks its successors.", InputSchema: submitReviewDecisionInputSchema(), OutputSchema: submitReviewDecisionOutputSchema()}, h.handleSubmitReviewDecision)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignListEpisodesForArtifact", Description: "List the agentic episode records (draft/critique/rework runs, or gaps) captured against one System-Design artifact (selected by kind). Read-only.", InputSchema: listEpisodesForArtifactInputSchema(), OutputSchema: listEpisodesForArtifactOutputSchema()}, h.handleListEpisodesForArtifact)
	mcp.AddTool(srv, &mcp.Tool{Name: "systemDesignGetEpisodeTimeline", Description: "Return one agentic episode's full timeline: its record (usage, cost, outcome, lineage) plus the sequenced trace events mined from its run. Read-only.", InputSchema: getEpisodeTimelineInputSchema(), OutputSchema: getEpisodeTimelineOutputSchema()}, h.handleGetEpisodeTimeline)
}

type advancePhaseInput struct {
	ProjectID        mgr.ProjectID `json:"projectID"`
	AcknowledgeStale bool          `json:"acknowledgeStale"`
}

type advancePhaseOutput struct {
	Result mgr.PhaseAdvanceResult `json:"result"`
}

type createProjectInput struct {
	Owner mgr.OwnerScope `json:"owner"`
	Name  string         `json:"name"`
}

type createProjectOutput struct {
	Result mgr.ProjectID `json:"result"`
}

type getProjectInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type getProjectOutput struct {
	Result mgr.ProjectState `json:"result"`
}

type getSessionStateInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
}

type getSessionStateOutput struct {
	Result mgr.SessionStateView `json:"result"`
}

type getDesignHealthInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type getDesignHealthOutput struct {
	Result mgr.DesignHealth `json:"result"`
}

type listProjectsInput struct {
	Owner mgr.OwnerScope `json:"owner"`
}

type listProjectsOutput struct {
	Result []mgr.ProjectSummary `json:"result"`
}

type requestArtifactDraftInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Kind      mgr.ArtifactKind    `json:"kind"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type requestArtifactDraftOutput struct {
	Result mgr.SessionRef `json:"result"`
}

type setOperatingModelInput struct {
	ProjectID mgr.ProjectID      `json:"projectID"`
	Model     mgr.OperatingModel `json:"model"`
}

type setOperatingModelOutput struct {
	Result mgr.Version `json:"result"`
}

type setResearchInputInput struct {
	ProjectID mgr.ProjectID     `json:"projectID"`
	Research  mgr.ResearchInput `json:"research"`
}

type setResearchInputOutput struct {
	Result mgr.Version `json:"result"`
}

type askQuestionsInput struct {
	ProjectID mgr.ProjectID         `json:"projectID"`
	Kind      mgr.ArtifactKind      `json:"kind"`
	Addressee string                `json:"addressee"`
	Questions []mgr.AnchoredComment `json:"questions"`
}

type askQuestionsOutput struct{}

type acknowledgeStaleBasisInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
	Note      string           `json:"note"`
}

type acknowledgeStaleBasisOutput struct{}

type setReviewCommentStatusInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
	CommentID string           `json:"commentID"`
	Status    string           `json:"status"`
}

type setReviewCommentStatusOutput struct{}

type startSystemDesignInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type startSystemDesignOutput struct {
	Result mgr.SessionRef `json:"result"`
}

type submitReviewDecisionInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Kind      mgr.ArtifactKind    `json:"kind"`
	Decision  mgr.ReviewDecision  `json:"decision"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type submitReviewDecisionOutput struct{}

type listEpisodesForArtifactInput struct {
	ProjectID    mgr.ProjectID    `json:"projectID"`
	ArtifactKind mgr.ArtifactKind `json:"artifactKind"`
}

type listEpisodesForArtifactOutput struct {
	Result []mgr.EpisodeRecordView `json:"result"`
}

type getEpisodeTimelineInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
	EpisodeID string        `json:"episodeID"`
}

type getEpisodeTimelineOutput struct {
	Result mgr.EpisodeTimeline `json:"result"`
}

// advancePhaseInputSchema is the explicit MCP input schema for the AdvancePhase operation.
func advancePhaseInputSchema() *jsonschema.Schema {
	s := objectSchema[advancePhaseInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "acknowledgeStale"}
	return s
}

// createProjectInputSchema is the explicit MCP input schema for the CreateProject operation.
func createProjectInputSchema() *jsonschema.Schema {
	s := objectSchema[createProjectInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"owner", "name"}
	return s
}

// getProjectInputSchema is the explicit MCP input schema for the GetProject operation.
func getProjectInputSchema() *jsonschema.Schema {
	s := objectSchema[getProjectInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID"}
	return s
}

// getSessionStateInputSchema is the explicit MCP input schema for the GetSessionState operation.
func getSessionStateInputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// getDesignHealthInputSchema is the explicit MCP input schema for the GetDesignHealth operation.
func getDesignHealthInputSchema() *jsonschema.Schema {
	s := objectSchema[getDesignHealthInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID"}
	return s
}

// listProjectsInputSchema is the explicit MCP input schema for the ListProjects operation.
func listProjectsInputSchema() *jsonschema.Schema {
	s := objectSchema[listProjectsInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"owner"}
	return s
}

// requestArtifactDraftInputSchema is the explicit MCP input schema for the RequestArtifactDraft operation.
func requestArtifactDraftInputSchema() *jsonschema.Schema {
	s := objectSchema[requestArtifactDraftInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// setOperatingModelInputSchema is the explicit MCP input schema for the SetOperatingModel operation.
func setOperatingModelInputSchema() *jsonschema.Schema {
	s := objectSchema[setOperatingModelInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "model"}
	return s
}

// setResearchInputInputSchema is the explicit MCP input schema for the SetResearchInput operation.
func setResearchInputInputSchema() *jsonschema.Schema {
	s := objectSchema[setResearchInputInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "research"}
	return s
}

// askQuestionsInputSchema is the explicit MCP input schema for the AskQuestions operation.
func askQuestionsInputSchema() *jsonschema.Schema {
	s := objectSchema[askQuestionsInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind", "addressee", "questions"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// acknowledgeStaleBasisInputSchema is the explicit MCP input schema for the AcknowledgeStaleBasis operation.
func acknowledgeStaleBasisInputSchema() *jsonschema.Schema {
	s := objectSchema[acknowledgeStaleBasisInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind", "note"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// setReviewCommentStatusInputSchema is the explicit MCP input schema for the SetReviewCommentStatus operation.
func setReviewCommentStatusInputSchema() *jsonschema.Schema {
	s := objectSchema[setReviewCommentStatusInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind", "commentID", "status"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// startSystemDesignInputSchema is the explicit MCP input schema for the StartSystemDesign operation.
func startSystemDesignInputSchema() *jsonschema.Schema {
	s := objectSchema[startSystemDesignInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID"}
	return s
}

// submitReviewDecisionInputSchema is the explicit MCP input schema for the SubmitReviewDecision operation.
func submitReviewDecisionInputSchema() *jsonschema.Schema {
	s := objectSchema[submitReviewDecisionInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind", "decision"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	s.Properties["decision"] = enumSchemaReviewDecision()
	return s
}

// listEpisodesForArtifactInputSchema is the explicit MCP input schema for the ListEpisodesForArtifact operation.
func listEpisodesForArtifactInputSchema() *jsonschema.Schema {
	s := objectSchema[listEpisodesForArtifactInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "artifactKind"}
	s.Properties["artifactKind"] = enumSchemaArtifactKind()
	return s
}

// getEpisodeTimelineInputSchema is the explicit MCP input schema for the GetEpisodeTimeline operation.
func getEpisodeTimelineInputSchema() *jsonschema.Schema {
	s := objectSchema[getEpisodeTimelineInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "episodeID"}
	return s
}

// advancePhaseOutputSchema is the explicit MCP output schema for the AdvancePhase operation.
func advancePhaseOutputSchema() *jsonschema.Schema {
	s := objectSchema[advancePhaseOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[advancePhaseOutput]())
	return s
}

// createProjectOutputSchema is the explicit MCP output schema for the CreateProject operation.
func createProjectOutputSchema() *jsonschema.Schema {
	s := objectSchema[createProjectOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[createProjectOutput]())
	return s
}

// getProjectOutputSchema is the explicit MCP output schema for the GetProject operation.
func getProjectOutputSchema() *jsonschema.Schema {
	s := objectSchema[getProjectOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[getProjectOutput]())
	return s
}

// getSessionStateOutputSchema is the explicit MCP output schema for the GetSessionState operation.
func getSessionStateOutputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[getSessionStateOutput]())
	return s
}

// getDesignHealthOutputSchema is the explicit MCP output schema for the GetDesignHealth operation.
func getDesignHealthOutputSchema() *jsonschema.Schema {
	s := objectSchema[getDesignHealthOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[getDesignHealthOutput]())
	return s
}

// listProjectsOutputSchema is the explicit MCP output schema for the ListProjects operation.
func listProjectsOutputSchema() *jsonschema.Schema {
	s := objectSchema[listProjectsOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[listProjectsOutput]())
	return s
}

// requestArtifactDraftOutputSchema is the explicit MCP output schema for the RequestArtifactDraft operation.
func requestArtifactDraftOutputSchema() *jsonschema.Schema {
	s := objectSchema[requestArtifactDraftOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[requestArtifactDraftOutput]())
	return s
}

// setOperatingModelOutputSchema is the explicit MCP output schema for the SetOperatingModel operation.
func setOperatingModelOutputSchema() *jsonschema.Schema {
	s := objectSchema[setOperatingModelOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[setOperatingModelOutput]())
	return s
}

// setResearchInputOutputSchema is the explicit MCP output schema for the SetResearchInput operation.
func setResearchInputOutputSchema() *jsonschema.Schema {
	s := objectSchema[setResearchInputOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[setResearchInputOutput]())
	return s
}

// askQuestionsOutputSchema is the explicit MCP output schema for the AskQuestions operation.
func askQuestionsOutputSchema() *jsonschema.Schema {
	s := objectSchema[askQuestionsOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[askQuestionsOutput]())
	return s
}

// acknowledgeStaleBasisOutputSchema is the explicit MCP output schema for the AcknowledgeStaleBasis operation.
func acknowledgeStaleBasisOutputSchema() *jsonschema.Schema {
	s := objectSchema[acknowledgeStaleBasisOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[acknowledgeStaleBasisOutput]())
	return s
}

// setReviewCommentStatusOutputSchema is the explicit MCP output schema for the SetReviewCommentStatus operation.
func setReviewCommentStatusOutputSchema() *jsonschema.Schema {
	s := objectSchema[setReviewCommentStatusOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[setReviewCommentStatusOutput]())
	return s
}

// startSystemDesignOutputSchema is the explicit MCP output schema for the StartSystemDesign operation.
func startSystemDesignOutputSchema() *jsonschema.Schema {
	s := objectSchema[startSystemDesignOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[startSystemDesignOutput]())
	return s
}

// submitReviewDecisionOutputSchema is the explicit MCP output schema for the SubmitReviewDecision operation.
func submitReviewDecisionOutputSchema() *jsonschema.Schema {
	s := objectSchema[submitReviewDecisionOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[submitReviewDecisionOutput]())
	return s
}

// listEpisodesForArtifactOutputSchema is the explicit MCP output schema for the ListEpisodesForArtifact operation.
func listEpisodesForArtifactOutputSchema() *jsonschema.Schema {
	s := objectSchema[listEpisodesForArtifactOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[listEpisodesForArtifactOutput]())
	return s
}

// getEpisodeTimelineOutputSchema is the explicit MCP output schema for the GetEpisodeTimeline operation.
func getEpisodeTimelineOutputSchema() *jsonschema.Schema {
	s := objectSchema[getEpisodeTimelineOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	describeContractFields(s, reflect.TypeFor[getEpisodeTimelineOutput]())
	return s
}

// contractFieldDescriptions is the contract's own property documentation,
// keyed by the Go type modelgen emits for each documenting $def. modelgen
// carries no description into those types, so the inferred output schema
// would otherwise show an agent a field's shape but never the contract's
// statement of when that field means nothing.
var contractFieldDescriptions = map[reflect.Type]map[string]string{
	reflect.TypeFor[mgr.ActivityConstructionStatus](): {
		"BuildStatus":   "The coarse build status. Meaningless when hasBuildEvidence is false (or classified is false): its zero value names InConstruction, which on such a row reports nothing, not work in progress. Read it only when both flags are true.",
		"Phase":         "The coarse lifecycle-phase roll-up. Meaningless when hasBuildEvidence is false (or classified is false): nothing has been resolved to roll up, so the value is the enum's zero, not a reported phase. Read it only when both flags are true.",
		"operatorNotes": "Every note an operator recorded against this activity (a send-back's feedback, a steer's reason), append-only and in recorded order. A note is pending until an agent dispatch carries it; then it names that dispatch's attempt. Omitted when there are none.",
		"pendingResume": "Present iff no construction pump wrote this row (no stored coarse phase past NotStarted, no stored phase set) yet its attempt ledger resolves some lifecycle phases complete and others not: an integration-pending row the backfill recorded. It is NOT in flight (nothing is running it) and it is not under review. Omitted on every other row: not started, pump-written, and done.",
		"recorded":      "True iff a stored .activityConstruction head-state row exists for this activity. False on a planned-no-record row: one the server emits because the committed activity list names the activity but nothing has been recorded for it yet. Such a row carries no attempts and no worstOrigin, and its BuildStatus and Phase are meaningless.",
		"worstOrigin":   "The least-trustworthy provenance origin across attempts (synthesized, then backfilled, then observed). Omitted when recorded is false. Meaningless when attempts is empty: the roll-up seeds an empty ledger to observed, which says nothing was derived from anything unknown, not that anything was observed.",
	},
	reflect.TypeFor[mgr.NoteComment](): {
		"jsonPath": "Where the comment is anchored in the artifact under review, as a JSONPath.",
		"text":     "The comment, verbatim.",
	},
	reflect.TypeFor[mgr.OperatorNote](): {
		"comments":             "Anchored comments that rode with the note. Omitted when there are none.",
		"deliveredAt":          "When the delivery was recorded. Omitted while the note is pending.",
		"deliveredToAttemptId": "The AttemptID (\"<activityId>:<task>:<n>\", the TargetRef of that dispatch's episode) of the agent dispatch that carried this note. Omitted while the note is pending, and always for a skip note, which nothing runs after.",
		"gate":                 "The gate the note was written at: a lifecycle phase's wire name, \"merge\" or \"takeover\". Omitted when none applies.",
		"kind":                 "Why the note was written.",
		"noteId":               "The note's id.",
		"recordedAt":           "When the store recorded the note (server clock).",
		"text":                 "The operator's note, verbatim.",
	},
	reflect.TypeFor[mgr.PendingDependency](): {
		"id":     "The dependency id as the network authors it: an activity id or a milestone id.",
		"reason": "Why it is unsatisfied. notBuilt: an activity that is not Done. builtNotIntegrated: an activity that is itself integration-pending. milestoneNotReached: a milestone whose own dependencies are not all satisfied. unresolved: an id naming neither an activity nor a milestone, or a milestone cycle (a plan defect).",
	},
	reflect.TypeFor[mgr.PendingResume](): {
		"fromPhase": "The first lifecycle phase of the row's profile that its resolved phase set does not hold complete: the phase the pump would run first.",
		"waitsOn":   "The row's direct network dependencies that are not satisfied, in authored order. Empty when every dependency is satisfied: the row is next in line.",
	},
	reflect.TypeFor[mgr.ProjectState](): {
		"constructionStarted": "True iff construction has started for this project: some stored .activityConstruction row carries state only the construction pump writes (a start time, a coarse phase past NotStarted, a phase set, or a recorded failure) or an attempt of origin observed. Reconstructed attempts (backfilled or synthesized) never count, and a planned-no-record row has no stored state to count. Decides Begin versus Resume.",
	},
}

// describeContractFields stamps contractFieldDescriptions onto an inferred
// schema, walking it in step with the Go type it was inferred from, so a
// description lands only on the property the contract documents — wherever
// that type appears in the output (a map value, a slice element, a field).
// It runs LAST: relaxRawJSON may replace a node wholesale, and a description
// written before that would be lost with it.
func describeContractFields(s *jsonschema.Schema, t reflect.Type) {
	if s == nil {
		return
	}
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	k := t.Kind()
	if k == reflect.Slice || k == reflect.Array {
		describeContractFields(s.Items, t.Elem())
		return
	}
	if k == reflect.Map {
		describeContractFields(s.AdditionalProperties, t.Elem())
		return
	}
	if k != reflect.Struct {
		return
	}
	descs := contractFieldDescriptions[t]
	for i := range t.NumField() {
		f := t.Field(i)
		name := jsonFieldName(f)
		p, ok := s.Properties[name]
		if name == "" || !ok {
			continue
		}
		if d, ok := descs[name]; ok {
			p.Description = d
		}
		describeContractFields(p, f.Type)
	}
}

// jsonFieldName is the wire key encoding/json uses for a struct field ("" for
// an unexported or json:"-" field, which no schema property stands for).
func jsonFieldName(f reflect.StructField) string {
	if !f.IsExported() {
		return ""
	}
	name, _, _ := strings.Cut(f.Tag.Get("json"), ",")
	switch name {
	case "-":
		return ""
	case "":
		return f.Name
	}
	return name
}

// enumSchemaArtifactKind describes the ArtifactKind enum: its allowed values and their meanings.
func enumSchemaArtifactKind() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
		Description: "ArtifactKind. Allowed values: 0=KindMission, 1=KindGlossary, 2=KindScrubbedRequirements, 3=KindVolatilities, 4=KindCoreUseCases, 5=KindSystem, 6=KindOperationalConcepts, 7=KindStandardCheck, 8=KindPlanningAssumptions, 9=KindActivityList, 10=KindNetwork, 11=KindNormalSolution, 12=KindSubcriticalSolution, 13=KindCompressedSolution, 14=KindDecompressedSolution, 15=KindRiskModel, 16=KindSdpReview.",
	}
}

// enumSchemaReviewDecision describes the ReviewDecision enum: its allowed values and their meanings.
func enumSchemaReviewDecision() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2, 3},
		Description: "ReviewDecision. Allowed values: 0=ReviewDecisionUnknown, 1=ReviewApprove, 2=ReviewReject, 3=ReviewWithdraw.",
	}
}

// handleAdvancePhase is the MCP tool handler for the AdvancePhase operation.
func (h *Handler) handleAdvancePhase(ctx context.Context, _ *mcp.CallToolRequest, in advancePhaseInput) (*mcp.CallToolResult, advancePhaseOutput, error) {
	var out advancePhaseOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.AdvancePhase(rc, in.ProjectID, in.AcknowledgeStale)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleCreateProject is the MCP tool handler for the CreateProject operation.
func (h *Handler) handleCreateProject(ctx context.Context, _ *mcp.CallToolRequest, in createProjectInput) (*mcp.CallToolResult, createProjectOutput, error) {
	var out createProjectOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.CreateProject(rc, in.Owner, in.Name)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetProject is the MCP tool handler for the GetProject operation.
func (h *Handler) handleGetProject(ctx context.Context, _ *mcp.CallToolRequest, in getProjectInput) (*mcp.CallToolResult, getProjectOutput, error) {
	var out getProjectOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetProject(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetSessionState is the MCP tool handler for the GetSessionState operation.
func (h *Handler) handleGetSessionState(ctx context.Context, _ *mcp.CallToolRequest, in getSessionStateInput) (*mcp.CallToolResult, getSessionStateOutput, error) {
	var out getSessionStateOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetSessionState(rc, in.ProjectID, in.Kind)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetDesignHealth is the MCP tool handler for the GetDesignHealth operation.
func (h *Handler) handleGetDesignHealth(ctx context.Context, _ *mcp.CallToolRequest, in getDesignHealthInput) (*mcp.CallToolResult, getDesignHealthOutput, error) {
	var out getDesignHealthOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetDesignHealth(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleListProjects is the MCP tool handler for the ListProjects operation.
func (h *Handler) handleListProjects(ctx context.Context, _ *mcp.CallToolRequest, in listProjectsInput) (*mcp.CallToolResult, listProjectsOutput, error) {
	var out listProjectsOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ListProjects(rc, in.Owner)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleRequestArtifactDraft is the MCP tool handler for the RequestArtifactDraft operation.
func (h *Handler) handleRequestArtifactDraft(ctx context.Context, _ *mcp.CallToolRequest, in requestArtifactDraftInput) (*mcp.CallToolResult, requestArtifactDraftOutput, error) {
	var out requestArtifactDraftOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.RequestArtifactDraft(rc, in.ProjectID, in.Kind, in.Feedback)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSetOperatingModel is the MCP tool handler for the SetOperatingModel operation.
func (h *Handler) handleSetOperatingModel(ctx context.Context, _ *mcp.CallToolRequest, in setOperatingModelInput) (*mcp.CallToolResult, setOperatingModelOutput, error) {
	var out setOperatingModelOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.SetOperatingModel(rc, in.ProjectID, in.Model)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSetResearchInput is the MCP tool handler for the SetResearchInput operation.
func (h *Handler) handleSetResearchInput(ctx context.Context, _ *mcp.CallToolRequest, in setResearchInputInput) (*mcp.CallToolResult, setResearchInputOutput, error) {
	var out setResearchInputOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.SetResearchInput(rc, in.ProjectID, in.Research)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleAskQuestions is the MCP tool handler for the AskQuestions operation.
func (h *Handler) handleAskQuestions(ctx context.Context, _ *mcp.CallToolRequest, in askQuestionsInput) (*mcp.CallToolResult, askQuestionsOutput, error) {
	var out askQuestionsOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.AskQuestions(rc, in.ProjectID, in.Kind, in.Addressee, in.Questions); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleAcknowledgeStaleBasis is the MCP tool handler for the AcknowledgeStaleBasis operation.
func (h *Handler) handleAcknowledgeStaleBasis(ctx context.Context, _ *mcp.CallToolRequest, in acknowledgeStaleBasisInput) (*mcp.CallToolResult, acknowledgeStaleBasisOutput, error) {
	var out acknowledgeStaleBasisOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.AcknowledgeStaleBasis(rc, in.ProjectID, in.Kind, in.Note); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleSetReviewCommentStatus is the MCP tool handler for the SetReviewCommentStatus operation.
func (h *Handler) handleSetReviewCommentStatus(ctx context.Context, _ *mcp.CallToolRequest, in setReviewCommentStatusInput) (*mcp.CallToolResult, setReviewCommentStatusOutput, error) {
	var out setReviewCommentStatusOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SetReviewCommentStatus(rc, in.ProjectID, in.Kind, in.CommentID, in.Status); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleStartSystemDesign is the MCP tool handler for the StartSystemDesign operation.
func (h *Handler) handleStartSystemDesign(ctx context.Context, _ *mcp.CallToolRequest, in startSystemDesignInput) (*mcp.CallToolResult, startSystemDesignOutput, error) {
	var out startSystemDesignOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.StartSystemDesign(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleSubmitReviewDecision is the MCP tool handler for the SubmitReviewDecision operation.
func (h *Handler) handleSubmitReviewDecision(ctx context.Context, _ *mcp.CallToolRequest, in submitReviewDecisionInput) (*mcp.CallToolResult, submitReviewDecisionOutput, error) {
	var out submitReviewDecisionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SubmitReviewDecision(rc, in.ProjectID, in.Kind, in.Decision, in.Feedback); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleListEpisodesForArtifact is the MCP tool handler for the ListEpisodesForArtifact operation.
func (h *Handler) handleListEpisodesForArtifact(ctx context.Context, _ *mcp.CallToolRequest, in listEpisodesForArtifactInput) (*mcp.CallToolResult, listEpisodesForArtifactOutput, error) {
	var out listEpisodesForArtifactOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ListEpisodesForArtifact(rc, in.ProjectID, in.ArtifactKind)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetEpisodeTimeline is the MCP tool handler for the GetEpisodeTimeline operation.
func (h *Handler) handleGetEpisodeTimeline(ctx context.Context, _ *mcp.CallToolRequest, in getEpisodeTimelineInput) (*mcp.CallToolResult, getEpisodeTimelineOutput, error) {
	var out getEpisodeTimelineOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetEpisodeTimeline(rc, in.ProjectID, in.EpisodeID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// --- helpers ---------------------------------------------------------------

// objectSchema infers the base object JSON Schema for a tool input struct via
// the SDK's reflection (the same inference the SDK would run for a nil input
// schema), so nested object/array params keep their structural shape; callers
// then override the required list and any enum properties. It panics on an
// un-inferrable type — a build-time contract error surfaced at server start.
func objectSchema[T any]() *jsonschema.Schema {
	s, err := jsonschema.For[T](nil)
	if err != nil {
		panic(fmt.Sprintf("mcp input schema inference: %v", err))
	}
	if s.Properties == nil {
		s.Properties = map[string]*jsonschema.Schema{}
	}
	return s
}

// fixUUIDStrings walks an inferred schema and retypes every uuid.UUID ([16]byte)
// property from the SDK's structural inference (an array of 16 0-255 bytes) to
// the schema the value actually marshals as on the wire: a string in RFC 4122
// form. It MUST run before relaxRawJSON, which would otherwise blank the same
// node as an indistinguishable raw-byte-array signature (T11 finding).
func fixUUIDStrings(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isUUIDArray(s) {
		*s = jsonschema.Schema{Type: "string", Format: "uuid"}
		return
	}
	for _, p := range s.Properties {
		fixUUIDStrings(p)
	}
	fixUUIDStrings(s.Items)
	fixUUIDStrings(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		fixUUIDStrings(p)
	}
}

// isUUIDArray reports whether a schema is the jsonschema-go signature of a Go
// uuid.UUID ([16]byte): the same raw-byte-array shape as isRawByteArray, further
// narrowed to exactly 16 items (a fixed-size array), which is unique to UUIDs
// among this codebase's byte-carrier fields.
func isUUIDArray(s *jsonschema.Schema) bool {
	if !isRawByteArray(s) {
		return false
	}
	return s.MinItems != nil && *s.MinItems == 16 && s.MaxItems != nil && *s.MaxItems == 16
}

// relaxRawJSON walks an inferred schema and relaxes every json.RawMessage /
// []byte JSON-carrier property to a permissive (accept-anything) schema. The SDK
// infers such a Go field as an array of 0-255 bytes, which rejects the real JSON
// object/string the manager actually emits or accepts (QA finding F26); the rest
// of the inferred shape is preserved. The permissive schema carries a
// Description so it marshals as a JSON OBJECT (`{"description":...}`) rather
// than the zero-value Schema{}, which the library marshals as bare JSON `true`
// — valid JSON Schema, but rejected by the TS MCP SDK's Zod validator, which
// requires every property schema to be an object (T11 finding).
func relaxRawJSON(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isRawByteArray(s) {
		*s = jsonschema.Schema{Description: "any JSON value"}
		return
	}
	for _, p := range s.Properties {
		relaxRawJSON(p)
	}
	relaxRawJSON(s.Items)
	relaxRawJSON(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		relaxRawJSON(p)
	}
}

// isRawByteArray reports whether a schema is the jsonschema-go signature of a Go
// []byte / json.RawMessage: an array (possibly nullable) whose items are bytes
// (integer, 0..255).
func isRawByteArray(s *jsonschema.Schema) bool {
	isArray := s.Type == "array"
	for _, t := range s.Types {
		if t == "array" {
			isArray = true
		}
	}
	if !isArray || s.Items == nil {
		return false
	}
	it := s.Items
	if it.Type != "integer" {
		return false
	}
	return it.Minimum != nil && *it.Minimum == 0 && it.Maximum != nil && *it.Maximum == 255
}

// allowNullMaps walks an inferred schema and unions "null" into every Go-map
// node's type. jsonschema-go infers a Go map as a bare {type:"object"}, but a
// nil map marshals to JSON null (unlike a nil slice, which the library already
// types as ["null","array"]). Read models legitimately emit nil maps in early
// project phases (e.g. ProjectState.ActivityConstruction before construction),
// so the honest schema must accept null there — otherwise the SDK's output
// validation rejects a payload the HTTP surface serves fine (QA finding F29).
func allowNullMaps(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isMapNode(s) {
		s.Types = []string{"null", "object"}
		s.Type = ""
	}
	for _, p := range s.Properties {
		allowNullMaps(p)
	}
	allowNullMaps(s.Items)
	allowNullMaps(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		allowNullMaps(p)
	}
}

// isMapNode reports whether a schema node is jsonschema-go's inference of a Go
// map: an object node carrying an additionalProperties element schema. A struct
// is also typed "object" but sets additionalProperties to the false schema
// (Not set), which this distinguishes so struct nodes are never made nullable.
func isMapNode(s *jsonschema.Schema) bool {
	isObject := s.Type == "object"
	for _, t := range s.Types {
		if t == "object" {
			isObject = true
		}
	}
	ap := s.AdditionalProperties
	return isObject && ap != nil && ap.Not == nil
}

func mapManagerError(err error) error {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		return fmt.Errorf("%s: %s", me.Kind.String(), me.Detail)
	}
	return err
}
