// Code generated by webgen (framework-go-app-generator). DO NOT EDIT.
/// <reference types="node" />
/**
 * Every preview fixture validates against preview/fixtures.schema.json, the
 * fixture JSON Schema webgen generates from the server OAS: its ops keys are the
 * OpsClient's OpIds and each result is checked against the op's 200 schema. A
 * fixture the preview entry happens not to import is checked all the same, and
 * so is the rule that fixture data never carries a bundle marker.
 *
 * The root is ARCHISTRATOR_PREVIEW_FIXTURES (relative to the webApp), defaulting to
 * preview/fixtures. An absent <root>/web-client is a build with no states.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  compileFixtureValidator,
  validateFixtureTree,
} from '@mixofreality-studio/archistrator-platform-framework-web/preview/node';

const webApp = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const schema: unknown = JSON.parse(
  readFileSync(resolve(webApp, 'preview', 'fixtures.schema.json'), 'utf8')
);
const fixturesEnv = process.env['ARCHISTRATOR_PREVIEW_FIXTURES'];
const root = resolve(webApp, fixturesEnv ?? 'preview/fixtures');

void test('every preview fixture validates against the OAS-generated schema', () => {
  const { errors } = validateFixtureTree(root, {
    surface: 'web-client',
    validate: compileFixtureValidator(schema),
  });
  assert.deepEqual(errors, []);
});
