/**
 * The preview build's Vite plugin (design-renderer-data.md §2′.1):
 *
 *   - when the build starts, every fixture under <fixturesRoot>/<surface> is
 *     validated against the OAS-generated schema; one invalid fixture fails the
 *     build;
 *   - the entry, preview.html at the source root, is served as index.html;
 *   - the schema ships beside the bundle as fixtures.schema.json.
 */
import { readFileSync } from 'node:fs';
import type { Plugin } from 'vite';
import { compileFixtureValidator, validateFixtureTree } from './fixtureTree.ts';

export interface PreviewFixturesOptions {
  /** The fixture root; fixtures are <fixturesRoot>/<surface>/<screen>/<state>.json. */
  readonly fixturesRoot: string;
  /** The UI surface (slot-5 client id), e.g. "web-client". */
  readonly surface: string;
  /** preview/fixtures.schema.json, generated by webgen. */
  readonly schemaPath: string;
}

export function previewFixtures(options: PreviewFixturesOptions): Plugin {
  const schemaText = (): string => readFileSync(options.schemaPath, 'utf8');
  return {
    name: 'archistrator-preview-fixtures',
    apply: 'build',
    // After Vite's own HTML plugin, which emits preview.html in its generateBundle;
    // a normal-order plugin runs first and would find nothing to rename.
    enforce: 'post',
    buildStart() {
      const validate = compileFixtureValidator(JSON.parse(schemaText()));
      const { files, errors } = validateFixtureTree(options.fixturesRoot, {
        surface: options.surface,
        validate,
      });
      if (errors.length > 0) {
        this.error(`preview fixtures fail the OAS-generated schema:\n  ${errors.join('\n  ')}`);
      }
      this.info(
        `${String(files.length)} fixture state(s) from ${options.fixturesRoot}/${options.surface}`
      );
    },
    generateBundle(_options, bundle) {
      const html = bundle['preview.html'];
      if (html?.type === 'asset') {
        delete bundle['preview.html'];
        this.emitFile({ type: 'asset', fileName: 'index.html', source: html.source });
      }
      this.emitFile({ type: 'asset', fileName: 'fixtures.schema.json', source: schemaText() });
    },
  };
}
