// Package modelgen generates each component's Go model structs + service-contract
// interface from a project.json document — step 2 of the contract pipeline. The
// `.serviceContracts` map in `.aiarch/state/project.json` is the OWNER of the
// contracts: each built entry carries a contract document (`title`, `$defs`,
// `interface`) plus self-describing metadata (`component`, `layer`, `goPackage`).
// modelgen turns that document → Go, so project.json is the single source of
// truth and the Go model (`contract.gen.go`) is a generated output.
//
// All-Go: the emitter is built directly on github.com/google/jsonschema-go — the
// SAME complete draft 2020-12 implementation used for reflection (bundled
// meta-schemas, $ref/$dynamicRef resolution). No quicktype, no Node, no external
// codegen tool whose bugs we'd inherit. The emitter is owned so support is
// exhaustive and failures are explicit, never silent.
//
// For each `.serviceContracts` entry with a non-empty `goPackage` Generate
// returns `<goPackage>/contract.gen.go` bytes (e.g. keyed by
// internal/resourceaccess/artifact), in a package named after the goPackage's
// last segment. Entries without a `goPackage` are skipped. An entry flagged
// `"stub": true` is CONTRACTED-BUT-UNBUILT: it still carries a goPackage + $defs +
// interface, and modelgen emits a fully generated not-implemented impl for it
// (see emitStubImpl).
//
// This is the library form of archistrator's server/cmd/modelgen (a thin CLI
// shim now wraps it). The module path and engine-impl allowlist — the only two
// project-specific inputs — are supplied via Config; everything else (the
// header string, the raw-JSON property-order recovery, the infra-bindings
// registry) is a faithful, byte-identical port.
package modelgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"sort"

	"github.com/google/jsonschema-go/jsonschema"
)

// Config parameterizes Generate with the only two project-specific inputs.
type Config struct {
	// ModulePath is the Go module path of the target server tree — the prefix
	// modelgen prepends to a dep's `goPackage` (e.g.
	// internal/resourceaccess/projectstate) to form the full import path of the
	// dep's published-interface package (see emitManagerConstructor). For
	// archistrator this is "github.com/mixofreality-studio/archistrator/server".
	ModulePath string
	// EngineImplAllowlist is the set of Engine contract `component` keys that gain
	// a generated impl struct + constructor. Engines carry no `infra` field, so an
	// explicit allowlist scopes the impl emission. All current engines are pure
	// (field-less impl, no-arg constructor).
	EngineImplAllowlist []string
}

// schemaFile names the legacy per-component seed; retained only so the generated
// file's "Code generated by … from <schemaFile>" header byte-matches the prior
// output (the contracts now live in project.json — see the package doc).
const schemaFile = "contract.schema.json"

// contractMeta is the self-describing metadata carried alongside a contract
// document: goPackage selects built entries (stubs have none) AND gives the
// output dir + package name (empty ⇒ skip); component + infra drive the
// GENERATED IMPL surface; stub flags a contracted-but-unbuilt component; deps
// declare a manager's constructor dependencies.
type contractMeta struct {
	GoPackage string        `json:"goPackage"`
	Component string        `json:"component"`
	Infra     []string      `json:"infra"`
	Stub      bool          `json:"stub"`
	Deps      []contractDep `json:"deps"`
}

// Generate emits every built component's contract.gen.go from the project.json
// document, keyed by the contract's goPackage. Entries without a goPackage are
// skipped. An error carries the offending contract's key.
func Generate(projectJSON []byte, cfg Config) (map[string][]byte, error) {
	if cfg.ModulePath == "" {
		return nil, fmt.Errorf("modelgen: Config.ModulePath is empty")
	}
	contracts, err := parseServiceContracts(projectJSON)
	if err != nil {
		return nil, err
	}
	resolver, err := buildResolver(contracts)
	if err != nil {
		return nil, err
	}
	allow := toSet(cfg.EngineImplAllowlist)

	keys := make([]string, 0, len(contracts))
	for k := range contracts {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	out := map[string][]byte{}
	for _, k := range keys {
		goPkg, src, err := emitContract(k, contracts[k], cfg.ModulePath, allow, resolver)
		if err != nil {
			return nil, err
		}
		if goPkg == "" { // no goPackage ⇒ skip (stub / unbuilt entry)
			continue
		}
		out[goPkg] = src
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("no built service contracts (with goPackage) found")
	}
	return out, nil
}

// emitContract processes one .serviceContracts entry: it returns the entry's
// goPackage + formatted bytes, or an empty goPackage to signal "skip" (no
// goPackage). Errors carry the contract key, preserving the source's two fatal
// prefixes ("parse contract" vs "modelgen").
func emitContract(k string, entry json.RawMessage, modulePath string, allow map[string]bool, resolver map[string]contractRef) (string, []byte, error) {
	var meta contractMeta
	if err := json.Unmarshal(entry, &meta); err != nil {
		return "", nil, fmt.Errorf("parse contract %q: %w", k, err)
	}
	if meta.GoPackage == "" {
		return "", nil, nil
	}
	src, err := genOne(entry, meta, modulePath, allow, resolver)
	if err != nil {
		return "", nil, fmt.Errorf("modelgen %s: %w", k, err)
	}
	return meta.GoPackage, src, nil
}

// parseServiceContracts pulls each contract entry out of project.json as RAW
// JSON so $defs property order and interface param order survive untouched (the
// basis of the byte-identical regen) — exactly as the old per-component file did.
func parseServiceContracts(projectJSON []byte) (map[string]json.RawMessage, error) {
	var top map[string]json.RawMessage
	if err := json.Unmarshal(projectJSON, &top); err != nil {
		return nil, fmt.Errorf("parse project.json: %w", err)
	}
	var contracts map[string]json.RawMessage
	if err := json.Unmarshal(top["serviceContracts"], &contracts); err != nil {
		return nil, fmt.Errorf("parse .serviceContracts: %w", err)
	}
	return contracts, nil
}

// buildResolver maps each contract key → its published interface coordinates
// (goPackage + interface name). A MANAGER contract's `deps` reference dependency
// components by their contract key; modelgen resolves each to a constructor param
// typed as the dep's GENERATED/published interface (see emitManagerConstructor).
func buildResolver(contracts map[string]json.RawMessage) (map[string]contractRef, error) {
	resolver := map[string]contractRef{}
	for k, entry := range contracts {
		var ref struct {
			GoPackage string `json:"goPackage"`
			Interface struct {
				Name string `json:"name"`
			} `json:"interface"`
		}
		if err := json.Unmarshal(entry, &ref); err != nil {
			return nil, fmt.Errorf("parse contract %q for resolver: %w", k, err)
		}
		resolver[k] = contractRef{goPackage: ref.GoPackage, iface: ref.Interface.Name}
	}
	return resolver, nil
}

// toSet turns the config allowlist slice into a membership set.
func toSet(keys []string) map[string]bool {
	set := make(map[string]bool, len(keys))
	for _, k := range keys {
		set[k] = true
	}
	return set
}

// genOne emits one component's contract.gen.go from its project.json contract
// entry (raw JSON) and returns the formatted bytes. The entry is a superset of
// the old contract.schema.json (it adds component/layer/goPackage/title around the
// same `$defs` + `interface`), so it feeds the UNCHANGED emission path directly:
// the extra metadata keys land in Schema.Extra and are ignored, while $defs and
// interface are read exactly as before — keeping the output byte-identical.
func genOne(raw []byte, meta contractMeta, modulePath string, allow map[string]bool, resolver map[string]contractRef) ([]byte, error) {
	pkg := filepath.Base(meta.GoPackage)

	// Emit the type/interface body first so x-go-type bindings can register their
	// imports (collected in pendingImports) before the import block is written.
	pendingImports = map[string]string{}
	var buf bytes.Buffer

	doc, err := emitTypesBody(&buf, raw)
	if err != nil {
		return nil, err
	}

	// Interface (the RPC surface) lives under the document's `interface` key,
	// carried via jsonschema-go's Extra map. Re-decode it into the typed
	// descriptor and emit the Go interface.
	iface, haveIface, err := decodeAndEmitInterface(&buf, doc)
	if err != nil {
		return nil, err
	}

	if haveIface {
		if err := emitImplSurface(&buf, iface, meta, modulePath, allow, resolver); err != nil {
			return nil, err
		}
	}

	return formatGeneratedFile(pkg, &buf)
}

// emitTypesBody parses one contract document's raw JSON and writes ONLY its
// $defs type block (structs/enums/sums + their codecs) into buf, returning the
// parsed schema for callers (genOne) that go on to emit more from the same
// document. It is the single emission path shared by genOne (Generate) and
// EmitTypes — the two never diverge because they run the identical code.
func emitTypesBody(buf *bytes.Buffer, raw []byte) (*jsonschema.Schema, error) {
	var doc jsonschema.Schema
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("parse schema: %w", err)
	}
	// Every built contract MUST carry model `$defs` — the generated file's whole
	// purpose is to be the component's public type surface.
	if len(doc.Defs) == 0 {
		return nil, fmt.Errorf("schema has no $defs (every built contract must declare its model types)")
	}

	// Property order is lost when $defs is unmarshaled into a Go map, so recover it
	// from the raw JSON for clean, stable, diff-friendly output.
	order := propOrder(raw)

	if _, err := emitDefs(buf, &doc, order); err != nil {
		return nil, err
	}
	return &doc, nil
}

// TypeOptions configures EmitTypes.
type TypeOptions struct {
	// PackageName is the emitted file's package name (required).
	PackageName string
	// UUIDAsString, when true, emits a uuid.UUID-bound scalar (a $defs node or
	// struct field carrying x-go-type "uuid.UUID") as a plain `string` instead,
	// and never imports "github.com/google/uuid" — for a zero-non-stdlib-import
	// client mirror. The wire representation is unchanged (a uuid already
	// marshals to its canonical string form); only the emitted Go type differs.
	// false (the default) reproduces Generate's own behavior verbatim.
	UUIDAsString bool
}

// EmitTypes emits ONLY the types block for one contract document — header +
// package + imports + the $defs type block (structs/enums/sums with their
// codecs). It emits NO interface and NO impls/DI constructors: unlike
// Generate, it is not tied to a manager's server-side wiring, so client-side
// mirrors (framework-go-app-generator/transportgen and friends) can reuse the
// exact same DTOs Generate emits for the manager without linking against the
// manager's dependencies or layer plumbing.
//
// EmitTypes shares its emission path with Generate byte-for-byte (both run
// emitTypesBody): with UUIDAsString=false, EmitTypes' output for a given
// contract's $defs is exactly the types-block prefix of what Generate emits
// for the same document.
func EmitTypes(raw json.RawMessage, opts TypeOptions) ([]byte, error) {
	if opts.PackageName == "" {
		return nil, fmt.Errorf("modelgen: TypeOptions.PackageName is empty")
	}

	pendingImports = map[string]string{}
	uuidAsString = opts.UUIDAsString
	defer func() { uuidAsString = false }()

	var buf bytes.Buffer
	if _, err := emitTypesBody(&buf, raw); err != nil {
		return nil, err
	}
	return formatGeneratedFile(opts.PackageName, &buf)
}
