package modelgen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
)

// pendingImports accumulates package imports needed during a single genOne pass,
// mapping import path -> alias ("" = no alias). It is reset at the start of every
// genOne, matching the source emitter's one-file-at-a-time model.
var pendingImports = map[string]string{}

// fakeHeader is fake.gen.go's DO NOT EDIT header — deliberately distinct from
// contract.gen.go's (see formatGeneratedFile): its regen source is
// project.json's `interface`, not contract.schema.json, and its regen command
// is gen-fakes, not gen-models. Reusing the contract header on a fake file
// would misdescribe how to regenerate it.
const fakeHeader = "// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.\n" +
	"// Edit project.json's `interface` and re-run `make gen-fakes` instead.\n\n"

// formatGeneratedFile assembles header + package + collected imports + body and
// gofmt's the result, returning the formatted bytes.
func formatGeneratedFile(pkg string, buf *bytes.Buffer) ([]byte, error) {
	header := fmt.Sprintf("// Code generated by cmd/modelgen from %s; DO NOT EDIT.\n// Edit the schema and re-run `make gen-models` instead.\n\n", schemaFile)
	return assembleFormatted(pkg, header, buf)
}

// formatGeneratedFakeFile is formatGeneratedFile's fake-package counterpart:
// identical header+package+imports+body assembly and gofmt pass, with
// fakeHeader in place of contract.gen.go's header.
func formatGeneratedFakeFile(pkg string, buf *bytes.Buffer) ([]byte, error) {
	return assembleFormatted(pkg, fakeHeader, buf)
}

// assembleFormatted assembles header + package + collected imports + body and
// gofmt's the result, returning the formatted bytes — the shared bottom half
// of formatGeneratedFile and formatGeneratedFakeFile.
func assembleFormatted(pkg, header string, buf *bytes.Buffer) ([]byte, error) {
	var out2 bytes.Buffer
	out2.WriteString(header)
	fmt.Fprintf(&out2, "package %s\n\n", pkg)
	writePendingImports(&out2)
	out2.Write(buf.Bytes())

	src, err := format.Source(out2.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w\n%s", err, out2.String())
	}
	return src, nil
}

// writePendingImports renders the sorted import block collected during body
// emission (nothing when no imports were registered).
func writePendingImports(out2 *bytes.Buffer) {
	if len(pendingImports) == 0 {
		return
	}
	imps := make([]string, 0, len(pendingImports))
	for p := range pendingImports {
		imps = append(imps, p)
	}
	sort.Strings(imps)
	out2.WriteString("import (\n")
	for _, p := range imps {
		if a := pendingImports[p]; a != "" {
			fmt.Fprintf(out2, "\t%s %q\n", a, p)
		} else {
			fmt.Fprintf(out2, "\t%q\n", p)
		}
	}
	out2.WriteString(")\n\n")
}
