package modelgen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
)

// pendingImports accumulates package imports needed during a single genOne pass,
// mapping import path -> alias ("" = no alias). It is reset at the start of every
// genOne, matching the source emitter's one-file-at-a-time model.
var pendingImports = map[string]string{}

// formatGeneratedFile assembles header + package + collected imports + body and
// gofmt's the result, returning the formatted bytes.
func formatGeneratedFile(pkg string, buf *bytes.Buffer) ([]byte, error) {
	// Assemble: header + package + (imports collected during body emission) + body.
	var out2 bytes.Buffer
	fmt.Fprintf(&out2, "// Code generated by cmd/modelgen from %s; DO NOT EDIT.\n", schemaFile)
	fmt.Fprintf(&out2, "// Edit the schema and re-run `make gen-models` instead.\n\n")
	fmt.Fprintf(&out2, "package %s\n\n", pkg)
	writePendingImports(&out2)
	out2.Write(buf.Bytes())

	src, err := format.Source(out2.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w\n%s", err, out2.String())
	}
	return src, nil
}

// writePendingImports renders the sorted import block collected during body
// emission (nothing when no imports were registered).
func writePendingImports(out2 *bytes.Buffer) {
	if len(pendingImports) == 0 {
		return
	}
	imps := make([]string, 0, len(pendingImports))
	for p := range pendingImports {
		imps = append(imps, p)
	}
	sort.Strings(imps)
	out2.WriteString("import (\n")
	for _, p := range imps {
		if a := pendingImports[p]; a != "" {
			fmt.Fprintf(out2, "\t%s %q\n", a, p)
		} else {
			fmt.Fprintf(out2, "\t%q\n", p)
		}
	}
	out2.WriteString(")\n\n")
}
