// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package widget

import (
	fwra "github.com/mixofreality-studio/archistrator-platform/framework-go/resourceaccess"
)

type Widget struct {
	ID WidgetID `json:"ID"`
}

type WidgetFilter struct {
	Prefix string `json:"Prefix"`
}

type WidgetID string

// WidgetAccess is the generated service-contract interface for this component.
type WidgetAccess interface {
	GetWidget(rc fwra.Context, id WidgetID) (Widget, error)
	DeleteWidget(rc fwra.Context, id WidgetID) error
	FindWidgets(rc fwra.Context, filter *WidgetFilter) ([]WidgetID, error)
}
