package contractgen_test

import (
	"strings"
	"testing"

	"github.com/mixofreality-studio/archistrator-platform/framework-go/contractgen"
)

var minimalManagerJSON = []byte(`{
  "component": "designManager",
  "layer": "Manager",
  "ops": [
    {
      "signature": "draftArtifact(projectId: ProjectID) → ArtifactDraft",
      "inputs": [{"name": "ProjectId", "type": "uuid.UUID"}],
      "outputs": [{"name": "ArtifactDraft", "type": "ArtifactDraft"}, {"name": "(error)", "type": "error"}]
    }
  ],
  "dataContracts": ["ProjectID = uuid.UUID"],
  "typeImports": {"uuid": "github.com/google/uuid"}
}`)

func TestParseContract_Manager(t *testing.T) {
	c, err := contractgen.ParseContract(minimalManagerJSON)
	if err != nil {
		t.Fatalf("ParseContract: %v", err)
	}
	if c.Component != "designManager" {
		t.Errorf("Component=%q, want designManager", c.Component)
	}
	if c.Layer != "Manager" {
		t.Errorf("Layer=%q, want Manager", c.Layer)
	}
	if len(c.Ops) != 1 {
		t.Errorf("len(Ops)=%d, want 1", len(c.Ops))
	}
}

func TestGenerate_ProducesGeneratedHeader(t *testing.T) {
	c, _ := contractgen.ParseContract(minimalManagerJSON)
	out, err := contractgen.Generate(c)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !strings.Contains(string(out), "// Code generated by contractgen; DO NOT EDIT.") {
		t.Errorf("generated file missing required header; got:\n%s", out)
	}
}

func TestGenerate_ProducesInterface(t *testing.T) {
	c, _ := contractgen.ParseContract(minimalManagerJSON)
	out, err := contractgen.Generate(c)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	src := string(out)
	if !strings.Contains(src, "IDesignManager") {
		t.Errorf("generated file must contain interface IDesignManager; got:\n%s", src)
	}
	if !strings.Contains(src, "DraftArtifact(") {
		t.Errorf("generated file must contain method DraftArtifact; got:\n%s", src)
	}
}

func TestGenerate_ClientLayerProducesNoInterface(t *testing.T) {
	raw := []byte(`{"component":"webClient","layer":"Client","ops":[{"signature":"showView() → void","inputs":[],"outputs":[]}],"dataContracts":[]}`)
	c, _ := contractgen.ParseContract(raw)
	out, err := contractgen.Generate(c)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if strings.Contains(string(out), "interface") {
		t.Errorf("Client layer must NOT produce a Go interface; got:\n%s", out)
	}
}

func TestGenerate_ValidGoSyntax(t *testing.T) {
	c, _ := contractgen.ParseContract(minimalManagerJSON)
	out, err := contractgen.Generate(c)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if len(out) == 0 {
		t.Fatal("Generate returned empty output")
	}
}

func TestGenerate_EmitsTypeImports(t *testing.T) {
	c, _ := contractgen.ParseContract(minimalManagerJSON)
	out, err := contractgen.Generate(c)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !strings.Contains(string(out), "github.com/google/uuid") {
		t.Errorf("generated file must import uuid package; got:\n%s", out)
	}
}

func TestValidateContract_SignatureAgreesWithOps_Passes(t *testing.T) {
	c, _ := contractgen.ParseContract(minimalManagerJSON)
	if err := contractgen.ValidateContract(c); err != nil {
		t.Fatalf("valid contract failed validation: %v", err)
	}
}

func TestValidateContract_SignatureArityMismatch_Fails(t *testing.T) {
	raw := []byte(`{
	  "component": "designManager",
	  "layer": "Manager",
	  "ops": [
	    {
	      "signature": "draftArtifact(projectId: ProjectID, extra: string) → ArtifactDraft",
	      "inputs": [{"name": "ProjectId", "type": "uuid.UUID"}],
	      "outputs": [{"name": "ArtifactDraft", "type": "ArtifactDraft"}]
	    }
	  ],
	  "dataContracts": []
	}`)
	c, _ := contractgen.ParseContract(raw)
	if err := contractgen.ValidateContract(c); err == nil {
		t.Fatal("expected arity mismatch error, got nil")
	}
}
