// Package contractgen generates typed Go interface scaffolding from an archistrator
// service-contract JSON file (the same shape as cmd/seed-contracts/data/*.json).
// Interfaces are generated only for Manager, Engine, and ResourceAccess layers.
// All generated files carry the canonical `// Code generated by contractgen; DO NOT EDIT.` header.
package contractgen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Contract is the decoded shape of a seed-contract JSON file.
type Contract struct {
	Component     string            `json:"component"`
	Layer         string            `json:"layer"`
	Ops           []Op              `json:"ops"`
	DataContracts []string          `json:"dataContracts"`
	// TypeImports maps a Go package short-name prefix (e.g. "uuid") to its
	// import path (e.g. "github.com/google/uuid"). Used to build the import block.
	TypeImports   map[string]string `json:"typeImports"`
}

// Op is one operation entry in the contract.
type Op struct {
	Signature string  `json:"signature"`
	Inputs    []Field `json:"inputs"`  // first input = request type
	Outputs   []Field `json:"outputs"` // first output = response type; last = error
}

// Field is one named+typed field from inputs/outputs.
type Field struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// ParseContract decodes raw contract JSON into a Contract.
func ParseContract(raw []byte) (Contract, error) {
	var c Contract
	if err := json.Unmarshal(raw, &c); err != nil {
		return Contract{}, fmt.Errorf("contractgen: parse: %w", err)
	}
	return c, nil
}

// ValidateContract checks that each op's free-text signature is consistent with its
// structured inputs/outputs. Returns an error if the op name or input arity disagrees.
// This is a directive-class check — disagreement is an authoring bug, not a warning.
func ValidateContract(c Contract) error {
	for i, op := range c.Ops {
		methodName := extractMethodName(op.Signature)
		sigInputs := signatureInputCount(op.Signature)
		structuredInputs := len(op.Inputs)
		if sigInputs != structuredInputs {
			return fmt.Errorf("contractgen: op %d (%s): signature has %d inputs but structured inputs has %d — signature and structured fields must agree",
				i+1, methodName, sigInputs, structuredInputs)
		}
	}
	return nil
}

// signatureInputCount counts the comma-separated params in a signature like
// "foo(a: T, b: U) → V" — returns 0 for "foo() → V".
func signatureInputCount(sig string) int {
	start := strings.IndexByte(sig, '(')
	end := strings.IndexByte(sig, ')')
	if start < 0 || end < 0 || end <= start+1 {
		return 0
	}
	params := strings.TrimSpace(sig[start+1 : end])
	if params == "" {
		return 0
	}
	return len(strings.Split(params, ","))
}

// interfaceLayers are the layers for which Generate emits a Go interface.
var interfaceLayers = map[string]bool{"Manager": true, "Engine": true, "ResourceAccess": true}

// Generate returns go/format-formatted Go source for the contract.
// For Manager/Engine/ResourceAccess it emits a typed interface + required imports.
// For other layers (Client, Resource, Utility) it emits only the package declaration and header.
func Generate(c Contract) ([]byte, error) {
	// Collect types used so we can emit the right imports.
	usedPrefixes := collectTypePrefixes(c)

	var b bytes.Buffer
	b.WriteString("// Code generated by contractgen; DO NOT EDIT.\n\n")
	b.WriteString("package generated\n\n")

	// Build import block from context + "context" always included for interface layers.
	imports := buildImports(usedPrefixes, c.TypeImports, interfaceLayers[c.Layer])
	if imports != "" {
		b.WriteString(imports)
		b.WriteString("\n")
	}

	if interfaceLayers[c.Layer] {
		ifaceName := "I" + capitalize(c.Component)
		fmt.Fprintf(&b, "// %s is the generated interface for the %s %s contract.\n", ifaceName, c.Component, c.Layer)
		fmt.Fprintf(&b, "type %s interface {\n", ifaceName)
		for _, op := range c.Ops {
			methodName := extractMethodName(op.Signature)
			reqType, respType := extractTypes(op)
			if reqType != "" {
				fmt.Fprintf(&b, "\t%s(ctx context.Context, req %s) (%s, error)\n", methodName, reqType, respType)
			} else {
				fmt.Fprintf(&b, "\t%s(ctx context.Context) (%s, error)\n", methodName, respType)
			}
		}
		b.WriteString("}\n")
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("contractgen: format Go source for %s: %w\nsource:\n%s", c.Component, err, b.String())
	}
	return src, nil
}

// collectTypePrefixes scans all types in a contract and returns the set of
// package short-name prefixes used (e.g. "uuid" from "uuid.UUID").
func collectTypePrefixes(c Contract) map[string]bool {
	seen := make(map[string]bool)
	for _, op := range c.Ops {
		for _, f := range op.Inputs {
			if p := typePrefix(f.Type); p != "" {
				seen[p] = true
			}
		}
		for _, f := range op.Outputs {
			if p := typePrefix(f.Type); p != "" {
				seen[p] = true
			}
		}
	}
	return seen
}

// typePrefix returns the package short-name from a qualified type like "uuid.UUID" → "uuid".
// Returns "" for built-in types (string, int, []byte, error, etc.).
func typePrefix(t string) string {
	t = strings.TrimLeft(t, "[]*")
	if idx := strings.IndexByte(t, '.'); idx > 0 {
		return t[:idx]
	}
	return ""
}

// buildImports returns a formatted import block string.
func buildImports(usedPrefixes map[string]bool, typeImports map[string]string, includeContext bool) string {
	var paths []string
	if includeContext {
		paths = append(paths, `"context"`)
	}
	for prefix := range usedPrefixes {
		if path, ok := typeImports[prefix]; ok {
			paths = append(paths, fmt.Sprintf("%q", path))
		}
	}
	if len(paths) == 0 {
		return ""
	}
	var b bytes.Buffer
	b.WriteString("import (\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%s\n", p)
	}
	b.WriteString(")")
	return b.String()
}

// capitalize upper-cases the first rune.
func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// extractMethodName pulls the operation name from a signature like "draftArtifact(…) → …".
func extractMethodName(sig string) string {
	idx := strings.IndexByte(sig, '(')
	if idx < 0 {
		return capitalize(sig)
	}
	return capitalize(strings.TrimSpace(sig[:idx]))
}

// extractTypes returns the request and first response type names from an Op.
// Returns ("", "interface{}") when there are no inputs or outputs respectively.
func extractTypes(op Op) (reqType, respType string) {
	if len(op.Inputs) > 0 && op.Inputs[0].Type != "" {
		reqType = op.Inputs[0].Type
	}
	for _, out := range op.Outputs {
		if out.Name != "(error)" && out.Type != "" && out.Type != "error" {
			respType = out.Type
			return
		}
	}
	respType = "interface{}"
	return
}

// CheckDriftOpts parameterises CheckDrift.
type CheckDriftOpts struct {
	// ContractDir is the directory containing *.json contract files.
	ContractDir string
	// OutputDir is the directory where generated *_contract_gen.go files live.
	OutputDir string
	// Package is the Go package name in the generated files (unused currently; reserved).
	Package string
}

// CheckDrift regenerates each contract in opts.ContractDir in memory and diffs
// against the committed file in opts.OutputDir. Any difference fails t.
func CheckDrift(t *testing.T, opts CheckDriftOpts) {
	t.Helper()
	entries, err := os.ReadDir(opts.ContractDir)
	if err != nil {
		t.Fatalf("contractgen.CheckDrift: read contract dir %s: %v", opts.ContractDir, err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(opts.ContractDir, e.Name()))
		if err != nil {
			t.Fatalf("contractgen.CheckDrift: read %s: %v", e.Name(), err)
		}
		c, err := ParseContract(raw)
		if err != nil {
			t.Errorf("contractgen.CheckDrift: parse %s: %v", e.Name(), err)
			continue
		}
		want, err := Generate(c)
		if err != nil {
			t.Errorf("contractgen.CheckDrift: generate %s: %v", e.Name(), err)
			continue
		}
		genFile := filepath.Join(opts.OutputDir, strings.TrimSuffix(e.Name(), ".json")+"_contract_gen.go")
		got, err := os.ReadFile(genFile)
		if os.IsNotExist(err) {
			t.Errorf("contractgen.CheckDrift: generated file %s does not exist; run contractgen to regenerate", genFile)
			continue
		}
		if err != nil {
			t.Fatalf("contractgen.CheckDrift: read %s: %v", genFile, err)
		}
		if !bytes.Equal(got, want) {
			t.Errorf("contractgen.CheckDrift: %s is out of date; regenerate with `go run ./cmd/contractgen`", genFile)
		}
	}
}
