// Code generated by framework-go-http-generator. DO NOT EDIT.
// Source contract: archistrator://contract/operations

package operations

import (
	"encoding/json"
	"errors"
	"net/http"

	"github.com/google/uuid"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go-http-generator/internal/stub/manager"
	mgr "github.com/mixofreality-studio/archistrator-platform/framework-go-http-generator/internal/stub/operationsmgr"
	"github.com/mixofreality-studio/archistrator-platform/framework-go-http-generator/internal/stub/security"
)

// Handler binds the OperationsManager manager to HTTP per the archistrator client convention.
type Handler struct {
	Manager  mgr.OperationsManager
	Security security.Security
}

// Register mounts every operation route on mux.
func (h *Handler) Register(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/v1/operations/apply-delinquency-policy/{customerID}", h.handleApplyDelinquencyPolicy)
	mux.HandleFunc("POST /api/v1/operations/deploy-after-construction/{operatedAppID}", h.handleDeployAfterConstruction)
	mux.HandleFunc("POST /api/v1/operations/query-cost-projection/{operatedAppID}", h.handleQueryCostProjection)
	mux.HandleFunc("GET /api/v1/operations/query-operated-system-view/{operatedAppID}", h.handleQueryOperatedSystemView)
	mux.HandleFunc("POST /api/v1/operations/reconcile-operated-state", h.handleReconcileOperatedState)
	mux.HandleFunc("POST /api/v1/operations/withdraw-system/{operatedAppID}", h.handleWithdrawSystem)
}

type applyDelinquencyPolicyRequest struct {
	DelinquencyContext mgr.DelinquencyContext `json:"delinquencyContext"`
}

type deployAfterConstructionRequest struct {
	Change mgr.DesiredStateChange `json:"change"`
}

type queryCostProjectionRequest struct {
	RequestID string                 `json:"requestID"`
	Points    *mgr.ScaleWhatIfPoints `json:"points"`
}

type reconcileOperatedStateRequest struct {
	TickID string              `json:"tickID"`
	Scope  *mgr.ReconcileScope `json:"scope"`
}

type withdrawSystemRequest struct {
	ChangeID string             `json:"changeID"`
	Reason   mgr.WithdrawReason `json:"reason"`
}

// handleApplyDelinquencyPolicy binds POST /api/v1/operations/apply-delinquency-policy/{customerID} -> mgr.ApplyDelinquencyPolicy.
func (h *Handler) handleApplyDelinquencyPolicy(w http.ResponseWriter, r *http.Request) {
	customerID, err := uuid.Parse(r.PathValue("customerID"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid customerID: "+err.Error())
		return
	}
	var req applyDelinquencyPolicyRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "apply-delinquency-policy"},
		security.ResourceRef{Kind: "customer", ID: customerID.String()})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	if err := h.Manager.ApplyDelinquencyPolicy(rc, customerID, req.DelinquencyContext); err != nil {
		writeManagerError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// handleDeployAfterConstruction binds POST /api/v1/operations/deploy-after-construction/{operatedAppID} -> mgr.DeployAfterConstruction.
func (h *Handler) handleDeployAfterConstruction(w http.ResponseWriter, r *http.Request) {
	operatedAppID, err := uuid.Parse(r.PathValue("operatedAppID"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid operatedAppID: "+err.Error())
		return
	}
	var req deployAfterConstructionRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "deploy-after-construction"},
		security.ResourceRef{Kind: "operatedapp", ID: operatedAppID.String()})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.DeployAfterConstruction(rc, operatedAppID, req.Change)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleQueryCostProjection binds POST /api/v1/operations/query-cost-projection/{operatedAppID} -> mgr.QueryCostProjection.
func (h *Handler) handleQueryCostProjection(w http.ResponseWriter, r *http.Request) {
	operatedAppID, err := uuid.Parse(r.PathValue("operatedAppID"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid operatedAppID: "+err.Error())
		return
	}
	var req queryCostProjectionRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "query-cost-projection"},
		security.ResourceRef{Kind: "operatedapp", ID: operatedAppID.String()})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.QueryCostProjection(rc, operatedAppID, req.RequestID, req.Points)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleQueryOperatedSystemView binds GET /api/v1/operations/query-operated-system-view/{operatedAppID} -> mgr.QueryOperatedSystemView.
func (h *Handler) handleQueryOperatedSystemView(w http.ResponseWriter, r *http.Request) {
	operatedAppID, err := uuid.Parse(r.PathValue("operatedAppID"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid operatedAppID: "+err.Error())
		return
	}
	requestID := r.URL.Query().Get("requestID")
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "query-operated-system-view"},
		security.ResourceRef{Kind: "operatedapp", ID: operatedAppID.String()})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.QueryOperatedSystemView(rc, operatedAppID, requestID)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleReconcileOperatedState binds POST /api/v1/operations/reconcile-operated-state -> mgr.ReconcileOperatedState.
func (h *Handler) handleReconcileOperatedState(w http.ResponseWriter, r *http.Request) {
	var req reconcileOperatedStateRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "reconcile-operated-state"},
		security.ResourceRef{Kind: "operationsCatalog", ID: principal.Subject})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.ReconcileOperatedState(rc, req.TickID, req.Scope)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// handleWithdrawSystem binds POST /api/v1/operations/withdraw-system/{operatedAppID} -> mgr.WithdrawSystem.
func (h *Handler) handleWithdrawSystem(w http.ResponseWriter, r *http.Request) {
	operatedAppID, err := uuid.Parse(r.PathValue("operatedAppID"))
	if err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid operatedAppID: "+err.Error())
		return
	}
	var req withdrawSystemRequest
	if !decodeJSON(w, r, &req) {
		return
	}
	principal, ok := security.PrincipalFrom(r.Context())
	if !ok {
		writeError(w, http.StatusUnauthorized, "unauthenticated", "authentication required")
		return
	}
	decision, err := h.Security.Authorize(r.Context(), principal,
		security.Action{Verb: "withdraw-system"},
		security.ResourceRef{Kind: "operatedapp", ID: operatedAppID.String()})
	if err != nil || !decision.Permit {
		writeError(w, http.StatusForbidden, "forbidden", "not permitted")
		return
	}
	rc := fwmanager.Context{Context: r.Context(), Principal: principal}
	result, err := h.Manager.WithdrawSystem(rc, operatedAppID, req.ChangeID, req.Reason)
	if err != nil {
		writeManagerError(w, err)
		return
	}
	writeJSON(w, http.StatusOK, result)
}

// --- response helpers ------------------------------------------------------

type errorResponse struct {
	Error string `json:"error"`
	Code  string `json:"code"`
}

func decodeJSON(w http.ResponseWriter, r *http.Request, dst any) bool {
	dec := json.NewDecoder(r.Body)
	dec.DisallowUnknownFields()
	if err := dec.Decode(dst); err != nil {
		writeError(w, http.StatusBadRequest, "bad_request", "invalid JSON body: "+err.Error())
		return false
	}
	return true
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeError(w http.ResponseWriter, status int, code, detail string) {
	writeJSON(w, status, errorResponse{Error: detail, Code: code})
}

// writeManagerError maps a framework-go manager.Error to its HTTP status; any
// other error is a non-leaking 500.
func writeManagerError(w http.ResponseWriter, err error) {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		writeError(w, statusForKind(me.Kind), codeForKind(me.Kind), me.Detail)
		return
	}
	writeError(w, http.StatusInternalServerError, "internal", "internal error")
}

func statusForKind(kind fwmanager.Kind) int {
	switch kind {
	case fwmanager.ContractMisuse:
		return http.StatusBadRequest
	case fwmanager.NotFound:
		return http.StatusNotFound
	case fwmanager.Unauthorized:
		return http.StatusForbidden
	case fwmanager.FailedPrecondition:
		return http.StatusConflict
	case fwmanager.Infrastructure:
		return http.StatusServiceUnavailable
	default:
		return http.StatusInternalServerError
	}
}

func codeForKind(kind fwmanager.Kind) string {
	switch kind {
	case fwmanager.ContractMisuse:
		return "contract_misuse"
	case fwmanager.NotFound:
		return "not_found"
	case fwmanager.Unauthorized:
		return "forbidden"
	case fwmanager.FailedPrecondition:
		return "failed_precondition"
	case fwmanager.Infrastructure:
		return "infrastructure"
	default:
		return "internal"
	}
}
