package mcpgen_test

import (
	"flag"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mixofreality-studio/archistrator-platform/framework-go-mcp-generator/contract"
	"github.com/mixofreality-studio/archistrator-platform/framework-go-mcp-generator/mcpgen"
)

var update = flag.Bool("update", false, "rewrite golden files")

type fixture struct {
	name          string
	contractFile  string
	managerImport string
	golden        string
}

var fixtures = []fixture{
	{
		name:          "project",
		contractFile:  "../testdata/project.contract.schema.json",
		managerImport: "github.com/mixofreality-studio/archistrator/server/internal/manager/project",
		golden:        "../testdata/project.tools.go.golden",
	},
	{
		name:          "construction",
		contractFile:  "../testdata/construction.contract.schema.json",
		managerImport: "github.com/mixofreality-studio/archistrator/server/internal/manager/construction",
		golden:        "../testdata/construction.tools.go.golden",
	},
	{
		name:          "systemdesign",
		contractFile:  "../testdata/systemdesign.contract.schema.json",
		managerImport: "github.com/mixofreality-studio/archistrator/server/internal/manager/systemdesign",
		golden:        "../testdata/systemdesign.tools.go.golden",
	},
	{
		name:          "projectdesign",
		contractFile:  "../testdata/projectdesign.contract.schema.json",
		managerImport: "github.com/mixofreality-studio/archistrator/server/internal/manager/projectdesign",
		golden:        "../testdata/projectdesign.tools.go.golden",
	},
	{
		name:          "operations",
		contractFile:  "../testdata/operations.contract.schema.json",
		managerImport: "github.com/mixofreality-studio/archistrator/server/internal/manager/operations",
		golden:        "../testdata/operations.tools.go.golden",
	},
}

// sampleFixtures drive the in-module compile proof: each emitted tool set is
// generated against a stub manager package whose signatures match the real ones
// (uuid.UUID identities, int-enum params, struct params) and committed to
// internal/sample, where `go build ./...` compiles it against the stubs + the
// REAL mcp SDK.
var sampleFixtures = []struct {
	name    string
	short   string
	pkg     string
	stubPkg string
	sample  string
}{
	{"project", "project", "sample", "projectmgr", "../internal/sample/project_tools.gen.go"},
	{"systemdesign", "systemdesign", "systemdesign", "systemdesignmgr", "../internal/sample/systemdesign/tools.gen.go"},
	{"projectdesign", "projectdesign", "projectdesign", "projectdesignmgr", "../internal/sample/projectdesign/tools.gen.go"},
	{"operations", "operations", "operations", "operationsmgr", "../internal/sample/operations/tools.gen.go"},
}

func TestGenerateGolden(t *testing.T) {
	for _, fx := range fixtures {
		t.Run(fx.name, func(t *testing.T) {
			raw, err := os.ReadFile(fx.contractFile)
			if err != nil {
				t.Fatal(err)
			}
			doc, err := contract.Parse(raw)
			if err != nil {
				t.Fatalf("parse contract: %v", err)
			}
			res, err := mcpgen.Generate(doc, mcpgen.Options{ManagerImport: fx.managerImport})
			if err != nil {
				t.Fatalf("generate: %v", err)
			}

			// Emitted Go must parse.
			if _, err := parser.ParseFile(token.NewFileSet(), "tools.go", res.ToolsGo, parser.AllErrors); err != nil {
				t.Fatalf("emitted tools do not parse: %v", err)
			}
			// One AddTool registration per operation, with the conventional name.
			src := string(res.ToolsGo)
			if got := strings.Count(src, "mcp.AddTool(srv,"); got != len(doc.Interface.Operations) {
				t.Errorf("AddTool count = %d, want %d", got, len(doc.Interface.Operations))
			}
			prefix := contract.LowerFirst(doc.ManagerBase())
			for _, op := range doc.Interface.Operations {
				name := prefix + op.Name
				if !strings.Contains(src, `Name: "`+name+`"`) {
					t.Errorf("tool name %q missing", name)
				}
			}

			checkGolden(t, fx.golden, res.ToolsGo)
		})
	}
}

// TestSampleInSync verifies the committed compile-proof sample (internal/sample,
// generated against the in-module stubs and compiled against the REAL mcp SDK by
// `go build ./...`) is regenerated byte-identically.
func TestSampleInSync(t *testing.T) {
	const base = "github.com/mixofreality-studio/archistrator-platform/framework-go-mcp-generator/internal/stub"
	for _, fx := range sampleFixtures {
		t.Run(fx.name, func(t *testing.T) {
			raw, err := os.ReadFile("../testdata/" + fx.short + ".contract.schema.json")
			if err != nil {
				t.Fatal(err)
			}
			doc, err := contract.Parse(raw)
			if err != nil {
				t.Fatal(err)
			}
			res, err := mcpgen.Generate(doc, mcpgen.Options{
				Package:                fx.pkg,
				ManagerImport:          base + "/" + fx.stubPkg,
				FrameworkManagerImport: base + "/manager",
				SecurityImport:         base + "/security",
			})
			if err != nil {
				t.Fatal(err)
			}
			checkGolden(t, fx.sample, res.ToolsGo)
		})
	}
}

func checkGolden(t *testing.T, path string, got []byte) {
	t.Helper()
	if *update {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, got, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden %s: %v (run with -update)", path, err)
	}
	if string(got) != string(want) {
		t.Errorf("output mismatch for %s (run with -update to refresh)", path)
	}
}
