// Package mcpgen turns a parsed schema-first manager contract into an MCP tool
// surface: Go source that registers one mcp.Tool per manager operation using the
// official SDK github.com/modelcontextprotocol/go-sdk/mcp.
//
// It emits TEXT — the manager/import wiring is parameterized through Options so
// generation never needs the target server to compile.
//
// Each generated tool handler builds the framework manager Context from the call
// context's principal, calls exactly one manager op, and maps the framework
// manager.Error. Input/output JSON Schemas are INFERRED by the SDK from the
// generated typed input/output structs (the generic mcp.AddTool path), so the
// emitted code carries no hand-written JSON Schema.
package mcpgen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/mixofreality-studio/archistrator-platform/framework-go-mcp-generator/contract"
)

const (
	defaultFrameworkManagerImport = "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	defaultSecurityImport         = "github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	defaultMCPImport              = "github.com/modelcontextprotocol/go-sdk/mcp"
	defaultManagerAlias           = "mgr"
	defaultPackage                = "mcptools"
)

// Options configures a generation run.
type Options struct {
	Package                string // emitted package name (default "mcptools")
	ManagerImport          string // import path of the manager package
	ManagerAlias           string // import alias (default "mgr")
	ManagerIface           string // override interface name (default: contract)
	FrameworkManagerImport string // framework-go manager import path
	SecurityImport         string // framework-go security import path
	MCPImport              string // mcp sdk import path (default official)
}

func (o Options) withDefaults(doc *contract.Doc) Options {
	if o.Package == "" {
		o.Package = defaultPackage
	}
	if o.ManagerAlias == "" {
		o.ManagerAlias = defaultManagerAlias
	}
	if o.ManagerIface == "" {
		o.ManagerIface = doc.Interface.Name
	}
	if o.FrameworkManagerImport == "" {
		o.FrameworkManagerImport = defaultFrameworkManagerImport
	}
	if o.SecurityImport == "" {
		o.SecurityImport = defaultSecurityImport
	}
	if o.MCPImport == "" {
		o.MCPImport = defaultMCPImport
	}
	return o
}

// Result holds the generator output.
type Result struct {
	// ToolsGo is the gofmt'd Go source registering the MCP tools.
	ToolsGo []byte
}

// Generate produces the MCP tool registration source for a contract.
func Generate(doc *contract.Doc, opts Options) (Result, error) {
	opts = opts.withDefaults(doc)
	src, err := genTools(doc, opts)
	if err != nil {
		return Result{}, err
	}
	return Result{ToolsGo: src}, nil
}

func genTools(doc *contract.Doc, opts Options) ([]byte, error) {
	var b strings.Builder
	alias := opts.ManagerAlias
	mgrPrefix := contract.LowerFirst(doc.ManagerBase())

	extra := toolExtraImports(doc)

	fmt.Fprintf(&b, "// Code generated by framework-go-mcp-generator. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source contract: %s\n\n", doc.ID)
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)
	writeToolImports(&b, opts, extra)

	fmt.Fprintf(&b, "// Handler binds the %s manager to MCP tools.\n", opts.ManagerIface)
	b.WriteString("type Handler struct {\n")
	fmt.Fprintf(&b, "\tManager %s.%s\n", alias, opts.ManagerIface)
	b.WriteString("}\n\n")

	// Register.
	b.WriteString("// Register adds every operation as an mcp.Tool on srv. The SDK infers each\n")
	b.WriteString("// tool's input/output JSON Schema from the typed handler signatures.\n")
	b.WriteString("func (h *Handler) Register(srv *mcp.Server) {\n")
	for _, op := range doc.Interface.Operations {
		toolName := mgrPrefix + op.Name
		desc := fmt.Sprintf("%s on the %s manager.", op.Name, doc.ManagerBase())
		fmt.Fprintf(&b, "\tmcp.AddTool(srv, &mcp.Tool{Name: %q, Description: %q}, h.handle%s)\n",
			toolName, desc, op.Name)
	}
	b.WriteString("}\n\n")

	// Input/Output types.
	writeIOTypes(&b, doc, alias)

	// Handlers.
	for _, op := range doc.Interface.Operations {
		writeToolHandler(&b, op)
	}

	writeHelpers(&b)

	src := []byte(b.String())
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("mcpgen: emitted source does not parse: %w\n---\n%s", err, src)
	}
	return formatted, nil
}

// writeToolImports emits the import block for the generated tools file: the fixed
// stdlib imports, the MCP SDK, the collected x-go-import paths, and the
// framework/manager imports.
func writeToolImports(b *strings.Builder, opts Options, extra []string) {
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"errors\"\n")
	b.WriteString("\t\"fmt\"\n\n")
	fmt.Fprintf(b, "\t%q\n\n", opts.MCPImport)
	for _, imp := range extra {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	if len(extra) > 0 {
		b.WriteString("\n")
	}
	fmt.Fprintf(b, "\tfwmanager %q\n", opts.FrameworkManagerImport)
	fmt.Fprintf(b, "\t%q\n", opts.SecurityImport)
	fmt.Fprintf(b, "\t%s %q\n", opts.ManagerAlias, opts.ManagerImport)
	b.WriteString(")\n\n")
}

// writeIOTypes emits the typed Input/Output struct for every operation. The SDK
// infers each tool's JSON Schema from these structs.
func writeIOTypes(b *strings.Builder, doc *contract.Doc, alias string) {
	for _, op := range doc.Interface.Operations {
		lower := contract.LowerFirst(op.Name)
		fmt.Fprintf(b, "type %sInput struct {\n", lower)
		for _, p := range op.Params {
			fmt.Fprintf(b, "\t%s %s `json:%q`\n",
				upperFirst(p.Name), contract.GoType(p.Schema, p.Pointer, alias), p.Name)
		}
		b.WriteString("}\n\n")

		if op.Result != nil {
			fmt.Fprintf(b, "type %sOutput struct {\n", lower)
			fmt.Fprintf(b, "\tResult %s `json:\"result\"`\n", contract.GoType(op.Result, false, alias))
			b.WriteString("}\n\n")
		} else {
			fmt.Fprintf(b, "type %sOutput struct{}\n\n", lower)
		}
	}
}

func writeToolHandler(b *strings.Builder, op contract.Operation) {
	lower := contract.LowerFirst(op.Name)
	fmt.Fprintf(b, "// handle%s is the MCP tool handler for the %s operation.\n", op.Name, op.Name)
	fmt.Fprintf(b, "func (h *Handler) handle%s(ctx context.Context, _ *mcp.CallToolRequest, in %sInput) (*mcp.CallToolResult, %sOutput, error) {\n",
		op.Name, lower, lower)
	fmt.Fprintf(b, "\tvar out %sOutput\n", lower)
	b.WriteString("\tprincipal, _ := security.PrincipalFrom(ctx)\n")
	b.WriteString("\trc := fwmanager.Context{Context: ctx, Principal: principal}\n")

	args := []string{"rc"}
	for _, p := range op.Params {
		args = append(args, "in."+upperFirst(p.Name))
	}
	call := fmt.Sprintf("h.Manager.%s(%s)", op.Name, strings.Join(args, ", "))
	if op.Result != nil {
		fmt.Fprintf(b, "\tresult, err := %s\n", call)
		b.WriteString("\tif err != nil {\n\t\treturn nil, out, mapManagerError(err)\n\t}\n")
		b.WriteString("\tout.Result = result\n")
		b.WriteString("\treturn nil, out, nil\n")
	} else {
		fmt.Fprintf(b, "\tif err := %s; err != nil {\n\t\treturn nil, out, mapManagerError(err)\n\t}\n", call)
		b.WriteString("\treturn nil, out, nil\n")
	}
	b.WriteString("}\n\n")
}

// toolExtraImports collects the sorted, de-duplicated x-go-import paths the
// generated input/output structs reference (uuid/time/[]byte/json.RawMessage
// bound via x-go-type on a param or result), so the tool types compile against
// the real manager signatures.
func toolExtraImports(doc *contract.Doc) []string {
	set := map[string]bool{}
	add := func(n *contract.SchemaNode) {
		for _, imp := range contract.GoImports(n) {
			set[imp] = true
		}
		if kind, ok := doc.ScalarKind(n); ok && kind == "uuid" {
			set["github.com/google/uuid"] = true
		}
	}
	for _, op := range doc.Interface.Operations {
		for _, p := range op.Params {
			add(p.Schema)
		}
		add(op.Result)
	}
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] -= 'a' - 'A'
	}
	return string(r)
}
