// Package transportgen emits a SELF-CONTAINED, zero-non-stdlib-import Go client
// SDK (HTTP + MCP) for a set of Manager contracts — the generated replacement
// for archistrator systemtests' hand-rolled transports and a delivered-app
// artifact.
//
// The SDK is ONE flat package: a shared core (HTTPClient/MCPClient plumbing,
// error types, the streamable-HTTP JSON-RPC/SSE loop), per-manager DTO type
// files (emitted through modelgen.EmitTypes so they are byte-identical to the
// server's own model types), and per-manager HTTP + MCP method files driven by
// framework-go-http-generator's exported route planner (httpgen.PlanOps) — the
// SINGLE source of route/verb/path-param truth, so the client can never diverge
// from what the server binds.
//
// Cross-manager DTO name collisions (many managers declare an ArtifactKind, a
// ProjectID, a ReviewFeedback, ...) are resolved deliberately: a $def whose
// emitted Go is byte-identical across every declaring manager is emitted ONCE in
// a shared file; a $def whose emitted Go differs (SessionStage's enum arity,
// Money's field casing, AnchoredComment's field set, and anything transitively
// referencing them) is emitted per-manager with a ManagerBase name prefix
// (SystemDesignSessionStage / ProjectDesignSessionStage). See analyzeDefs.
package transportgen

import (
	"fmt"
	"sort"

	httpgen "github.com/mixofreality-studio/archistrator-platform/framework-go-http-generator/httpgen"
	projectmodel "github.com/mixofreality-studio/archistrator-platform/framework-go-projectmodel"
)

// genHeader is the marker every emitted file starts with (first line, so tools
// and golangci-lint's generated-file exclusion recognize the file).
const genHeader = "// Code generated by transportgen. DO NOT EDIT.\n\n"

// Config parameterizes Generate.
type Config struct {
	// Managers is the ordered set of serviceContracts keys (each a Manager-layer
	// contract) to emit an SDK surface for.
	Managers []string
	// PackageName is the emitted package name (e.g. "sdk").
	PackageName string
	// UUIDAsString emits every uuid-bound scalar as plain string and never
	// imports github.com/google/uuid — the zero-dependency client mode.
	UUIDAsString bool
}

// mgrInfo is the resolved per-manager context Generate threads through the
// emitters.
type mgrInfo struct {
	key      string
	doc      *projectmodel.Doc
	base     string                    // ManagerBase, e.g. "SystemDesign"
	kebab    string                    // Kebab(base), e.g. "system-design"
	toolPref string                    // LowerFirst(base), the MCP tool-name prefix
	rename   map[string]string         // conflict $def name -> ManagerBase-prefixed name (this manager only)
	plans    map[string]httpgen.OpPlan // op name -> resolved HTTP binding
}

// Generate emits the SDK files for cfg.Managers, keyed by file name:
// core.gen.go, types_shared.gen.go (only when there are shared DTOs), and
// types_<mgr>.gen.go / http_<mgr>.gen.go / mcp_<mgr>.gen.go per manager.
func Generate(m *projectmodel.Model, cfg Config) (map[string][]byte, error) {
	if cfg.PackageName == "" {
		return nil, fmt.Errorf("transportgen: Config.PackageName is empty")
	}
	if len(cfg.Managers) == 0 {
		return nil, fmt.Errorf("transportgen: Config.Managers is empty")
	}

	infos, err := resolveManagers(m, cfg)
	if err != nil {
		return nil, err
	}
	an, err := analyzeDefs(infos, cfg)
	if err != nil {
		return nil, err
	}
	assignRenames(infos, an)

	out := map[string][]byte{}
	if err := emitSharedFile(out, an, cfg); err != nil {
		return nil, err
	}
	if err := emitManagerFiles(out, infos, an, cfg); err != nil {
		return nil, err
	}
	if err := emitExternalFile(out, infos, cfg); err != nil {
		return nil, err
	}
	core, err := emitCore(cfg)
	if err != nil {
		return nil, fmt.Errorf("transportgen: core: %w", err)
	}
	out["core.gen.go"] = core
	return out, nil
}

// assignRenames builds each manager's conflict-name rename map. The conflict
// partition is global; a manager only ever references conflict names it also
// declares (contracts are self-contained), so its map is the conflict names in
// its own $defs.
func assignRenames(infos []*mgrInfo, an *defAnalysis) {
	for _, info := range infos {
		info.rename = map[string]string{}
		for name := range info.doc.Defs {
			if an.conflict[name] {
				info.rename[name] = info.base + name
			}
		}
	}
}

// emitSharedFile emits types_shared.gen.go when there are byte-identical DTOs to
// deduplicate.
func emitSharedFile(out map[string][]byte, an *defAnalysis, cfg Config) error {
	if len(an.sharedOrder) == 0 {
		return nil
	}
	src, err := emitSharedTypes(an, cfg)
	if err != nil {
		return fmt.Errorf("transportgen: types_shared: %w", err)
	}
	out["types_shared.gen.go"] = src
	return nil
}

// emitManagerFiles emits the types/http/mcp file trio for each manager.
func emitManagerFiles(out map[string][]byte, infos []*mgrInfo, an *defAnalysis, cfg Config) error {
	for _, info := range infos {
		tsrc, err := emitManagerTypes(info, an, cfg)
		if err != nil {
			return fmt.Errorf("transportgen: types_%s: %w", info.kebab, err)
		}
		out["types_"+info.kebab+".gen.go"] = tsrc

		hsrc, err := emitManagerHTTP(info, cfg)
		if err != nil {
			return fmt.Errorf("transportgen: http_%s: %w", info.kebab, err)
		}
		out["http_"+info.kebab+".gen.go"] = hsrc

		msrc, err := emitManagerMCP(info, cfg)
		if err != nil {
			return fmt.Errorf("transportgen: mcp_%s: %w", info.kebab, err)
		}
		out["mcp_"+info.kebab+".gen.go"] = msrc
	}
	return nil
}

// emitExternalFile emits types_external.gen.go when a contract binds in-package
// types it never declares.
func emitExternalFile(out map[string][]byte, infos []*mgrInfo, cfg Config) error {
	dangling := collectDangling(infos)
	if len(dangling) == 0 {
		return nil
	}
	src, err := emitExternalTypes(dangling, cfg)
	if err != nil {
		return fmt.Errorf("transportgen: types_external: %w", err)
	}
	out["types_external.gen.go"] = src
	return nil
}

// resolveManagers validates each configured key is a Manager contract and
// pre-plans its HTTP routes via httpgen.PlanOps.
func resolveManagers(m *projectmodel.Model, cfg Config) ([]*mgrInfo, error) {
	infos := make([]*mgrInfo, 0, len(cfg.Managers))
	for _, key := range cfg.Managers {
		c, ok := m.Contracts[key]
		if !ok {
			return nil, fmt.Errorf("transportgen: manager %s: unknown contract", key)
		}
		if c.Layer != "Manager" {
			return nil, fmt.Errorf("transportgen: contract %q is layer %q, want Manager", key, c.Layer)
		}
		plans, err := httpgen.PlanOps(c.Doc)
		if err != nil {
			return nil, fmt.Errorf("transportgen: plan %s: %w", key, err)
		}
		byName := make(map[string]httpgen.OpPlan, len(plans))
		for _, p := range plans {
			byName[p.Name] = p
		}
		base := c.Doc.ManagerBase()
		infos = append(infos, &mgrInfo{
			key:      key,
			doc:      c.Doc,
			base:     base,
			kebab:    projectmodel.Kebab(base),
			toolPref: projectmodel.LowerFirst(base),
			plans:    byName,
		})
	}
	return infos, nil
}

// Route is one entry of the emitted client's HTTP surface: the verb+path a
// generated method binds for an operation. Path is the mounted template with
// its query params appended as {name} placeholders, so a fidelity test can
// byte-pin the whole route (e.g.
// "GET /api/v1/system-design/get-session-state/{projectID}?kind={kind}").
type Route struct {
	Manager string
	Op      string
	Verb    string
	Path    string
}

// RouteTable returns the HTTP routes the SDK binds for managers, derived from
// the SAME httpgen.PlanOps the emitter uses — the verifiable mirror proof.
func RouteTable(m *projectmodel.Model, managers []string) ([]Route, error) {
	infos, err := resolveManagers(m, Config{Managers: managers, PackageName: "sdk"})
	if err != nil {
		return nil, err
	}
	var out []Route
	for _, info := range infos {
		ops := make([]string, 0, len(info.plans))
		for name := range info.plans {
			ops = append(ops, name)
		}
		sort.Strings(ops)
		for _, name := range ops {
			p := info.plans[name]
			out = append(out, Route{
				Manager: info.key,
				Op:      name,
				Verb:    p.Verb,
				Path:    routePath(p),
			})
		}
	}
	return out, nil
}

// routePath renders an OpPlan's mounted template plus any query params as {name}
// placeholders in declared order.
func routePath(p httpgen.OpPlan) string {
	path := p.PathTemplate
	for i, q := range p.QueryParams {
		sep := "&"
		if i == 0 {
			sep = "?"
		}
		path += sep + q.Name + "={" + q.Name + "}"
	}
	return path
}
