// Package temporalgen generates the Temporal activities/invokers/worker
// wiring for a Manager component's dependencies: one Temporal Activity per
// ResourceAccess dep operation, the Manager-side invoker functions that call
// them via workflow.ExecuteActivity, and the worker main that registers them
// on the interface's task queue.
//
// This is the Task 4 scaffold: naming rules + a skeleton Generate that emits
// three parseable, near-empty files. Tasks 5-7 grow each emitter's body.
package temporalgen

import (
	"fmt"
	"go/format"
	"path"
	"strings"

	"github.com/mixofreality-studio/archistrator-platform/framework-go-projectmodel"
)

// Config parameterizes Generate.
type Config struct {
	// ModulePath is the target server module's import path root, e.g.
	// "github.com/mixofreality-studio/archistrator/server".
	ModulePath string
	// ManagerKey is the serviceContracts key of the Manager contract to
	// generate Temporal wiring for (e.g. "orderManager").
	ManagerKey string
	// CallerKeyedOps is keyed by dep name and lists the op names on that dep
	// that take an explicit caller-supplied idempotency key param.
	CallerKeyedOps map[string][]string
}

// genHeader is the generated-code marker every emitted file starts with.
// It must be the first line so tools (and golangci-lint's generated-file
// exclusion) recognize the file as generated.
const genHeader = "// Code generated by temporalgen. DO NOT EDIT.\n"

// Generate emits the Temporal activities/invokers/worker wiring for the
// Manager contract cfg.ManagerKey resolves to in m. It returns exactly three
// files keyed by name: "activities.gen.go", "invokers.gen.go",
// "worker.gen.go".
//
// Step 1 (this task) emits skeleton files — header + package clause only.
// Tasks 5-7 grow each file's body: activities.gen.go gets one Temporal
// Activity per ResourceAccess dep operation, invokers.gen.go gets the
// Manager-side ExecuteActivity wrappers, worker.gen.go gets the worker main
// that registers them on TaskQueueName(mgr.Doc.Interface.Name).
func Generate(m *projectmodel.Model, cfg Config) (map[string][]byte, error) {
	mgr, ok := m.Contracts[cfg.ManagerKey]
	if !ok {
		return nil, fmt.Errorf("temporalgen: manager %s: unknown contract", cfg.ManagerKey)
	}
	if mgr.Layer != "Manager" {
		return nil, fmt.Errorf("temporalgen: contract %q is layer %q, want Manager", cfg.ManagerKey, mgr.Layer)
	}
	if mgr.GoPackage == "" {
		return nil, fmt.Errorf("temporalgen: manager %s: empty goPackage", cfg.ManagerKey)
	}

	pkgName := path.Base(mgr.GoPackage)

	names := []string{"activities.gen.go", "invokers.gen.go", "worker.gen.go"}
	out := make(map[string][]byte, len(names))
	for _, name := range names {
		src := genHeader + "\npackage " + pkgName + "\n"
		formatted, err := format.Source([]byte(src))
		if err != nil {
			return nil, fmt.Errorf("temporalgen: format %s: %w", name, err)
		}
		out[name] = formatted
	}
	return out, nil
}

// ActivityName is the Temporal activity name registered for one
// ResourceAccess dependency operation: "<depComponentKey>.<lowerFirst(opName)>"
// (e.g. "orderStateAccess.readOrder").
func ActivityName(depComponentKey, opName string) string {
	return depComponentKey + "." + projectmodel.LowerFirst(opName)
}

// TaskQueueName is the Temporal task queue name for a Manager interface: the
// interface name with its trailing "Manager" stripped, kebab-cased (e.g.
// "OrderManager" -> "order", "SystemDesignManager" -> "system-design").
func TaskQueueName(interfaceName string) string {
	return projectmodel.Kebab(strings.TrimSuffix(interfaceName, "Manager"))
}
