// Package temporalgen generates the Temporal activities/invokers/worker
// wiring for a Manager component's dependencies: one Temporal Activity per
// ResourceAccess dep operation, the Manager-side invoker functions that call
// them via workflow.ExecuteActivity, and the worker main that registers them
// on the interface's task queue.
//
// Task 4 laid the scaffold (naming rules + a skeleton Generate). Task 5 grew
// activities.gen.go; Task 6 grew invokers.gen.go. Task 7 grows worker.gen.go.
package temporalgen

import (
	"fmt"
	"go/format"
	"path"
	"strings"

	"github.com/mixofreality-studio/archistrator-platform/framework-go-projectmodel"
)

// Config parameterizes Generate.
type Config struct {
	// ModulePath is the target server module's import path root, e.g.
	// "github.com/mixofreality-studio/archistrator/server".
	ModulePath string
	// ManagerKey is the serviceContracts key of the Manager contract to
	// generate Temporal wiring for (e.g. "orderManager").
	ManagerKey string
	// CallerKeyedOps is keyed by dep name and lists the op names on that dep
	// that take an explicit caller-supplied idempotency key param.
	CallerKeyedOps map[string][]string
}

// genHeader is the generated-code marker every emitted file starts with.
// It must be the first line so tools (and golangci-lint's generated-file
// exclusion) recognize the file as generated.
const genHeader = "// Code generated by temporalgen. DO NOT EDIT.\n"

// emitContext carries common context for per-file emitter functions.
type emitContext struct {
	model   *projectmodel.Model
	cfg     Config
	mgr     *projectmodel.Contract
	pkgName string
}

// emitWorker generates the worker.gen.go file.
func emitWorker(ec emitContext) ([]byte, error) {
	src := genHeader + "\npackage " + ec.pkgName + "\n"
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

// Generate emits the Temporal activities/invokers/worker wiring for the
// Manager contract cfg.ManagerKey resolves to in m. It returns exactly three
// files keyed by name: "activities.gen.go", "invokers.gen.go",
// "worker.gen.go".
//
// activities.gen.go gets one Temporal Activity per ResourceAccess dep
// operation; invokers.gen.go gets the workflow-side typed ExecuteActivity
// callers. worker.gen.go (Task 7) still emits a skeleton — it grows the
// worker main that registers them on TaskQueueName(mgr.Doc.Interface.Name).
func Generate(m *projectmodel.Model, cfg Config) (map[string][]byte, error) {
	mgr, ok := m.Contracts[cfg.ManagerKey]
	if !ok {
		return nil, fmt.Errorf("temporalgen: manager %s: unknown contract", cfg.ManagerKey)
	}
	if mgr.Layer != "Manager" {
		return nil, fmt.Errorf("temporalgen: contract %q is layer %q, want Manager", cfg.ManagerKey, mgr.Layer)
	}
	if mgr.GoPackage == "" {
		return nil, fmt.Errorf("temporalgen: manager %s: empty goPackage", cfg.ManagerKey)
	}

	pkgName := path.Base(mgr.GoPackage)
	ec := emitContext{
		model:   m,
		cfg:     cfg,
		mgr:     mgr,
		pkgName: pkgName,
	}

	out := make(map[string][]byte)

	activities, err := emitActivities(ec)
	if err != nil {
		return nil, fmt.Errorf("temporalgen: format activities.gen.go: %w", err)
	}
	out["activities.gen.go"] = activities

	invokers, err := emitInvokers(ec)
	if err != nil {
		return nil, fmt.Errorf("temporalgen: format invokers.gen.go: %w", err)
	}
	out["invokers.gen.go"] = invokers

	worker, err := emitWorker(ec)
	if err != nil {
		return nil, fmt.Errorf("temporalgen: format worker.gen.go: %w", err)
	}
	out["worker.gen.go"] = worker

	return out, nil
}

// ActivityName is the Temporal activity name registered for one
// ResourceAccess dependency operation: "<depComponentKey>.<lowerFirst(opName)>"
// (e.g. "orderStateAccess.readOrder").
func ActivityName(depComponentKey, opName string) string {
	return depComponentKey + "." + projectmodel.LowerFirst(opName)
}

// TaskQueueName is the Temporal task queue name for a Manager interface: the
// interface name with its trailing "Manager" stripped, kebab-cased (e.g.
// "OrderManager" -> "order", "SystemDesignManager" -> "system-design").
func TaskQueueName(interfaceName string) string {
	return projectmodel.Kebab(strings.TrimSuffix(interfaceName, "Manager"))
}
