// Code generated by cmd/modelgen from the service-contract interface; DO NOT EDIT.
// Edit project.json's `interface` and re-run `make gen-fakes` instead.

package classifierfake

import (
	"github.com/mixofreality-studio/archistrator-platform/framework-go-app-generator/internal/sample/fakeproof/internal/engine/classifier"
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
)

// FakeClassifierEngine is a generated test double for classifier.ClassifierEngine: set the Fn field(s)
// a test needs; calling a method whose Fn is unset panics.
type FakeClassifierEngine struct {
	ClassifyFn func(rc fweng.Context, id classifier.WidgetID) (classifier.Classification, error)
}

func (f *FakeClassifierEngine) Classify(rc fweng.Context, id classifier.WidgetID) (classifier.Classification, error) {
	if f.ClassifyFn == nil {
		panic("FakeClassifierEngine.ClassifyFn not set")
	}
	return f.ClassifyFn(rc, id)
}

var _ classifier.ClassifierEngine = (*FakeClassifierEngine)(nil)
