// Code generated by modelgen. DO NOT EDIT.

package widgetaccessfake

import "example.com/fakeapp/internal/resourceaccess/widgetaccess"

// FakeWidgetAccess is a generated test double for widgetaccess.WidgetAccess. It
// imports its sibling contract package to name FakeWidgetAccess's types — a
// same-ResourceAccess-layer edge that would be a forbidden sideways import were
// this package classified as an ordinary ResourceAccess component.
type FakeWidgetAccess struct {
	GetWidgetFunc func(id string) (string, error)
}

// GetWidget delegates to the configured stub func.
func (f *FakeWidgetAccess) GetWidget(id string) (string, error) {
	return f.GetWidgetFunc(id)
}

var _ widgetaccess.WidgetAccess = (*FakeWidgetAccess)(nil)
