// emit.go
package configgen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/mixofreality-studio/archistrator-platform/framework-go-projectmodel"
)

// genHeader is the generated-code marker (golangci-lint's generated-file
// exclusion + humans recognize it). Must be the first line.
const genHeader = "// Code generated by configgen. DO NOT EDIT.\n"

// emitFile renders and gofmt's config.gen.go.
func emitFile(d *projectmodel.Deployment, cfg Config, infra []infraField, settings []settingField) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(genHeader)
	writeDocHeader(&b, cfg)
	fmt.Fprintf(&b, "package %s\n\n", cfg.PackageName)
	writeImports(&b, settings)
	writeStruct(&b, infra, settings)
	writeLoadConfig(&b, cfg, infra, settings)
	writeMissingFor(&b, d, infra)
	writeDormantWarnings(&b, infra)
	writeHelpers(&b, settings)

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("configgen: gofmt: %w\n%s", err, b.String())
	}
	return src, nil
}

// writeDocHeader documents the contract of the generated file.
func writeDocHeader(b *bytes.Buffer, cfg Config) {
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// Container: %s. Env prefix: %s.\n", nonEmpty(cfg.ContainerKey, "(unscoped)"), cfg.EnvPrefix)
	fmt.Fprintf(b, "// Contract:\n")
	fmt.Fprintf(b, "//   - LoadConfig reads the environment and hard-requires ONLY inputs\n")
	fmt.Fprintf(b, "//     required across ALL declared profiles, collecting every missing one\n")
	fmt.Fprintf(b, "//     into a single error.\n")
	fmt.Fprintf(b, "//   - MissingFor(profile) reports the required env vars absent for a given\n")
	fmt.Fprintf(b, "//     profile; the hand composition root consults it for per-profile and\n")
	fmt.Fprintf(b, "//     conditional (e.g. dry-run-gated) requirements.\n")
	fmt.Fprintf(b, "//   - DormantWarnings reports optional-dormant infrastructure left\n")
	fmt.Fprintf(b, "//     unconfigured.\n")
	fmt.Fprintf(b, "//   - Every infra input is a string; typed/secret coercion (int64 ids, PEM\n")
	fmt.Fprintf(b, "//     resolution) is the hand adapter's job.\n")
}

// writeImports emits the import block; strconv/time are pulled in only when a
// setting needs them.
func writeImports(b *bytes.Buffer, settings []settingField) {
	imps := []string{"fmt", "os", "strings"}
	if anyKind(settings, "bool") || anyKind(settings, "int") {
		imps = append(imps, "strconv")
	}
	if anyKind(settings, "duration") {
		imps = append(imps, "time")
	}
	sort.Strings(imps)
	b.WriteString("import (\n")
	for _, p := range imps {
		fmt.Fprintf(b, "\t%q\n", p)
	}
	b.WriteString(")\n\n")
}

// writeStruct emits the Config struct: infra input fields then setting fields.
func writeStruct(b *bytes.Buffer, infra []infraField, settings []settingField) {
	b.WriteString("// Config is the container's env-loaded configuration.\n")
	b.WriteString("type Config struct {\n")
	if len(infra) > 0 {
		b.WriteString("\t// Infrastructure inputs (all string; typed coercion is the hand adapter's job).\n")
		for _, f := range infra {
			fmt.Fprintf(b, "\t%s string\n", f.GoName)
		}
	}
	if len(settings) > 0 {
		if len(infra) > 0 {
			b.WriteString("\n")
		}
		b.WriteString("\t// Settings (typed, with defaults).\n")
		for _, f := range settings {
			fmt.Fprintf(b, "\t%s %s\n", f.GoName, f.GoType)
		}
	}
	b.WriteString("}\n\n")
}

// writeLoadConfig emits LoadConfig().
func writeLoadConfig(b *bytes.Buffer, cfg Config, infra []infraField, settings []settingField) {
	b.WriteString("// LoadConfig reads the environment into a Config, returning a single error\n")
	b.WriteString("// naming every missing always-required variable.\n")
	b.WriteString("func LoadConfig() (*Config, error) {\n")
	b.WriteString("\tc := &Config{\n")
	for _, f := range infra {
		fmt.Fprintf(b, "\t\t%s: getenv(%q),\n", f.GoName, f.Env)
	}
	for _, f := range settings {
		fmt.Fprintf(b, "\t\t%s: %s(%q, %q),\n", f.GoName, loaderFor(f.Kind), f.Env, f.Default)
	}
	b.WriteString("\t}\n\n")
	b.WriteString("\tvar missing []string\n")
	for _, f := range infra {
		if f.RequiredAll {
			fmt.Fprintf(b, "\tif c.%s == \"\" {\n\t\tmissing = append(missing, %q)\n\t}\n", f.GoName, f.Env)
		}
	}
	b.WriteString("\tif len(missing) > 0 {\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(%q, strings.Join(missing, \", \"))\n",
		cfg.PackageName+": missing required configuration for all declared profiles: %s")
	b.WriteString("\t}\n")
	b.WriteString("\treturn c, nil\n}\n\n")
}

// writeMissingFor emits the per-profile required-var table + MissingFor.
func writeMissingFor(b *bytes.Buffer, d *projectmodel.Deployment, infra []infraField) {
	b.WriteString("// requiredEnvByProfile lists, per profile, the env vars of required-class\n")
	b.WriteString("// infrastructure provisioned for that profile.\n")
	b.WriteString("var requiredEnvByProfile = map[string][]string{\n")
	for _, p := range sortedProfiles(d) {
		fmt.Fprintf(b, "\t%q: {%s},\n", p, quoteJoin(requiredEnvsForProfile(infra, p)))
	}
	b.WriteString("}\n\n")

	b.WriteString("// MissingFor reports the required env vars for profile that are absent.\n")
	b.WriteString("func MissingFor(profile string) []string {\n")
	b.WriteString("\tvar missing []string\n")
	b.WriteString("\tfor _, name := range requiredEnvByProfile[profile] {\n")
	b.WriteString("\t\tif getenv(name) == \"\" {\n")
	b.WriteString("\t\t\tmissing = append(missing, name)\n")
	b.WriteString("\t\t}\n\t}\n\treturn missing\n}\n\n")
}

// writeDormantWarnings emits the DormantWarnings method (one warning per
// optional-dormant infra decl whose inputs are all absent).
func writeDormantWarnings(b *bytes.Buffer, infra []infraField) {
	// Group dormant fields by infra key, preserving first-seen order.
	var keys []string
	byKey := map[string][]infraField{}
	for _, f := range infra {
		if !f.OptDormant {
			continue
		}
		if _, ok := byKey[f.InfraKey]; !ok {
			keys = append(keys, f.InfraKey)
		}
		byKey[f.InfraKey] = append(byKey[f.InfraKey], f)
	}

	b.WriteString("// DormantWarnings reports optional-dormant infrastructure that is entirely\n")
	b.WriteString("// unconfigured (every one of its inputs absent).\n")
	b.WriteString("func (c *Config) DormantWarnings() []string {\n")
	b.WriteString("\tvar w []string\n")
	for _, k := range keys {
		fields := byKey[k]
		conds := make([]string, len(fields))
		envs := make([]string, len(fields))
		for i, f := range fields {
			conds[i] = "c." + f.GoName + " == \"\""
			envs[i] = f.Env
		}
		fmt.Fprintf(b, "\tif %s {\n", strings.Join(conds, " && "))
		fmt.Fprintf(b, "\t\tw = append(w, %q)\n", fmt.Sprintf(
			"infrastructure %q (optional-dormant) is unconfigured; set %s to enable",
			k, strings.Join(envs, ", ")))
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn w\n}\n\n")
}

// writeHelpers emits the env-reading helpers actually used.
func writeHelpers(b *bytes.Buffer, settings []settingField) {
	b.WriteString("// getenv reads and trims an environment variable.\n")
	b.WriteString("func getenv(name string) string { return strings.TrimSpace(os.Getenv(name)) }\n\n")

	if anyKind(settings, "string") {
		b.WriteString("// getenvString returns the trimmed env value, or def when unset.\n")
		b.WriteString("func getenvString(name, def string) string {\n")
		b.WriteString("\tif v := getenv(name); v != \"\" {\n\t\treturn v\n\t}\n\treturn def\n}\n\n")
	}
	if anyKind(settings, "bool") {
		b.WriteString("// getenvBool parses a bool; an unparseable env falls back to def.\n")
		b.WriteString("func getenvBool(name, def string) bool {\n")
		b.WriteString("\tif v := getenv(name); v != \"\" {\n")
		b.WriteString("\t\tif x, err := strconv.ParseBool(v); err == nil {\n\t\t\treturn x\n\t\t}\n\t}\n")
		b.WriteString("\tx, _ := strconv.ParseBool(def)\n\treturn x\n}\n\n")
	}
	if anyKind(settings, "int") {
		b.WriteString("// getenvInt parses an int; an unparseable env falls back to def.\n")
		b.WriteString("func getenvInt(name, def string) int {\n")
		b.WriteString("\tif v := getenv(name); v != \"\" {\n")
		b.WriteString("\t\tif x, err := strconv.Atoi(v); err == nil {\n\t\t\treturn x\n\t\t}\n\t}\n")
		b.WriteString("\tx, _ := strconv.Atoi(def)\n\treturn x\n}\n\n")
	}
	if anyKind(settings, "duration") {
		b.WriteString("// getenvDuration parses a duration; an unparseable env falls back to def.\n")
		b.WriteString("func getenvDuration(name, def string) time.Duration {\n")
		b.WriteString("\tif v := getenv(name); v != \"\" {\n")
		b.WriteString("\t\tif x, err := time.ParseDuration(v); err == nil {\n\t\t\treturn x\n\t\t}\n\t}\n")
		b.WriteString("\tx, _ := time.ParseDuration(def)\n\treturn x\n}\n")
	}
}

// sortedProfiles returns the deployment's distinct env profiles, sorted.
func sortedProfiles(d *projectmodel.Deployment) []string {
	seen := map[string]bool{}
	var out []string
	for _, e := range d.Environments {
		if !seen[e.Profile] {
			seen[e.Profile] = true
			out = append(out, e.Profile)
		}
	}
	sort.Strings(out)
	return out
}

// requiredEnvsForProfile lists the env vars of required-class infra
// provisioned for profile p (in the infra field order). Plain-optional and
// optional-dormant decls are excluded regardless of profile membership — only
// presence=="required" decls belong in the per-profile MissingFor table.
func requiredEnvsForProfile(infra []infraField, p string) []string {
	var vars []string
	for _, f := range infra {
		if f.RequiredClass && f.RequiredForProfile(p) {
			vars = append(vars, f.Env)
		}
	}
	return vars
}

// quoteJoin renders a slice as a comma-separated list of Go string literals.
func quoteJoin(vs []string) string {
	quoted := make([]string, len(vs))
	for i, v := range vs {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, ", ")
}

// loaderFor returns the helper name for a setting kind.
func loaderFor(kind string) string {
	switch kind {
	case "bool":
		return "getenvBool"
	case "int":
		return "getenvInt"
	case "duration":
		return "getenvDuration"
	default:
		return "getenvString"
	}
}

// RequiredForProfile reports whether the field's owning decl is provisioned for
// profile p (its Profiles list contains p).
func (f infraField) RequiredForProfile(p string) bool {
	for _, x := range f.Profiles {
		if x == p {
			return true
		}
	}
	return false
}

// anyKind reports whether any setting has the given kind.
func anyKind(settings []settingField, kind string) bool {
	for _, s := range settings {
		if s.Kind == kind {
			return true
		}
	}
	return false
}

func nonEmpty(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
