// Code generated by cmd/clientgen (mcpemit). DO NOT EDIT.
// Source contract:

package projectdesign

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	mgr "github.com/mixofreality-studio/archistrator/server/internal/manager/projectdesign"
)

// Handler binds the ProjectDesignManager manager to MCP tools.
type Handler struct {
	Manager mgr.ProjectDesignManager
}

// Register adds every operation as an mcp.Tool on srv, each carrying an
// explicit human description and an explicit input JSON Schema (enum values +
// meanings, REST-matching optionality) so an agentic consumer needs no source.
func (h *Handler) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignAdvanceToConstruction", Description: "Advance the project from Project Design (phase 2) to Construction (phase 3), once the SDP has been committed. Returns the resulting phase plus any reason the advance was gated.", InputSchema: advanceToConstructionInputSchema(), OutputSchema: advanceToConstructionOutputSchema()}, h.handleAdvanceToConstruction)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignGetSessionState", Description: "Return the current draft/review session state for one Project-Design artifact (selected by kind): its stage, the latest AI draft, and any review feedback. Read-only.", InputSchema: getSessionStateInputSchema(), OutputSchema: getSessionStateOutputSchema()}, h.handleGetSessionState)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignRequestArtifactDraft", Description: "Kick off (or re-run) the AI drafting of one Project-Design artifact (selected by kind, e.g. the activity list, project network, or a solution option). Pass feedback to re-draft against review notes. Returns a handle to the asynchronous drafting session.", InputSchema: requestArtifactDraftInputSchema(), OutputSchema: requestArtifactDraftOutputSchema()}, h.handleRequestArtifactDraft)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignRequestSDPCommit", Description: "Assemble the SDP Review (every solution option plus the risk model) for management sign-off. Returns a handle to the assembly session.", InputSchema: requestSDPCommitInputSchema(), OutputSchema: requestSDPCommitOutputSchema()}, h.handleRequestSDPCommit)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignAskQuestions", Description: "Ask one or more clarifying QUESTIONS about a Project-Design artifact (selected by kind) addressed to a role (pm or architect), WITHOUT sending the draft back for a redraft. The questions are appended to the artifact's review ledger as question-type entries and a lightweight answer job is dispatched so the addressed role answers each in place. Works on a committed artifact too (seeds a question-only thread without opening an amendment). Unlike change-request comments, open questions do NOT block approve.", InputSchema: askQuestionsInputSchema(), OutputSchema: askQuestionsOutputSchema()}, h.handleAskQuestions)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignAcknowledgeStaleBasis", Description: "Mark a stale committed Project-Design artifact 'reviewed — unaffected': clear its stale-basis flag WITHOUT a redraft, recording the reviewer's note as a durable audit entry in the review thread. Use when an upstream change does not actually affect this artifact (so a reconcile amendment would be a byte-identical no-op).", InputSchema: acknowledgeStaleBasisInputSchema(), OutputSchema: acknowledgeStaleBasisOutputSchema()}, h.handleAcknowledgeStaleBasis)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignSetReviewCommentStatus", Description: "Change the status of one durable review-ledger comment on a Project-Design artifact (selected by kind): waive an open comment to dismiss it, or reopen an addressed comment to send it back. Approve is blocked while any comment is still open.", InputSchema: setReviewCommentStatusInputSchema(), OutputSchema: setReviewCommentStatusOutputSchema()}, h.handleSetReviewCommentStatus)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignSubmitReviewDecision", Description: "Record a review verdict (approve / reject / withdraw) on the current draft of a Project-Design artifact (selected by kind). Reject and withdraw should carry feedback; approve commits the artifact.", InputSchema: submitReviewDecisionInputSchema(), OutputSchema: submitReviewDecisionOutputSchema()}, h.handleSubmitReviewDecision)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignSubmitSDPDecision", Description: "Record management's decision on the SDP Review: commit one solution option (pass its optionID) or reject all options. Pass feedback to record the rationale.", InputSchema: submitSDPDecisionInputSchema(), OutputSchema: submitSDPDecisionOutputSchema()}, h.handleSubmitSDPDecision)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignListEpisodesForArtifact", Description: "List the agentic episode records (draft/critique/rework runs, or gaps) captured against one Project-Design artifact (selected by kind). Read-only.", InputSchema: listEpisodesForArtifactInputSchema(), OutputSchema: listEpisodesForArtifactOutputSchema()}, h.handleListEpisodesForArtifact)
	mcp.AddTool(srv, &mcp.Tool{Name: "projectDesignGetEpisodeTimeline", Description: "Return one agentic episode's full timeline: its record (usage, cost, outcome, lineage) plus the sequenced trace events mined from its run. Read-only.", InputSchema: getEpisodeTimelineInputSchema(), OutputSchema: getEpisodeTimelineOutputSchema()}, h.handleGetEpisodeTimeline)
}

type advanceToConstructionInput struct {
	ProjectID        mgr.ProjectID `json:"projectID"`
	AcknowledgeStale bool          `json:"acknowledgeStale"`
}

type advanceToConstructionOutput struct {
	Result mgr.PhaseAdvanceResult `json:"result"`
}

type getSessionStateInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
}

type getSessionStateOutput struct {
	Result mgr.SessionStateView `json:"result"`
}

type requestArtifactDraftInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Kind      mgr.ArtifactKind    `json:"kind"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type requestArtifactDraftOutput struct {
	Result mgr.SessionRef `json:"result"`
}

type requestSDPCommitInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
}

type requestSDPCommitOutput struct {
	Result mgr.SessionRef `json:"result"`
}

type askQuestionsInput struct {
	ProjectID mgr.ProjectID         `json:"projectID"`
	Kind      mgr.ArtifactKind      `json:"kind"`
	Addressee string                `json:"addressee"`
	Questions []mgr.AnchoredComment `json:"questions"`
}

type askQuestionsOutput struct{}

type acknowledgeStaleBasisInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
	Note      string           `json:"note"`
}

type acknowledgeStaleBasisOutput struct{}

type setReviewCommentStatusInput struct {
	ProjectID mgr.ProjectID    `json:"projectID"`
	Kind      mgr.ArtifactKind `json:"kind"`
	CommentID string           `json:"commentID"`
	Status    string           `json:"status"`
}

type setReviewCommentStatusOutput struct{}

type submitReviewDecisionInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Kind      mgr.ArtifactKind    `json:"kind"`
	Decision  mgr.ReviewDecision  `json:"decision"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type submitReviewDecisionOutput struct{}

type submitSDPDecisionInput struct {
	ProjectID mgr.ProjectID       `json:"projectID"`
	Decision  mgr.SDPDecision     `json:"decision"`
	OptionID  *mgr.OptionID       `json:"optionID,omitempty"`
	Feedback  *mgr.ReviewFeedback `json:"feedback,omitempty"`
}

type submitSDPDecisionOutput struct{}

type listEpisodesForArtifactInput struct {
	ProjectID    mgr.ProjectID    `json:"projectID"`
	ArtifactKind mgr.ArtifactKind `json:"artifactKind"`
}

type listEpisodesForArtifactOutput struct {
	Result []mgr.EpisodeRecordView `json:"result"`
}

type getEpisodeTimelineInput struct {
	ProjectID mgr.ProjectID `json:"projectID"`
	EpisodeID string        `json:"episodeID"`
}

type getEpisodeTimelineOutput struct {
	Result mgr.EpisodeTimeline `json:"result"`
}

// advanceToConstructionInputSchema is the explicit MCP input schema for the AdvanceToConstruction operation.
func advanceToConstructionInputSchema() *jsonschema.Schema {
	s := objectSchema[advanceToConstructionInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "acknowledgeStale"}
	return s
}

// getSessionStateInputSchema is the explicit MCP input schema for the GetSessionState operation.
func getSessionStateInputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// requestArtifactDraftInputSchema is the explicit MCP input schema for the RequestArtifactDraft operation.
func requestArtifactDraftInputSchema() *jsonschema.Schema {
	s := objectSchema[requestArtifactDraftInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// requestSDPCommitInputSchema is the explicit MCP input schema for the RequestSDPCommit operation.
func requestSDPCommitInputSchema() *jsonschema.Schema {
	s := objectSchema[requestSDPCommitInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID"}
	return s
}

// askQuestionsInputSchema is the explicit MCP input schema for the AskQuestions operation.
func askQuestionsInputSchema() *jsonschema.Schema {
	s := objectSchema[askQuestionsInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind", "addressee", "questions"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// acknowledgeStaleBasisInputSchema is the explicit MCP input schema for the AcknowledgeStaleBasis operation.
func acknowledgeStaleBasisInputSchema() *jsonschema.Schema {
	s := objectSchema[acknowledgeStaleBasisInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind", "note"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// setReviewCommentStatusInputSchema is the explicit MCP input schema for the SetReviewCommentStatus operation.
func setReviewCommentStatusInputSchema() *jsonschema.Schema {
	s := objectSchema[setReviewCommentStatusInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind", "commentID", "status"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	return s
}

// submitReviewDecisionInputSchema is the explicit MCP input schema for the SubmitReviewDecision operation.
func submitReviewDecisionInputSchema() *jsonschema.Schema {
	s := objectSchema[submitReviewDecisionInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "kind", "decision"}
	s.Properties["kind"] = enumSchemaArtifactKind()
	s.Properties["decision"] = enumSchemaReviewDecision()
	return s
}

// submitSDPDecisionInputSchema is the explicit MCP input schema for the SubmitSDPDecision operation.
func submitSDPDecisionInputSchema() *jsonschema.Schema {
	s := objectSchema[submitSDPDecisionInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "decision"}
	s.Properties["decision"] = enumSchemaSDPDecision()
	return s
}

// listEpisodesForArtifactInputSchema is the explicit MCP input schema for the ListEpisodesForArtifact operation.
func listEpisodesForArtifactInputSchema() *jsonschema.Schema {
	s := objectSchema[listEpisodesForArtifactInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "artifactKind"}
	s.Properties["artifactKind"] = enumSchemaArtifactKind()
	return s
}

// getEpisodeTimelineInputSchema is the explicit MCP input schema for the GetEpisodeTimeline operation.
func getEpisodeTimelineInputSchema() *jsonschema.Schema {
	s := objectSchema[getEpisodeTimelineInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"projectID", "episodeID"}
	return s
}

// advanceToConstructionOutputSchema is the explicit MCP output schema for the AdvanceToConstruction operation.
func advanceToConstructionOutputSchema() *jsonschema.Schema {
	s := objectSchema[advanceToConstructionOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// getSessionStateOutputSchema is the explicit MCP output schema for the GetSessionState operation.
func getSessionStateOutputSchema() *jsonschema.Schema {
	s := objectSchema[getSessionStateOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// requestArtifactDraftOutputSchema is the explicit MCP output schema for the RequestArtifactDraft operation.
func requestArtifactDraftOutputSchema() *jsonschema.Schema {
	s := objectSchema[requestArtifactDraftOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// requestSDPCommitOutputSchema is the explicit MCP output schema for the RequestSDPCommit operation.
func requestSDPCommitOutputSchema() *jsonschema.Schema {
	s := objectSchema[requestSDPCommitOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// askQuestionsOutputSchema is the explicit MCP output schema for the AskQuestions operation.
func askQuestionsOutputSchema() *jsonschema.Schema {
	s := objectSchema[askQuestionsOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// acknowledgeStaleBasisOutputSchema is the explicit MCP output schema for the AcknowledgeStaleBasis operation.
func acknowledgeStaleBasisOutputSchema() *jsonschema.Schema {
	s := objectSchema[acknowledgeStaleBasisOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// setReviewCommentStatusOutputSchema is the explicit MCP output schema for the SetReviewCommentStatus operation.
func setReviewCommentStatusOutputSchema() *jsonschema.Schema {
	s := objectSchema[setReviewCommentStatusOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// submitReviewDecisionOutputSchema is the explicit MCP output schema for the SubmitReviewDecision operation.
func submitReviewDecisionOutputSchema() *jsonschema.Schema {
	s := objectSchema[submitReviewDecisionOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// submitSDPDecisionOutputSchema is the explicit MCP output schema for the SubmitSDPDecision operation.
func submitSDPDecisionOutputSchema() *jsonschema.Schema {
	s := objectSchema[submitSDPDecisionOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// listEpisodesForArtifactOutputSchema is the explicit MCP output schema for the ListEpisodesForArtifact operation.
func listEpisodesForArtifactOutputSchema() *jsonschema.Schema {
	s := objectSchema[listEpisodesForArtifactOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// getEpisodeTimelineOutputSchema is the explicit MCP output schema for the GetEpisodeTimeline operation.
func getEpisodeTimelineOutputSchema() *jsonschema.Schema {
	s := objectSchema[getEpisodeTimelineOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// enumSchemaArtifactKind describes the ArtifactKind enum: its allowed values and their meanings.
func enumSchemaArtifactKind() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
		Description: "ArtifactKind. Allowed values: 0=KindMission, 1=KindGlossary, 2=KindScrubbedRequirements, 3=KindVolatilities, 4=KindCoreUseCases, 5=KindSystem, 6=KindOperationalConcepts, 7=KindStandardCheck, 8=KindPlanningAssumptions, 9=KindActivityList, 10=KindNetwork, 11=KindNormalSolution, 12=KindSubcriticalSolution, 13=KindCompressedSolution, 14=KindDecompressedSolution, 15=KindRiskModel, 16=KindSdpReview.",
	}
}

// enumSchemaReviewDecision describes the ReviewDecision enum: its allowed values and their meanings.
func enumSchemaReviewDecision() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2, 3},
		Description: "ReviewDecision. Allowed values: 0=ReviewDecisionUnknown, 1=ReviewApprove, 2=ReviewReject, 3=ReviewWithdraw.",
	}
}

// enumSchemaSDPDecision describes the SDPDecision enum: its allowed values and their meanings.
func enumSchemaSDPDecision() *jsonschema.Schema {
	return &jsonschema.Schema{
		Type:        "integer",
		Enum:        []any{0, 1, 2},
		Description: "SDPDecision. Allowed values: 0=SDPDecisionUnknown, 1=SDPCommit, 2=SDPRejectAll.",
	}
}

// handleAdvanceToConstruction is the MCP tool handler for the AdvanceToConstruction operation.
func (h *Handler) handleAdvanceToConstruction(ctx context.Context, _ *mcp.CallToolRequest, in advanceToConstructionInput) (*mcp.CallToolResult, advanceToConstructionOutput, error) {
	var out advanceToConstructionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.AdvanceToConstruction(rc, in.ProjectID, in.AcknowledgeStale)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetSessionState is the MCP tool handler for the GetSessionState operation.
func (h *Handler) handleGetSessionState(ctx context.Context, _ *mcp.CallToolRequest, in getSessionStateInput) (*mcp.CallToolResult, getSessionStateOutput, error) {
	var out getSessionStateOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetSessionState(rc, in.ProjectID, in.Kind)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleRequestArtifactDraft is the MCP tool handler for the RequestArtifactDraft operation.
func (h *Handler) handleRequestArtifactDraft(ctx context.Context, _ *mcp.CallToolRequest, in requestArtifactDraftInput) (*mcp.CallToolResult, requestArtifactDraftOutput, error) {
	var out requestArtifactDraftOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.RequestArtifactDraft(rc, in.ProjectID, in.Kind, in.Feedback)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleRequestSDPCommit is the MCP tool handler for the RequestSDPCommit operation.
func (h *Handler) handleRequestSDPCommit(ctx context.Context, _ *mcp.CallToolRequest, in requestSDPCommitInput) (*mcp.CallToolResult, requestSDPCommitOutput, error) {
	var out requestSDPCommitOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.RequestSDPCommit(rc, in.ProjectID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleAskQuestions is the MCP tool handler for the AskQuestions operation.
func (h *Handler) handleAskQuestions(ctx context.Context, _ *mcp.CallToolRequest, in askQuestionsInput) (*mcp.CallToolResult, askQuestionsOutput, error) {
	var out askQuestionsOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.AskQuestions(rc, in.ProjectID, in.Kind, in.Addressee, in.Questions); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleAcknowledgeStaleBasis is the MCP tool handler for the AcknowledgeStaleBasis operation.
func (h *Handler) handleAcknowledgeStaleBasis(ctx context.Context, _ *mcp.CallToolRequest, in acknowledgeStaleBasisInput) (*mcp.CallToolResult, acknowledgeStaleBasisOutput, error) {
	var out acknowledgeStaleBasisOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.AcknowledgeStaleBasis(rc, in.ProjectID, in.Kind, in.Note); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleSetReviewCommentStatus is the MCP tool handler for the SetReviewCommentStatus operation.
func (h *Handler) handleSetReviewCommentStatus(ctx context.Context, _ *mcp.CallToolRequest, in setReviewCommentStatusInput) (*mcp.CallToolResult, setReviewCommentStatusOutput, error) {
	var out setReviewCommentStatusOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SetReviewCommentStatus(rc, in.ProjectID, in.Kind, in.CommentID, in.Status); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleSubmitReviewDecision is the MCP tool handler for the SubmitReviewDecision operation.
func (h *Handler) handleSubmitReviewDecision(ctx context.Context, _ *mcp.CallToolRequest, in submitReviewDecisionInput) (*mcp.CallToolResult, submitReviewDecisionOutput, error) {
	var out submitReviewDecisionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SubmitReviewDecision(rc, in.ProjectID, in.Kind, in.Decision, in.Feedback); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleSubmitSDPDecision is the MCP tool handler for the SubmitSDPDecision operation.
func (h *Handler) handleSubmitSDPDecision(ctx context.Context, _ *mcp.CallToolRequest, in submitSDPDecisionInput) (*mcp.CallToolResult, submitSDPDecisionOutput, error) {
	var out submitSDPDecisionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.SubmitSDPDecision(rc, in.ProjectID, in.Decision, in.OptionID, in.Feedback); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleListEpisodesForArtifact is the MCP tool handler for the ListEpisodesForArtifact operation.
func (h *Handler) handleListEpisodesForArtifact(ctx context.Context, _ *mcp.CallToolRequest, in listEpisodesForArtifactInput) (*mcp.CallToolResult, listEpisodesForArtifactOutput, error) {
	var out listEpisodesForArtifactOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ListEpisodesForArtifact(rc, in.ProjectID, in.ArtifactKind)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleGetEpisodeTimeline is the MCP tool handler for the GetEpisodeTimeline operation.
func (h *Handler) handleGetEpisodeTimeline(ctx context.Context, _ *mcp.CallToolRequest, in getEpisodeTimelineInput) (*mcp.CallToolResult, getEpisodeTimelineOutput, error) {
	var out getEpisodeTimelineOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.GetEpisodeTimeline(rc, in.ProjectID, in.EpisodeID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// --- helpers ---------------------------------------------------------------

// objectSchema infers the base object JSON Schema for a tool input struct via
// the SDK's reflection (the same inference the SDK would run for a nil input
// schema), so nested object/array params keep their structural shape; callers
// then override the required list and any enum properties. It panics on an
// un-inferrable type — a build-time contract error surfaced at server start.
func objectSchema[T any]() *jsonschema.Schema {
	s, err := jsonschema.For[T](nil)
	if err != nil {
		panic(fmt.Sprintf("mcp input schema inference: %v", err))
	}
	if s.Properties == nil {
		s.Properties = map[string]*jsonschema.Schema{}
	}
	return s
}

// fixUUIDStrings walks an inferred schema and retypes every uuid.UUID ([16]byte)
// property from the SDK's structural inference (an array of 16 0-255 bytes) to
// the schema the value actually marshals as on the wire: a string in RFC 4122
// form. It MUST run before relaxRawJSON, which would otherwise blank the same
// node as an indistinguishable raw-byte-array signature (T11 finding).
func fixUUIDStrings(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isUUIDArray(s) {
		*s = jsonschema.Schema{Type: "string", Format: "uuid"}
		return
	}
	for _, p := range s.Properties {
		fixUUIDStrings(p)
	}
	fixUUIDStrings(s.Items)
	fixUUIDStrings(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		fixUUIDStrings(p)
	}
}

// isUUIDArray reports whether a schema is the jsonschema-go signature of a Go
// uuid.UUID ([16]byte): the same raw-byte-array shape as isRawByteArray, further
// narrowed to exactly 16 items (a fixed-size array), which is unique to UUIDs
// among this codebase's byte-carrier fields.
func isUUIDArray(s *jsonschema.Schema) bool {
	if !isRawByteArray(s) {
		return false
	}
	return s.MinItems != nil && *s.MinItems == 16 && s.MaxItems != nil && *s.MaxItems == 16
}

// relaxRawJSON walks an inferred schema and relaxes every json.RawMessage /
// []byte JSON-carrier property to a permissive (accept-anything) schema. The SDK
// infers such a Go field as an array of 0-255 bytes, which rejects the real JSON
// object/string the manager actually emits or accepts (QA finding F26); the rest
// of the inferred shape is preserved. The permissive schema carries a
// Description so it marshals as a JSON OBJECT (`{"description":...}`) rather
// than the zero-value Schema{}, which the library marshals as bare JSON `true`
// — valid JSON Schema, but rejected by the TS MCP SDK's Zod validator, which
// requires every property schema to be an object (T11 finding).
func relaxRawJSON(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isRawByteArray(s) {
		*s = jsonschema.Schema{Description: "any JSON value"}
		return
	}
	for _, p := range s.Properties {
		relaxRawJSON(p)
	}
	relaxRawJSON(s.Items)
	relaxRawJSON(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		relaxRawJSON(p)
	}
}

// isRawByteArray reports whether a schema is the jsonschema-go signature of a Go
// []byte / json.RawMessage: an array (possibly nullable) whose items are bytes
// (integer, 0..255).
func isRawByteArray(s *jsonschema.Schema) bool {
	isArray := s.Type == "array"
	for _, t := range s.Types {
		if t == "array" {
			isArray = true
		}
	}
	if !isArray || s.Items == nil {
		return false
	}
	it := s.Items
	if it.Type != "integer" {
		return false
	}
	return it.Minimum != nil && *it.Minimum == 0 && it.Maximum != nil && *it.Maximum == 255
}

// allowNullMaps walks an inferred schema and unions "null" into every Go-map
// node's type. jsonschema-go infers a Go map as a bare {type:"object"}, but a
// nil map marshals to JSON null (unlike a nil slice, which the library already
// types as ["null","array"]). Read models legitimately emit nil maps in early
// project phases (e.g. ProjectState.ActivityConstruction before construction),
// so the honest schema must accept null there — otherwise the SDK's output
// validation rejects a payload the HTTP surface serves fine (QA finding F29).
func allowNullMaps(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isMapNode(s) {
		s.Types = []string{"null", "object"}
		s.Type = ""
	}
	for _, p := range s.Properties {
		allowNullMaps(p)
	}
	allowNullMaps(s.Items)
	allowNullMaps(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		allowNullMaps(p)
	}
}

// isMapNode reports whether a schema node is jsonschema-go's inference of a Go
// map: an object node carrying an additionalProperties element schema. A struct
// is also typed "object" but sets additionalProperties to the false schema
// (Not set), which this distinguishes so struct nodes are never made nullable.
func isMapNode(s *jsonschema.Schema) bool {
	isObject := s.Type == "object"
	for _, t := range s.Types {
		if t == "object" {
			isObject = true
		}
	}
	ap := s.AdditionalProperties
	return isObject && ap != nil && ap.Not == nil
}

func mapManagerError(err error) error {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		return fmt.Errorf("%s: %s", me.Kind.String(), me.Detail)
	}
	return err
}
