package main

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestRun_WriteThenCheck drives the CLI end to end against the testgen
// fixture: a first run writes generated + hooks files and reports them; a
// check is then silent; a hand edit to a generated file and an added hook
// are reported and exit non-zero; a rerun rewrites the generated file, leaves
// the edited hooks file alone, and prunes a stale generated file.
func TestRun_WriteThenCheck(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/app/server\n\ngo 1.25\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	project := filepath.Join("..", "..", "testgen", "testdata", "project_tp.json")
	args := []string{"-project", project, "-root", root, "-uitests", "uitests/generated"}

	var out, errOut bytes.Buffer
	if err := run(args, &out, &errOut); err != nil {
		t.Fatalf("first run: %v\n%s", err, errOut.String())
	}
	gen := filepath.Join(root, "internal", "manager", "billing", "manager_scenarios.gen_test.go")
	hooks := filepath.Join(root, "internal", "manager", "billing", "manager_hooks_test.go")
	for _, p := range []string{gen, hooks, filepath.Join(root, "uitests", "generated", "shopClient", "hooks.ts")} {
		if _, err := os.Stat(p); err != nil {
			t.Fatalf("first run did not write %s: %v", p, err)
		}
	}
	if !strings.Contains(out.String(), "wrote hooks internal/manager/billing/manager_hooks_test.go") {
		t.Errorf("first run output: %s", out.String())
	}

	out.Reset()
	if err := run(append(args, "-check"), &out, &errOut); err != nil || out.Len() != 0 {
		t.Fatalf("check on a fresh tree: err=%v out=%s", err, out.String())
	}

	if err := os.WriteFile(gen, []byte("// edited\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	edited, err := os.ReadFile(hooks)
	if err != nil {
		t.Fatal(err)
	}
	edited = append(edited, []byte("\nfunc Step_extra(t *testing.T) {}\n")...)
	if err := os.WriteFile(hooks, edited, 0o600); err != nil {
		t.Fatal(err)
	}
	stale := filepath.Join(root, "internal", "manager", "gone", "manager_scenarios.gen_test.go")
	if err := os.MkdirAll(filepath.Dir(stale), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(stale, []byte("// Code generated by testgen. DO NOT EDIT.\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	out.Reset()
	err = run(append(args, "-check"), &out, &errOut)
	if !errors.Is(err, errDrift) {
		t.Fatalf("check must report drift, got err=%v", err)
	}
	for _, want := range []string{
		"stale: internal/manager/billing/manager_scenarios.gen_test.go",
		"orphan hook Step_extra in internal/manager/billing/manager_hooks_test.go",
		"orphan generated file internal/manager/gone/manager_scenarios.gen_test.go", // no plan produces it any more; a write run would prune it
	} {
		if !strings.Contains(out.String(), want) {
			t.Errorf("check output lacks %q:\n%s", want, out.String())
		}
	}

	out.Reset()
	if err := run(args, &out, &errOut); err != nil {
		t.Fatalf("rerun: %v", err)
	}
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Errorf("stale generated file not pruned: %v", err)
	}
	if !strings.Contains(out.String(), "pruned internal/manager/gone/manager_scenarios.gen_test.go") {
		t.Errorf("rerun output: %s", out.String())
	}
	after, err := os.ReadFile(hooks)
	if err != nil || !bytes.Equal(after, edited) {
		t.Errorf("rerun must leave the agent-owned hooks file alone")
	}
	regen, err := os.ReadFile(gen)
	if err != nil || string(regen) == "// edited\n" {
		t.Errorf("rerun must rewrite the generated file")
	}
}

// TestRun_DefaultUITestsDir drives the CLI with its own defaults for -root
// (the server module, here <tmp>/server) and -uitests (../uitests/generated):
// the Playwright config lands in the sibling uitests module and its results
// tree is spelled relative to that module's root (../../test-results/<comp>),
// not relative to however -uitests was written; -check is then silent.
func TestRun_DefaultUITestsDir(t *testing.T) {
	repo := t.TempDir()
	root := filepath.Join(repo, "server")
	if err := os.MkdirAll(root, 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/app/server\n\ngo 1.25\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	project := filepath.Join("..", "..", "testgen", "testdata", "project_tp.json")
	args := []string{"-project", project, "-root", root}

	var out, errOut bytes.Buffer
	if err := run(args, &out, &errOut); err != nil {
		t.Fatalf("run: %v\n%s", err, errOut.String())
	}
	cfg, err := os.ReadFile(filepath.Join(repo, "uitests", "generated", "shopClient", "playwright.config.gen.ts"))
	if err != nil {
		t.Fatalf("config not written under the sibling uitests module: %v", err)
	}
	for _, want := range []string{"outputDir: '../../test-results/shopClient'", "outputFile: '../../test-results/shopClient/playwright.json'"} {
		if !strings.Contains(string(cfg), want) {
			t.Errorf("missing %q in config\n%s", want, cfg)
		}
	}

	out.Reset()
	if err := run(append(args, "-check"), &out, &errOut); err != nil || out.Len() != 0 {
		t.Fatalf("check on a fresh tree: err=%v out=%s", err, out.String())
	}
}
