// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package systemdesign

import (
	"encoding/json"
	fwm "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator/server/internal/engine/estimation"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/constructionpipeline"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/projectstate"
	"github.com/mixofreality-studio/archistrator/server/internal/resourceaccess/sourcecontrol"
	"go.temporal.io/sdk/client"
	"time"
)

type ActivityBuildStatus int

const (
	BuildInConstruction ActivityBuildStatus = 0
	BuildInReview       ActivityBuildStatus = 1
	BuildIntegrated     ActivityBuildStatus = 2
	BuildFailed         ActivityBuildStatus = 3
)

type ActivityConstructionPhase int

const (
	ActivityConstructionNotStarted ActivityConstructionPhase = 0
	ActivityConstructionRunning    ActivityConstructionPhase = 1
	ActivityConstructionDone       ActivityConstructionPhase = 2
	ActivityConstructionFailed     ActivityConstructionPhase = 3
)

type ActivityConstructionStatus struct {
	ActivityID    string                    `json:"ActivityID"`
	Type          ActivityType              `json:"Type"`
	Kind          ActivityType              `json:"Kind"`
	Variant       TestingVariant            `json:"Variant"`
	Phase         ActivityConstructionPhase `json:"Phase"`
	Phases        []PhaseCompletion         `json:"Phases"`
	CurrentPhase  ActivityMethodPhase       `json:"CurrentPhase"`
	StartedAt     *time.Time                `json:"startedAt,omitempty"`
	CompletedAt   *time.Time                `json:"completedAt,omitempty"`
	BuildStatus   ActivityBuildStatus       `json:"BuildStatus"`
	Produced      []ProducedArtifact        `json:"Produced"`
	FailureReason FailureReason             `json:"FailureReason"`
	FailureDetail string                    `json:"FailureDetail"`
}

type ActivityGitStatus struct {
	ActivityID     string       `json:"ActivityID"`
	BranchName     string       `json:"BranchName"`
	BranchRef      string       `json:"BranchRef"`
	PullRequestRef string       `json:"PullRequestRef"`
	PrNumber       int64        `json:"PrNumber"`
	PrURL          string       `json:"PrURL"`
	CICheck        CICheckState `json:"CICheck"`
	ArchApproved   bool         `json:"ArchApproved"`
	Merged         bool         `json:"Merged"`
	CRLabel        string       `json:"CRLabel"`
	IsRevert       bool         `json:"IsRevert"`
	UpdatedAt      time.Time    `json:"UpdatedAt"`
}

type ActivityMethodPhase string

type ActivityType int

const (
	ActivityTypeService       ActivityType = 0
	ActivityTypeFrontend      ActivityType = 1
	ActivityTypeTesting       ActivityType = 2
	ActivityTypeDeployment    ActivityType = 3
	ActivityTypeDocumentation ActivityType = 4
)

type AnchoredComment struct {
	JSONPath   string `json:"jsonPath"`
	Text       string `json:"text"`
	AnchorText string `json:"anchorText"`
}

type ArtifactKind int

const (
	KindMission              ArtifactKind = 0
	KindGlossary             ArtifactKind = 1
	KindScrubbedRequirements ArtifactKind = 2
	KindVolatilities         ArtifactKind = 3
	KindCoreUseCases         ArtifactKind = 4
	KindSystem               ArtifactKind = 5
	KindOperationalConcepts  ArtifactKind = 6
	KindStandardCheck        ArtifactKind = 7
	KindPlanningAssumptions  ArtifactKind = 8
	KindActivityList         ArtifactKind = 9
	KindNetwork              ArtifactKind = 10
	KindNormalSolution       ArtifactKind = 11
	KindSubcriticalSolution  ArtifactKind = 12
	KindCompressedSolution   ArtifactKind = 13
	KindDecompressedSolution ArtifactKind = 14
	KindRiskModel            ArtifactKind = 15
	KindSdpReview            ArtifactKind = 16
)

type ArtifactSlotModel struct {
	Kind  string           `json:"kind"`
	Model *json.RawMessage `json:"model,omitempty"`
}

type ArtifactSlotView struct {
	Kind            string            `json:"kind"`
	Stage           ArtifactStage     `json:"stage"`
	Model           ArtifactSlotModel `json:"model"`
	Notes           *string           `json:"notes,omitempty"`
	StaleBasis      *bool             `json:"staleBasis,omitempty"`
	StaleBasisCause *StaleCauseView   `json:"staleBasisCause,omitempty"`
	Revisions       *int64            `json:"revisions,omitempty"`
	Provenance      *ProvenanceView   `json:"provenance,omitempty"`
}

type ArtifactStage int

const (
	ArtifactStageEmpty          ArtifactStage = 0
	ArtifactStageAwaitingReview ArtifactStage = 1
	ArtifactStageCommitted      ArtifactStage = 2
	ArtifactStageRejected       ArtifactStage = 3
	ArtifactStageWithdrawn      ArtifactStage = 4
)

type CICheckState int

const (
	CICheckPending CICheckState = 0
	CICheckSuccess CICheckState = 1
	CICheckFailure CICheckState = 2
)

type ConstructionProgress struct {
	Week           int64     `json:"Week"`
	TotalWeeks     int64     `json:"TotalWeeks"`
	HandOffModel   string    `json:"HandOffModel"`
	SupervisionCap int64     `json:"SupervisionCap"`
	EV             EVCurve   `json:"EV"`
	Points         []EvPoint `json:"points,omitempty"`
}

type ContractOp struct {
	Signature  string           `json:"Signature"`
	Stereotype string           `json:"Stereotype"`
	Note       string           `json:"Note"`
	Inputs     []ContractStruct `json:"Inputs"`
	Outputs    []ContractStruct `json:"Outputs"`
}

type ContractParty struct {
	Name  string `json:"Name"`
	Layer string `json:"Layer"`
	How   string `json:"How"`
}

type ContractRevision struct {
	Rev        string `json:"Rev"`
	At         string `json:"At"`
	By         string `json:"By"`
	ByActivity string `json:"ByActivity"`
	Summary    string `json:"Summary"`
}

type ContractStruct struct {
	Name   string    `json:"Name"`
	Fields []GoField `json:"Fields"`
}

type DefectView struct {
	Id       string `json:"id"`
	Title    string `json:"title"`
	Severity string `json:"severity"`
	Note     string `json:"note"`
}

type DraftModel struct {
	Kind  string           `json:"kind"`
	Model *json.RawMessage `json:"model,omitempty"`
}

type EVCurve struct {
	Weeks   []int64   `json:"weeks"`
	Earned  []float64 `json:"earned"`
	Planned []float64 `json:"planned"`
	SPI     float64   `json:"spi"`
}

type EvPoint struct {
	Week       int64    `json:"week"`
	EarnedPct  float64  `json:"earnedPct"`
	PlannedPct float64  `json:"plannedPct"`
	Note       string   `json:"note"`
	AcPct      *float64 `json:"acPct,omitempty"`
}

type FailureReason int

const (
	FailureReasonUnknown            FailureReason = 0
	FailureReasonPipelineFailed     FailureReason = 1
	FailureReasonPipelineCancelled  FailureReason = 2
	FailureReasonPipelineTimedOut   FailureReason = 3
	FailureReasonVarianceExhausted  FailureReason = 4
	FailureReasonEscalationTimedOut FailureReason = 5
)

type Finding struct {
	RuleID   RuleID    `json:"ruleId"`
	Severity Severity  `json:"severity"`
	Message  string    `json:"message"`
	Location *Location `json:"location,omitempty"`
}

type GoField struct {
	Name string `json:"Name"`
	Type string `json:"Type"`
	Note string `json:"Note"`
}

type Location struct {
	Ordinal int64  `json:"ordinal"`
	Section string `json:"section"`
}

type OperatingModel string

type OwnerScope string

type Phase int

const (
	PhaseSystemDesign  Phase = 0
	PhaseProjectDesign Phase = 1
	PhaseConstruction  Phase = 2
)

type PhaseAdvanceResult struct {
	Advanced         bool           `json:"advanced"`
	MissingArtifacts []ArtifactKind `json:"missingArtifacts"`
}

type PhaseCompletion struct {
	Phase       ActivityMethodPhase `json:"Phase"`
	Weight      int64               `json:"Weight"`
	Completed   bool                `json:"Completed"`
	CompletedAt *time.Time          `json:"completedAt,omitempty"`
	ArtifactRef string              `json:"ArtifactRef"`
}

type ProducedArtifact struct {
	Kind     string `json:"Kind"`
	Title    string `json:"Title"`
	Source   string `json:"Source"`
	Produced bool   `json:"Produced"`
	Note     string `json:"Note"`
}

type ProjectID string

type ProjectState struct {
	ProjectID            ProjectID                             `json:"ProjectID"`
	Name                 string                                `json:"Name"`
	Owner                OwnerScope                            `json:"Owner"`
	Phase                Phase                                 `json:"Phase"`
	PhaseName            string                                `json:"PhaseName"`
	Version              int64                                 `json:"Version"`
	OperatingModel       OperatingModel                        `json:"operatingModel"`
	Research             ResearchInput                         `json:"Research"`
	Slots                []ArtifactSlotView                    `json:"Slots"`
	GitRows              map[string]ActivityGitStatus          `json:"GitRows"`
	ActivityConstruction map[string]ActivityConstructionStatus `json:"ActivityConstruction"`
	ConstructionProgress *ConstructionProgress                 `json:"constructionProgress,omitempty"`
	ServiceContracts     map[string]ServiceContract            `json:"ServiceContracts"`
	ReviewPolicy         *ReviewPolicyView                     `json:"reviewPolicy,omitempty"`
	TestingState         *TestingStateView                     `json:"testingState,omitempty"`
}

type ProjectSummary struct {
	ProjectID      ProjectID  `json:"ProjectID"`
	Name           string     `json:"Name"`
	Owner          OwnerScope `json:"Owner"`
	Phase          Phase      `json:"Phase"`
	PhaseName      string     `json:"PhaseName"`
	CommittedCount int64      `json:"CommittedCount"`
	TotalCount     int64      `json:"TotalCount"`
	UpdatedAt      time.Time  `json:"UpdatedAt"`
}

type ResearchInput struct {
	Sources []ResearchSource `json:"sources"`
}

type ResearchSource struct {
	Title        string `json:"title"`
	Content      string `json:"content"`
	ContentBytes *int64 `json:"contentBytes,omitempty"`
}

type ReviewCommentView struct {
	ID         string `json:"id"`
	Anchor     string `json:"anchor"`
	AnchorText string `json:"anchorText"`
	Text       string `json:"text"`
	AuthorRole string `json:"authorRole"`
	Round      int64  `json:"round"`
	Status     string `json:"status"`
	Response   string `json:"response"`
	Type       string `json:"type"`
	Addressee  string `json:"addressee"`
}

type ReviewDecision int

const (
	ReviewDecisionUnknown ReviewDecision = 0
	ReviewApprove         ReviewDecision = 1
	ReviewReject          ReviewDecision = 2
	ReviewWithdraw        ReviewDecision = 3
)

type ReviewFeedback struct {
	Notes    string            `json:"notes"`
	Comments []AnchoredComment `json:"comments,omitempty"`
}

type ReviewPolicyView struct {
	GatedPhasesByType map[string][]string `json:"gatedPhasesByType"`
}

type RuleID string

type ServiceContract struct {
	Component     string             `json:"Component"`
	Layer         string             `json:"Layer"`
	Stereotype    string             `json:"Stereotype"`
	Volatility    string             `json:"Volatility"`
	Status        string             `json:"Status"`
	Inbound       []ContractParty    `json:"Inbound"`
	Outbound      []ContractParty    `json:"Outbound"`
	Ops           []ContractOp       `json:"Ops"`
	DataContracts []string           `json:"DataContracts"`
	ErrorModel    string             `json:"ErrorModel"`
	Idempotency   string             `json:"Idempotency"`
	Revisions     []ContractRevision `json:"Revisions"`
}

type SessionRef string

type SessionStage int

const (
	SessionStageUnknown SessionStage = 0
	StageDrafting       SessionStage = 1
	StageAwaitingReview SessionStage = 2
	StageRedrafting     SessionStage = 3
	StageCommitted      SessionStage = 4
	StageWithdrawn      SessionStage = 5
	StageRefused        SessionStage = 6
	StageDraftFailed    SessionStage = 7
)

type SessionStateView struct {
	ProjectID     ProjectID           `json:"projectId"`
	ArtifactKind  ArtifactKind        `json:"artifactKind"`
	Stage         SessionStage        `json:"stage"`
	Draft         DraftModel          `json:"draft"`
	Findings      []Finding           `json:"findings,omitempty"`
	FailureReason *string             `json:"failureReason,omitempty"`
	FailureRunURL *string             `json:"failureRunUrl,omitempty"`
	StageName     string              `json:"stageName"`
	ReviewThread  []ReviewCommentView `json:"reviewThread,omitempty"`
}

type Severity string

const (
	SeverityInfo    Severity = "info"
	SeverityWarning Severity = "warning"
	SeverityError   Severity = "error"
)

type SystemTestPlanView struct {
	Scenarios []TestScenarioView `json:"scenarios"`
}

type TestArgView struct {
	Name      string `json:"name"`
	Value     string `json:"value"`
	SchemaRef string `json:"schemaRef"`
}

type TestCaseView struct {
	Id              string         `json:"id"`
	Kind            string         `json:"kind"`
	Title           string         `json:"title"`
	Proves          string         `json:"proves"`
	ExpectedOutcome string         `json:"expectedOutcome"`
	Steps           []TestStepView `json:"steps"`
}

type TestExpectView struct {
	Result        string `json:"result"`
	ErrorExpected bool   `json:"errorExpected"`
	ErrorCode     string `json:"errorCode"`
}

type TestRunView struct {
	Id     string `json:"id"`
	Passed int64  `json:"passed"`
	Failed int64  `json:"failed"`
	Note   string `json:"note"`
}

type TestScenarioView struct {
	Id          string         `json:"id"`
	UseCase     string         `json:"useCase"`
	Title       string         `json:"title"`
	Cases       []TestCaseView `json:"cases"`
	Description string         `json:"description"`
}

type TestStepView struct {
	Seq       int64          `json:"seq"`
	Component string         `json:"component"`
	Operation string         `json:"operation"`
	Status    string         `json:"status"`
	Inputs    []TestArgView  `json:"inputs"`
	Expect    TestExpectView `json:"expect"`
	Assertion string         `json:"assertion"`
}

type TestingStateView struct {
	TestRuns       []TestRunView       `json:"testRuns"`
	Defects        []DefectView        `json:"defects"`
	SystemTestPlan *SystemTestPlanView `json:"systemTestPlan,omitempty"`
}

type TestingVariant int

const (
	TestVariantPlan       TestingVariant = 0
	TestVariantHarness    TestingVariant = 1
	TestVariantPerf       TestingVariant = 2
	TestVariantSystemTest TestingVariant = 3
	TestVariantQAProcess  TestingVariant = 4
)

type Version int64

// SystemDesignManager is the generated service-contract interface for this component.
type SystemDesignManager interface {
	AdvancePhase(rc fwm.Context, projectID ProjectID, acknowledgeStale bool) (PhaseAdvanceResult, error)
	CreateProject(rc fwm.Context, owner OwnerScope, name string) (ProjectID, error)
	GetProject(rc fwm.Context, projectID ProjectID) (ProjectState, error)
	GetSessionState(rc fwm.Context, projectID ProjectID, kind ArtifactKind) (SessionStateView, error)
	ListProjects(rc fwm.Context, owner OwnerScope) ([]ProjectSummary, error)
	RequestArtifactDraft(rc fwm.Context, projectID ProjectID, kind ArtifactKind, feedback *ReviewFeedback) (SessionRef, error)
	SetOperatingModel(rc fwm.Context, projectID ProjectID, model OperatingModel) (Version, error)
	SetResearchInput(rc fwm.Context, projectID ProjectID, research ResearchInput) (Version, error)
	AskQuestions(rc fwm.Context, projectID ProjectID, kind ArtifactKind, addressee string, questions []AnchoredComment) error
	AcknowledgeStaleBasis(rc fwm.Context, projectID ProjectID, kind ArtifactKind, note string) error
	SetReviewCommentStatus(rc fwm.Context, projectID ProjectID, kind ArtifactKind, commentID string, status string) error
	StartSystemDesign(rc fwm.Context, projectID ProjectID) (SessionRef, error)
	SubmitReviewDecision(rc fwm.Context, projectID ProjectID, kind ArtifactKind, decision ReviewDecision, feedback *ReviewFeedback) error
}

// NewSystemDesignManager constructs the SystemDesignManager, delegating to the hand-written, unexported
// builder newSystemDesignManager in the manager package (which owns the stateful facade setup:
// the Temporal client, the deps, and config). The constructor returns the
// interface, so the concrete manager impl stays unexported.
func NewSystemDesignManager(client client.Client, projectState projectstate.ProjectStateAccess, pipeline constructionpipeline.ConstructionPipelineAccess, rail sourcecontrol.SourceControlAccess, repo func(projectID ProjectID) (sourcecontrol.RepoRef, bool), estimator estimation.EstimationEngine, repoBase string) SystemDesignManager {
	return newSystemDesignManager(client, projectState, pipeline, rail, repo, estimator, repoBase)
}
