// Code generated by temporalgen. DO NOT EDIT.

package order

import (
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

// TaskQueue is the manager's Temporal task queue (derived from the contract
// interface name).
const TaskQueue = "order"

// genWorkerManifest is what the hand-written manager supplies to
// RegisterWorker: the workflow functions (codegen cannot know them), any
// hybrid hand-written activities, the invoker options hook, and the
// genActivities dep threading.
type genWorkerManifest struct {
	Workflows        []genRegisteredWorkflow
	CustomActivities []genRegisteredActivity
	ActivityOptions  func(activityName string) (workflow.ActivityOptions, bool)
	Activities       genActivities
}

type genRegisteredWorkflow struct {
	Name string
	Fn   any
}

type genRegisteredActivity struct {
	Name string
	Fn   any
}

// RegisterWorker registers every workflow + generated activity + custom
// activity on w. Forgetting a generated activity is impossible; workflows and
// hybrids are exactly what the manifest declares.
func RegisterWorker(w worker.Worker, mf genWorkerManifest) {
	for _, wf := range mf.Workflows {
		w.RegisterWorkflowWithOptions(wf.Fn, workflow.RegisterOptions{Name: wf.Name})
	}
	acts := &mf.Activities
	w.RegisterActivityWithOptions(acts.OrderStateCancelOrder, activity.RegisterOptions{Name: "orderStateAccess.cancelOrder"})
	w.RegisterActivityWithOptions(acts.OrderStateChargeOrder, activity.RegisterOptions{Name: "orderStateAccess.chargeOrder"})
	w.RegisterActivityWithOptions(acts.OrderStatePurgeOrder, activity.RegisterOptions{Name: "orderStateAccess.purgeOrder"})
	w.RegisterActivityWithOptions(acts.OrderStatePutOrder, activity.RegisterOptions{Name: "orderStateAccess.putOrder"})
	w.RegisterActivityWithOptions(acts.OrderStateReadOrder, activity.RegisterOptions{Name: "orderStateAccess.readOrder"})
	for _, ca := range mf.CustomActivities {
		w.RegisterActivityWithOptions(ca.Fn, activity.RegisterOptions{Name: ca.Name})
	}
}
