// Code generated by cmd/clientgen (mcpemit). DO NOT EDIT.
// Source contract:

package operations

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/jsonschema-go/jsonschema"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/google/uuid"

	fwmanager "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	"github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	mgr "github.com/mixofreality-studio/archistrator/server/internal/manager/operations"
)

// Handler binds the OperationsManager manager to MCP tools.
type Handler struct {
	Manager mgr.OperationsManager
}

// Register adds every operation as an mcp.Tool on srv, each carrying an
// explicit human description and an explicit input JSON Schema (enum values +
// meanings, REST-matching optionality) so an agentic consumer needs no source.
func (h *Handler) Register(srv *mcp.Server) {
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsApplyDelinquencyPolicy", Description: "Apply the billing-delinquency policy to a customer (e.g. suspend or restore their operated systems) given the current delinquency context.", InputSchema: applyDelinquencyPolicyInputSchema(), OutputSchema: applyDelinquencyPolicyOutputSchema()}, h.handleApplyDelinquencyPolicy)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsDeployAfterConstruction", Description: "Deploy a desired-state change to an operated application once its construction completes. Returns the deployment outcome.", InputSchema: deployAfterConstructionInputSchema(), OutputSchema: deployAfterConstructionOutputSchema()}, h.handleDeployAfterConstruction)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsQueryCostProjection", Description: "Project the operating cost of an operated application, optionally across scale/what-if points. requestID idempotently identifies the query. Read-only.", InputSchema: queryCostProjectionInputSchema(), OutputSchema: queryCostProjectionOutputSchema()}, h.handleQueryCostProjection)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsQueryDeploymentHealth", Description: "Return the deployment diagram's per-node health for an operated application: nodes it deploys colour healthy/unhealthy from the live cluster, every other node on the diagram (e.g. the architect's own laptop or browser) reads neutral. Read-only.", InputSchema: queryDeploymentHealthInputSchema(), OutputSchema: queryDeploymentHealthOutputSchema()}, h.handleQueryDeploymentHealth)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsQueryOperatedSystemView", Description: "Return the live operated-system view (runtime status and topology) for an operated application. requestID idempotently identifies the query. Read-only.", InputSchema: queryOperatedSystemViewInputSchema(), OutputSchema: queryOperatedSystemViewOutputSchema()}, h.handleQueryOperatedSystemView)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsReconcileOperatedState", Description: "Reconcile the actual operated state toward the desired state across the given scope (or everything when omitted). tickID idempotently identifies the reconcile tick.", InputSchema: reconcileOperatedStateInputSchema(), OutputSchema: reconcileOperatedStateOutputSchema()}, h.handleReconcileOperatedState)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsRegisterOperatedApp", Description: "Onboard a new operated application by seeding its head-state row — the customer, project, and deployable-bundle reference it will deploy from. Must run once before the first DeployAfterConstruction. Returns the new head-state version.", InputSchema: registerOperatedAppInputSchema(), OutputSchema: registerOperatedAppOutputSchema()}, h.handleRegisterOperatedApp)
	mcp.AddTool(srv, &mcp.Tool{Name: "operationsWithdrawSystem", Description: "Withdraw and tear down an operated application (identified by its deploy changeID) for the given reason. Returns the withdrawal outcome.", InputSchema: withdrawSystemInputSchema(), OutputSchema: withdrawSystemOutputSchema()}, h.handleWithdrawSystem)
}

type applyDelinquencyPolicyInput struct {
	CustomerID         uuid.UUID              `json:"customerID"`
	DelinquencyContext mgr.DelinquencyContext `json:"delinquencyContext"`
}

type applyDelinquencyPolicyOutput struct{}

type deployAfterConstructionInput struct {
	OperatedAppID uuid.UUID              `json:"operatedAppID"`
	Change        mgr.DesiredStateChange `json:"change"`
}

type deployAfterConstructionOutput struct {
	Result mgr.DeployResult `json:"result"`
}

type queryCostProjectionInput struct {
	OperatedAppID uuid.UUID              `json:"operatedAppID"`
	RequestID     string                 `json:"requestID"`
	Points        *mgr.ScaleWhatIfPoints `json:"points,omitempty"`
}

type queryCostProjectionOutput struct {
	Result mgr.CostProjectionSeam `json:"result"`
}

type queryDeploymentHealthInput struct {
	OperatedAppID uuid.UUID `json:"operatedAppID"`
}

type queryDeploymentHealthOutput struct {
	Result mgr.DeploymentHealth `json:"result"`
}

type queryOperatedSystemViewInput struct {
	OperatedAppID uuid.UUID `json:"operatedAppID"`
	RequestID     string    `json:"requestID"`
}

type queryOperatedSystemViewOutput struct {
	Result mgr.OperatedSystemView `json:"result"`
}

type reconcileOperatedStateInput struct {
	TickID string              `json:"tickID"`
	Scope  *mgr.ReconcileScope `json:"scope,omitempty"`
}

type reconcileOperatedStateOutput struct {
	Result mgr.ReconcileResult `json:"result"`
}

type registerOperatedAppInput struct {
	OperatedAppID       uuid.UUID `json:"operatedAppID"`
	CustomerID          uuid.UUID `json:"customerID"`
	ProjectRef          string    `json:"projectRef"`
	DeployableBundleRef string    `json:"deployableBundleRef"`
}

type registerOperatedAppOutput struct {
	Result mgr.Version `json:"result"`
}

type withdrawSystemInput struct {
	OperatedAppID uuid.UUID          `json:"operatedAppID"`
	ChangeID      string             `json:"changeID"`
	Reason        mgr.WithdrawReason `json:"reason"`
}

type withdrawSystemOutput struct {
	Result mgr.WithdrawResult `json:"result"`
}

// applyDelinquencyPolicyInputSchema is the explicit MCP input schema for the ApplyDelinquencyPolicy operation.
func applyDelinquencyPolicyInputSchema() *jsonschema.Schema {
	s := objectSchema[applyDelinquencyPolicyInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"customerID", "delinquencyContext"}
	return s
}

// deployAfterConstructionInputSchema is the explicit MCP input schema for the DeployAfterConstruction operation.
func deployAfterConstructionInputSchema() *jsonschema.Schema {
	s := objectSchema[deployAfterConstructionInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"operatedAppID", "change"}
	return s
}

// queryCostProjectionInputSchema is the explicit MCP input schema for the QueryCostProjection operation.
func queryCostProjectionInputSchema() *jsonschema.Schema {
	s := objectSchema[queryCostProjectionInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"operatedAppID", "requestID"}
	return s
}

// queryDeploymentHealthInputSchema is the explicit MCP input schema for the QueryDeploymentHealth operation.
func queryDeploymentHealthInputSchema() *jsonschema.Schema {
	s := objectSchema[queryDeploymentHealthInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"operatedAppID"}
	return s
}

// queryOperatedSystemViewInputSchema is the explicit MCP input schema for the QueryOperatedSystemView operation.
func queryOperatedSystemViewInputSchema() *jsonschema.Schema {
	s := objectSchema[queryOperatedSystemViewInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"operatedAppID", "requestID"}
	return s
}

// reconcileOperatedStateInputSchema is the explicit MCP input schema for the ReconcileOperatedState operation.
func reconcileOperatedStateInputSchema() *jsonschema.Schema {
	s := objectSchema[reconcileOperatedStateInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"tickID"}
	return s
}

// registerOperatedAppInputSchema is the explicit MCP input schema for the RegisterOperatedApp operation.
func registerOperatedAppInputSchema() *jsonschema.Schema {
	s := objectSchema[registerOperatedAppInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"operatedAppID", "customerID", "projectRef", "deployableBundleRef"}
	return s
}

// withdrawSystemInputSchema is the explicit MCP input schema for the WithdrawSystem operation.
func withdrawSystemInputSchema() *jsonschema.Schema {
	s := objectSchema[withdrawSystemInput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	s.Required = []string{"operatedAppID", "changeID", "reason"}
	return s
}

// applyDelinquencyPolicyOutputSchema is the explicit MCP output schema for the ApplyDelinquencyPolicy operation.
func applyDelinquencyPolicyOutputSchema() *jsonschema.Schema {
	s := objectSchema[applyDelinquencyPolicyOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// deployAfterConstructionOutputSchema is the explicit MCP output schema for the DeployAfterConstruction operation.
func deployAfterConstructionOutputSchema() *jsonschema.Schema {
	s := objectSchema[deployAfterConstructionOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// queryCostProjectionOutputSchema is the explicit MCP output schema for the QueryCostProjection operation.
func queryCostProjectionOutputSchema() *jsonschema.Schema {
	s := objectSchema[queryCostProjectionOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// queryDeploymentHealthOutputSchema is the explicit MCP output schema for the QueryDeploymentHealth operation.
func queryDeploymentHealthOutputSchema() *jsonschema.Schema {
	s := objectSchema[queryDeploymentHealthOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// queryOperatedSystemViewOutputSchema is the explicit MCP output schema for the QueryOperatedSystemView operation.
func queryOperatedSystemViewOutputSchema() *jsonschema.Schema {
	s := objectSchema[queryOperatedSystemViewOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// reconcileOperatedStateOutputSchema is the explicit MCP output schema for the ReconcileOperatedState operation.
func reconcileOperatedStateOutputSchema() *jsonschema.Schema {
	s := objectSchema[reconcileOperatedStateOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// registerOperatedAppOutputSchema is the explicit MCP output schema for the RegisterOperatedApp operation.
func registerOperatedAppOutputSchema() *jsonschema.Schema {
	s := objectSchema[registerOperatedAppOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// withdrawSystemOutputSchema is the explicit MCP output schema for the WithdrawSystem operation.
func withdrawSystemOutputSchema() *jsonschema.Schema {
	s := objectSchema[withdrawSystemOutput]()
	fixUUIDStrings(s)
	relaxRawJSON(s)
	allowNullMaps(s)
	return s
}

// handleApplyDelinquencyPolicy is the MCP tool handler for the ApplyDelinquencyPolicy operation.
func (h *Handler) handleApplyDelinquencyPolicy(ctx context.Context, _ *mcp.CallToolRequest, in applyDelinquencyPolicyInput) (*mcp.CallToolResult, applyDelinquencyPolicyOutput, error) {
	var out applyDelinquencyPolicyOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	if err := h.Manager.ApplyDelinquencyPolicy(rc, in.CustomerID, in.DelinquencyContext); err != nil {
		return nil, out, mapManagerError(err)
	}
	return nil, out, nil
}

// handleDeployAfterConstruction is the MCP tool handler for the DeployAfterConstruction operation.
func (h *Handler) handleDeployAfterConstruction(ctx context.Context, _ *mcp.CallToolRequest, in deployAfterConstructionInput) (*mcp.CallToolResult, deployAfterConstructionOutput, error) {
	var out deployAfterConstructionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.DeployAfterConstruction(rc, in.OperatedAppID, in.Change)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleQueryCostProjection is the MCP tool handler for the QueryCostProjection operation.
func (h *Handler) handleQueryCostProjection(ctx context.Context, _ *mcp.CallToolRequest, in queryCostProjectionInput) (*mcp.CallToolResult, queryCostProjectionOutput, error) {
	var out queryCostProjectionOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.QueryCostProjection(rc, in.OperatedAppID, in.RequestID, in.Points)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleQueryDeploymentHealth is the MCP tool handler for the QueryDeploymentHealth operation.
func (h *Handler) handleQueryDeploymentHealth(ctx context.Context, _ *mcp.CallToolRequest, in queryDeploymentHealthInput) (*mcp.CallToolResult, queryDeploymentHealthOutput, error) {
	var out queryDeploymentHealthOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.QueryDeploymentHealth(rc, in.OperatedAppID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleQueryOperatedSystemView is the MCP tool handler for the QueryOperatedSystemView operation.
func (h *Handler) handleQueryOperatedSystemView(ctx context.Context, _ *mcp.CallToolRequest, in queryOperatedSystemViewInput) (*mcp.CallToolResult, queryOperatedSystemViewOutput, error) {
	var out queryOperatedSystemViewOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.QueryOperatedSystemView(rc, in.OperatedAppID, in.RequestID)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleReconcileOperatedState is the MCP tool handler for the ReconcileOperatedState operation.
func (h *Handler) handleReconcileOperatedState(ctx context.Context, _ *mcp.CallToolRequest, in reconcileOperatedStateInput) (*mcp.CallToolResult, reconcileOperatedStateOutput, error) {
	var out reconcileOperatedStateOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.ReconcileOperatedState(rc, in.TickID, in.Scope)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleRegisterOperatedApp is the MCP tool handler for the RegisterOperatedApp operation.
func (h *Handler) handleRegisterOperatedApp(ctx context.Context, _ *mcp.CallToolRequest, in registerOperatedAppInput) (*mcp.CallToolResult, registerOperatedAppOutput, error) {
	var out registerOperatedAppOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.RegisterOperatedApp(rc, in.OperatedAppID, in.CustomerID, in.ProjectRef, in.DeployableBundleRef)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// handleWithdrawSystem is the MCP tool handler for the WithdrawSystem operation.
func (h *Handler) handleWithdrawSystem(ctx context.Context, _ *mcp.CallToolRequest, in withdrawSystemInput) (*mcp.CallToolResult, withdrawSystemOutput, error) {
	var out withdrawSystemOutput
	principal, _ := security.PrincipalFrom(ctx)
	rc := fwmanager.Context{Context: ctx, Principal: principal}
	result, err := h.Manager.WithdrawSystem(rc, in.OperatedAppID, in.ChangeID, in.Reason)
	if err != nil {
		return nil, out, mapManagerError(err)
	}
	out.Result = result
	return nil, out, nil
}

// --- helpers ---------------------------------------------------------------

// objectSchema infers the base object JSON Schema for a tool input struct via
// the SDK's reflection (the same inference the SDK would run for a nil input
// schema), so nested object/array params keep their structural shape; callers
// then override the required list and any enum properties. It panics on an
// un-inferrable type — a build-time contract error surfaced at server start.
func objectSchema[T any]() *jsonschema.Schema {
	s, err := jsonschema.For[T](nil)
	if err != nil {
		panic(fmt.Sprintf("mcp input schema inference: %v", err))
	}
	if s.Properties == nil {
		s.Properties = map[string]*jsonschema.Schema{}
	}
	return s
}

// fixUUIDStrings walks an inferred schema and retypes every uuid.UUID ([16]byte)
// property from the SDK's structural inference (an array of 16 0-255 bytes) to
// the schema the value actually marshals as on the wire: a string in RFC 4122
// form. It MUST run before relaxRawJSON, which would otherwise blank the same
// node as an indistinguishable raw-byte-array signature (T11 finding).
func fixUUIDStrings(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isUUIDArray(s) {
		*s = jsonschema.Schema{Type: "string", Format: "uuid"}
		return
	}
	for _, p := range s.Properties {
		fixUUIDStrings(p)
	}
	fixUUIDStrings(s.Items)
	fixUUIDStrings(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		fixUUIDStrings(p)
	}
}

// isUUIDArray reports whether a schema is the jsonschema-go signature of a Go
// uuid.UUID ([16]byte): the same raw-byte-array shape as isRawByteArray, further
// narrowed to exactly 16 items (a fixed-size array), which is unique to UUIDs
// among this codebase's byte-carrier fields.
func isUUIDArray(s *jsonschema.Schema) bool {
	if !isRawByteArray(s) {
		return false
	}
	return s.MinItems != nil && *s.MinItems == 16 && s.MaxItems != nil && *s.MaxItems == 16
}

// relaxRawJSON walks an inferred schema and relaxes every json.RawMessage /
// []byte JSON-carrier property to a permissive (accept-anything) schema. The SDK
// infers such a Go field as an array of 0-255 bytes, which rejects the real JSON
// object/string the manager actually emits or accepts (QA finding F26); the rest
// of the inferred shape is preserved. The permissive schema carries a
// Description so it marshals as a JSON OBJECT (`{"description":...}`) rather
// than the zero-value Schema{}, which the library marshals as bare JSON `true`
// — valid JSON Schema, but rejected by the TS MCP SDK's Zod validator, which
// requires every property schema to be an object (T11 finding).
func relaxRawJSON(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isRawByteArray(s) {
		*s = jsonschema.Schema{Description: "any JSON value"}
		return
	}
	for _, p := range s.Properties {
		relaxRawJSON(p)
	}
	relaxRawJSON(s.Items)
	relaxRawJSON(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		relaxRawJSON(p)
	}
}

// isRawByteArray reports whether a schema is the jsonschema-go signature of a Go
// []byte / json.RawMessage: an array (possibly nullable) whose items are bytes
// (integer, 0..255).
func isRawByteArray(s *jsonschema.Schema) bool {
	isArray := s.Type == "array"
	for _, t := range s.Types {
		if t == "array" {
			isArray = true
		}
	}
	if !isArray || s.Items == nil {
		return false
	}
	it := s.Items
	if it.Type != "integer" {
		return false
	}
	return it.Minimum != nil && *it.Minimum == 0 && it.Maximum != nil && *it.Maximum == 255
}

// allowNullMaps walks an inferred schema and unions "null" into every Go-map
// node's type. jsonschema-go infers a Go map as a bare {type:"object"}, but a
// nil map marshals to JSON null (unlike a nil slice, which the library already
// types as ["null","array"]). Read models legitimately emit nil maps in early
// project phases (e.g. ProjectState.ActivityConstruction before construction),
// so the honest schema must accept null there — otherwise the SDK's output
// validation rejects a payload the HTTP surface serves fine (QA finding F29).
func allowNullMaps(s *jsonschema.Schema) {
	if s == nil {
		return
	}
	if isMapNode(s) {
		s.Types = []string{"null", "object"}
		s.Type = ""
	}
	for _, p := range s.Properties {
		allowNullMaps(p)
	}
	allowNullMaps(s.Items)
	allowNullMaps(s.AdditionalProperties)
	for _, p := range s.PrefixItems {
		allowNullMaps(p)
	}
}

// isMapNode reports whether a schema node is jsonschema-go's inference of a Go
// map: an object node carrying an additionalProperties element schema. A struct
// is also typed "object" but sets additionalProperties to the false schema
// (Not set), which this distinguishes so struct nodes are never made nullable.
func isMapNode(s *jsonschema.Schema) bool {
	isObject := s.Type == "object"
	for _, t := range s.Types {
		if t == "object" {
			isObject = true
		}
	}
	ap := s.AdditionalProperties
	return isObject && ap != nil && ap.Not == nil
}

func mapManagerError(err error) error {
	var me *fwmanager.Error
	if errors.As(err, &me) {
		return fmt.Errorf("%s: %s", me.Kind.String(), me.Detail)
	}
	return err
}
