// Package httpgen turns a parsed schema-first manager contract into the client
// HTTP layer: stdlib net/http handlers (one per operation, mounted on a
// ServeMux) and a generated OpenAPI 3.1 document. It emits TEXT — it never needs
// the target server to compile — so the manager/import wiring is parameterized
// through Options.
//
// The emitted handlers match the archistrator server recipe (internal/client/web):
// decode -> authorize (fail-closed) -> build the manager Context -> call exactly
// one manager op -> map the framework manager.Error.Kind to an HTTP status ->
// writeJSON. See plan.go for the routing/authz convention.
package httpgen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	projectmodel "github.com/mixofreality-studio/archistrator-platform/framework-go-projectmodel"
)

// Default import paths for the archistrator-platform framework. Overridable via
// Options so the same generator can target a stub layout in tests.
const (
	defaultFrameworkManagerImport = "github.com/mixofreality-studio/archistrator-platform/framework-go/manager"
	defaultSecurityImport         = "github.com/mixofreality-studio/archistrator-platform/framework-go/utilities/security"
	defaultManagerAlias           = "mgr"
	defaultPackage                = "httpapi"
)

// Options configures a generation run.
type Options struct {
	// Package is the package name of the emitted .go file (default "httpapi").
	Package string
	// ManagerImport is the Go import path of the manager package whose interface
	// and I/O types the handlers reference (required for the emitted code to wire
	// up, though generation never compiles it).
	ManagerImport string
	// ManagerAlias is the import alias for ManagerImport (default "mgr").
	ManagerAlias string
	// ManagerIface overrides the interface type name (default: contract interface).
	ManagerIface string
	// FrameworkManagerImport is the framework-go manager package import path.
	FrameworkManagerImport string
	// SecurityImport is the framework-go security utility import path.
	SecurityImport string
	// Title / Version populate the OpenAPI info block.
	Title   string
	Version string
}

func (o Options) withDefaults(doc *projectmodel.Doc) Options {
	if o.Package == "" {
		o.Package = defaultPackage
	}
	if o.ManagerAlias == "" {
		o.ManagerAlias = defaultManagerAlias
	}
	if o.ManagerIface == "" {
		o.ManagerIface = doc.Interface.Name
	}
	if o.FrameworkManagerImport == "" {
		o.FrameworkManagerImport = defaultFrameworkManagerImport
	}
	if o.SecurityImport == "" {
		o.SecurityImport = defaultSecurityImport
	}
	if o.Title == "" {
		o.Title = doc.ManagerBase() + " API"
	}
	if o.Version == "" {
		o.Version = "1.0.0"
	}
	return o
}

// Result holds the generator outputs.
type Result struct {
	// HandlersGo is the gofmt'd Go source for the REST handlers.
	HandlersGo []byte
	// OpenAPIYAML is the OpenAPI 3.1 document as YAML.
	OpenAPIYAML []byte
}

// Generate produces the REST handlers and the OpenAPI document for a contract.
func Generate(doc *projectmodel.Doc, opts Options) (Result, error) {
	opts = opts.withDefaults(doc)
	plans := planOps(doc)
	handlers, err := genHandlers(doc, plans, opts)
	if err != nil {
		return Result{}, err
	}
	oas, err := genOpenAPI(doc, plans, opts)
	if err != nil {
		return Result{}, err
	}
	return Result{HandlersGo: handlers, OpenAPIYAML: oas}, nil
}

func genHandlers(doc *projectmodel.Doc, plans []opPlan, opts Options) ([]byte, error) {
	var b strings.Builder
	alias := opts.ManagerAlias

	extra := handlerExtraImports(doc, plans)
	needStrconv := handlerNeedsStrconv(doc, plans)

	fmt.Fprintf(&b, "// Code generated by framework-go-http-generator. DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source contract: %s\n\n", doc.ID)
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)
	writeHandlerImports(&b, opts, extra, needStrconv)

	fmt.Fprintf(&b, "// Handler binds the %s manager to HTTP per the archistrator client convention.\n", opts.ManagerIface)
	b.WriteString("type Handler struct {\n")
	fmt.Fprintf(&b, "\tManager  %s.%s\n", alias, opts.ManagerIface)
	b.WriteString("\tSecurity security.Security\n")
	b.WriteString("}\n\n")

	// Register.
	b.WriteString("// Register mounts every operation route on mux.\n")
	b.WriteString("func (h *Handler) Register(mux *http.ServeMux) {\n")
	for _, p := range plans {
		fmt.Fprintf(&b, "\tmux.HandleFunc(%q, h.handle%s)\n", p.method+" "+p.path, p.op.Name)
	}
	b.WriteString("}\n\n")

	// Request body types.
	writeRequestBodyTypes(&b, plans, alias)

	// Handlers.
	for _, p := range plans {
		if err := writeHandler(&b, doc, p, opts); err != nil {
			return nil, err
		}
	}

	writeHelpers(&b)

	src := []byte(b.String())
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("httpgen: emitted handlers do not parse: %w\n---\n%s", err, src)
	}
	return formatted, nil
}

// writeHandlerImports emits the import block for the generated handlers file: the
// fixed stdlib imports (plus strconv when a scalar parse is needed), the collected
// x-go-import paths, and the framework/manager imports.
func writeHandlerImports(b *strings.Builder, opts Options, extra []string, needStrconv bool) {
	b.WriteString("import (\n")
	b.WriteString("\t\"encoding/json\"\n")
	b.WriteString("\t\"errors\"\n")
	b.WriteString("\t\"net/http\"\n")
	if needStrconv {
		b.WriteString("\t\"strconv\"\n")
	}
	b.WriteString("\n")
	for _, imp := range extra {
		fmt.Fprintf(b, "\t%q\n", imp)
	}
	if len(extra) > 0 {
		b.WriteString("\n")
	}
	fmt.Fprintf(b, "\tfwmanager %q\n", opts.FrameworkManagerImport)
	fmt.Fprintf(b, "\t%q\n", opts.SecurityImport)
	fmt.Fprintf(b, "\t%s %q\n", opts.ManagerAlias, opts.ManagerImport)
	b.WriteString(")\n\n")
}

// writeRequestBodyTypes emits the per-operation request wrapper struct for every
// op that carries body params (one field per non-path param).
func writeRequestBodyTypes(b *strings.Builder, plans []opPlan, alias string) {
	for _, p := range plans {
		if len(p.bodyParams) == 0 {
			continue
		}
		fmt.Fprintf(b, "type %sRequest struct {\n", projectmodel.LowerFirst(p.op.Name))
		for _, bp := range p.bodyParams {
			fmt.Fprintf(b, "\t%s %s `json:%q`\n",
				upperFirst(bp.param.Name),
				projectmodel.GoType(bp.param.Schema, bp.param.Pointer, alias),
				bp.param.Name)
		}
		b.WriteString("}\n\n")
	}
}

func writeHandler(b *strings.Builder, doc *projectmodel.Doc, p opPlan, opts Options) error {
	alias := opts.ManagerAlias
	op := p.op

	fmt.Fprintf(b, "// handle%s binds %s %s -> %s.%s.\n",
		op.Name, p.method, p.path, alias, op.Name)
	fmt.Fprintf(b, "func (h *Handler) handle%s(w http.ResponseWriter, r *http.Request) {\n", op.Name)

	// argExpr maps each param name to the Go expression passed to the manager call.
	argExpr := map[string]string{}

	// Path params — parsed from the URL path segment (with a 400 on a malformed
	// non-string scalar, e.g. a uuid or int-enum identity).
	for _, pp := range p.pathParams {
		writeScalarBind(b, doc, alias, pp.param, fmt.Sprintf("r.PathValue(%q)", pp.param.Name))
		argExpr[pp.param.Name] = pp.param.Name
	}

	// Body params (POST).
	if len(p.bodyParams) > 0 {
		fmt.Fprintf(b, "\tvar req %sRequest\n", projectmodel.LowerFirst(op.Name))
		b.WriteString("\tif !decodeJSON(w, r, &req) {\n\t\treturn\n\t}\n")
		for _, bp := range p.bodyParams {
			argExpr[bp.param.Name] = "req." + upperFirst(bp.param.Name)
		}
	}

	// Query params (GET) — parsed from the query string (400 on a malformed
	// non-string scalar).
	for _, qp := range p.queryParams {
		writeScalarBind(b, doc, alias, qp.param, fmt.Sprintf("r.URL.Query().Get(%q)", qp.param.Name))
		argExpr[qp.param.Name] = qp.param.Name
	}

	// Authorize (fail-closed).
	b.WriteString("\tprincipal, ok := security.PrincipalFrom(r.Context())\n")
	b.WriteString("\tif !ok {\n\t\twriteError(w, http.StatusUnauthorized, \"unauthenticated\", \"authentication required\")\n\t\treturn\n\t}\n")
	idExpr := "principal.Subject"
	if !p.catalog {
		idExpr = resourceIDExpr(doc, p.pathParams[0].param)
	}
	b.WriteString("\tdecision, err := h.Security.Authorize(r.Context(), principal,\n")
	fmt.Fprintf(b, "\t\tsecurity.Action{Verb: %q},\n", p.verb)
	fmt.Fprintf(b, "\t\tsecurity.ResourceRef{Kind: %q, ID: %s})\n", p.resourceKind, idExpr)
	b.WriteString("\tif err != nil || !decision.Permit {\n\t\twriteError(w, http.StatusForbidden, \"forbidden\", \"not permitted\")\n\t\treturn\n\t}\n")

	// Call the manager.
	b.WriteString("\trc := fwmanager.Context{Context: r.Context(), Principal: principal}\n")
	args := []string{"rc"}
	for _, param := range op.Params {
		args = append(args, argExpr[param.Name])
	}
	call := fmt.Sprintf("h.Manager.%s(%s)", op.Name, strings.Join(args, ", "))
	if op.Result != nil {
		fmt.Fprintf(b, "\tresult, err := %s\n", call)
		b.WriteString("\tif err != nil {\n\t\twriteManagerError(w, err)\n\t\treturn\n\t}\n")
		b.WriteString("\twriteJSON(w, http.StatusOK, result)\n")
	} else {
		fmt.Fprintf(b, "\tif err := %s; err != nil {\n\t\twriteManagerError(w, err)\n\t\treturn\n\t}\n", call)
		b.WriteString("\tw.WriteHeader(http.StatusNoContent)\n")
	}
	b.WriteString("}\n\n")
	return nil
}

// writeScalarBind emits the statements that bind a path/query param to its typed
// Go value `param.Name` from rawExpr (a string expression like r.PathValue("x")).
// A string scalar is a direct (named-type) conversion; a uuid/int/number/bool is
// parsed, with a 400 written and the handler aborted on a malformed value.
func writeScalarBind(b *strings.Builder, doc *projectmodel.Doc, alias string, param projectmodel.Param, rawExpr string) {
	name := param.Name
	ref := param.Schema.RefName()
	kind, _ := doc.ScalarKind(param.Schema)

	switch kind {
	case "uuid":
		if param.Pointer {
			fmt.Fprintf(b, "\t%sVal, err := uuid.Parse(%s)\n", name, rawExpr)
			b.WriteString(badRequest(name))
			fmt.Fprintf(b, "\t%s := &%sVal\n", name, name)
		} else {
			fmt.Fprintf(b, "\t%s, err := uuid.Parse(%s)\n", name, rawExpr)
			b.WriteString(badRequest(name))
		}
	case "integer":
		fmt.Fprintf(b, "\t%sInt, err := strconv.Atoi(%s)\n", name, rawExpr)
		b.WriteString(badRequest(name))
		writeConv(b, name, name+"Int", ref, alias, param.Pointer)
	case "number":
		fmt.Fprintf(b, "\t%sFloat, err := strconv.ParseFloat(%s, 64)\n", name, rawExpr)
		b.WriteString(badRequest(name))
		writeConv(b, name, name+"Float", ref, alias, param.Pointer)
	case "boolean":
		fmt.Fprintf(b, "\t%sBool, err := strconv.ParseBool(%s)\n", name, rawExpr)
		b.WriteString(badRequest(name))
		writeConv(b, name, name+"Bool", ref, alias, param.Pointer)
	default: // string (named-type ref or plain inline string)
		valExpr := rawExpr
		if ref != "" {
			valExpr = fmt.Sprintf("%s.%s(%s)", alias, ref, rawExpr)
		}
		if param.Pointer {
			fmt.Fprintf(b, "\t%sVal := %s\n", name, valExpr)
			fmt.Fprintf(b, "\t%s := &%sVal\n", name, name)
		} else {
			fmt.Fprintf(b, "\t%s := %s\n", name, valExpr)
		}
	}
}

// writeConv binds `name` to the parsed src value, applying a named-type conversion
// (mgr.Kind(src)) when the param is a $ref scalar, and taking its address when the
// param is a pointer.
func writeConv(b *strings.Builder, name, src, ref, alias string, ptr bool) {
	conv := src
	if ref != "" {
		conv = fmt.Sprintf("%s.%s(%s)", alias, ref, src)
	}
	if ptr {
		fmt.Fprintf(b, "\t%sVal := %s\n", name, conv)
		fmt.Fprintf(b, "\t%s := &%sVal\n", name, name)
	} else {
		fmt.Fprintf(b, "\t%s := %s\n", name, conv)
	}
}

func badRequest(name string) string {
	return "\tif err != nil {\n\t\twriteError(w, http.StatusBadRequest, \"bad_request\", \"invalid " +
		name + ": \"+err.Error())\n\t\treturn\n\t}\n"
}

// resourceIDExpr renders the authz ResourceRef.ID expression for the first path
// param: uuid -> .String(); a named string scalar -> string(...).
func resourceIDExpr(doc *projectmodel.Doc, fp projectmodel.Param) string {
	kind, _ := doc.ScalarKind(fp.Schema)
	if kind == "uuid" {
		if fp.Pointer {
			return "(*" + fp.Name + ").String()"
		}
		return fp.Name + ".String()"
	}
	if fp.Pointer {
		return "string(*" + fp.Name + ")"
	}
	return "string(" + fp.Name + ")"
}

// handlerExtraImports collects the sorted, de-duplicated x-go-import paths the
// emitted handlers reference: the uuid package for parse + every param's bound
// foundational type (uuid path/query/body fields).
func handlerExtraImports(doc *projectmodel.Doc, plans []opPlan) []string {
	set := map[string]bool{}
	for _, p := range plans {
		for _, pp := range allParams(p) {
			for _, imp := range projectmodel.GoImports(pp.param.Schema) {
				set[imp] = true
			}
			if kind, ok := doc.ScalarKind(pp.param.Schema); ok && kind == "uuid" {
				set["github.com/google/uuid"] = true
			}
		}
	}
	return sortedKeys(set)
}

// handlerNeedsStrconv reports whether any path/query param is a non-string scalar
// requiring a strconv parse.
func handlerNeedsStrconv(doc *projectmodel.Doc, plans []opPlan) bool {
	for _, p := range plans {
		for _, pp := range append(append([]paramPlan{}, p.pathParams...), p.queryParams...) {
			switch kind, _ := doc.ScalarKind(pp.param.Schema); kind {
			case "integer", "number", "boolean":
				return true
			}
		}
	}
	return false
}

func allParams(p opPlan) []paramPlan {
	out := make([]paramPlan, 0, len(p.pathParams)+len(p.queryParams)+len(p.bodyParams))
	out = append(out, p.pathParams...)
	out = append(out, p.queryParams...)
	out = append(out, p.bodyParams...)
	return out
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] -= 'a' - 'A'
	}
	return string(r)
}
