package httpgen

import (
	"fmt"
	"go/format"
	"strings"
)

// Default package name for the emitted wiring/middleware layer.
const defaultWiringPackage = "httpserver"

// WiringOptions configures a wiring-layer generation run. The wiring layer is
// component-AGNOSTIC: it is the auth/transport middleware (over the platform
// security package) plus the deterministic HTTP composition (NewServer) that
// mounts any set of generated component Handlers behind one auth boundary. It
// imports ONLY the platform security package + the stdlib — never an app/manager
// package — so a single emitted copy composes every component.
type WiringOptions struct {
	// Package is the package name of the emitted wiring files (default
	// "httpserver").
	Package string
	// SecurityImport is the framework-go security utility import path (default the
	// archistrator-platform path). The emitted middleware calls into THIS package:
	// security.Middleware / security.WithPrincipal / security.Validator /
	// security.Principal / security.NewError / security.ErrUnauthenticated.
	SecurityImport string
}

func (o WiringOptions) withDefaults() WiringOptions {
	if o.Package == "" {
		o.Package = defaultWiringPackage
	}
	if o.SecurityImport == "" {
		o.SecurityImport = defaultSecurityImport
	}
	return o
}

// WiringResult holds the emitted wiring-layer files.
type WiringResult struct {
	// MiddlewareGo is the gofmt'd Go source for the auth/transport middleware
	// (DevConfig + AuthMiddleware + denyAllValidator) over the security package.
	MiddlewareGo []byte
	// ServerGo is the gofmt'd Go source for the HTTP composition (the Registrar
	// seam + NewServer + the unauthenticated health probe).
	ServerGo []byte
}

// GenerateWiring produces the component-agnostic auth middleware + HTTP wiring
// layer. Emit it ONCE per consuming package; combined with the per-component
// Generate output (handlers, each exposing Register(mux)) it stands up a complete
// HTTP surface with no hand-written Go in the consuming package.
func GenerateWiring(opts WiringOptions) (WiringResult, error) {
	opts = opts.withDefaults()
	mw, err := genMiddleware(opts)
	if err != nil {
		return WiringResult{}, err
	}
	srv, err := genServer(opts)
	if err != nil {
		return WiringResult{}, err
	}
	return WiringResult{MiddlewareGo: mw, ServerGo: srv}, nil
}

func genMiddleware(opts WiringOptions) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by framework-go-http-generator. DO NOT EDIT.\n")
	b.WriteString("// Auth/transport middleware over the platform security package.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"net/http\"\n\n")
	fmt.Fprintf(&b, "\tsecurity %q\n", opts.SecurityImport)
	b.WriteString(")\n\n")
	b.WriteString(middlewareBody)
	return gofmt(b.String())
}

func genServer(opts WiringOptions) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by framework-go-http-generator. DO NOT EDIT.\n")
	b.WriteString("// Deterministic HTTP composition: mount every generated component's routes\n")
	b.WriteString("// behind the one generated auth middleware, health probes outside it.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", opts.Package)
	b.WriteString("import (\n")
	b.WriteString("\t\"net/http\"\n\n")
	fmt.Fprintf(&b, "\tsecurity %q\n", opts.SecurityImport)
	b.WriteString(")\n\n")
	b.WriteString(serverBody)
	return gofmt(b.String())
}

func gofmt(src string) ([]byte, error) {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return nil, fmt.Errorf("httpgen: emitted wiring does not parse: %w\n---\n%s", err, src)
	}
	return formatted, nil
}

// middlewareBody mirrors the archistrator server recipe
// (internal/client/web/auth.go): in prod validate the bearer access token via the
// security Validator -> put the principal on the context (security.Middleware,
// which calls security.WithPrincipal internally); in dev mode inject a configured
// dev principal directly; a nil validator denies every request (401) so the auth
// boundary still rejects rather than failing to boot.
const middlewareBody = `// DevConfig configures the clearly-gated dev-mode principal injection. It MUST be
// disabled in any IdP-fronted deployment.
type DevConfig struct {
	// Enabled turns on dev-mode principal injection (no token validated).
	Enabled bool
	// Principal is the dev identity injected on every request when Enabled.
	Principal security.Principal
}

// AuthMiddleware returns the middleware mounted in front of the authenticated API
// surface:
//
//   - dev.Enabled: inject dev.Principal on every request (no token required) — the
//     local/systemtest happy path.
//   - otherwise: validate the bearer access token with validator via
//     security.Middleware, which stashes the resulting principal on the request
//     context (readable by the handlers with security.PrincipalFrom). A nil
//     validator denies every request (401), so the auth boundary still rejects
//     rather than failing to boot where no IdP is configured.
func AuthMiddleware(dev DevConfig, validator security.Validator) func(http.Handler) http.Handler {
	if dev.Enabled {
		return func(next http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				next.ServeHTTP(w, r.WithContext(security.WithPrincipal(r.Context(), dev.Principal)))
			})
		}
	}
	if validator == nil {
		validator = denyAllValidator{}
	}
	return security.Middleware(validator)
}

// denyAllValidator rejects every token. It backs the no-IdP-configured, non-dev
// deployment so the auth boundary returns 401 instead of failing to construct a
// validator at boot.
type denyAllValidator struct{}

func (denyAllValidator) ValidateAccessToken(context.Context, string) (security.Principal, error) {
	return security.Principal{}, security.NewError(security.ErrUnauthenticated)
}
`

// serverBody is the deterministic composition glue. The Registrar seam is the
// per-component route-registration func: every generated component Handler
// satisfies it via its Register(mux) method (Go interfaces are structural, so
// NewServer composes Handlers from any number of component packages without
// importing them). NewServer mounts each registrar's /api/v1/... routes behind
// the one auth middleware and the liveness/readiness probes OUTSIDE it
// (unauthenticated), mirroring internal/client/web/web.go.
const serverBody = `// Registrar mounts a component's operation routes onto the authenticated API mux.
// Every generated component Handler satisfies it via its Register method, so
// NewServer composes any set of components behind one auth boundary.
type Registrar interface {
	Register(mux *http.ServeMux)
}

// NewServer builds the complete component HTTP surface and returns it as an
// http.Handler:
//
//   - a stdlib net/http API mux carrying every registrar's /api/v1/... routes,
//     wrapped by the generated auth middleware (AuthMiddleware), and
//   - unauthenticated GET /healthz and GET /readyz probes on the outer mux,
//     OUTSIDE the auth boundary (the middleware rejects unauthenticated requests,
//     so health must not sit behind it).
//
// The consuming composition root constructs the manager-backed Handlers, then
// calls NewServer with them — no hand-written routing glue.
func NewServer(dev DevConfig, validator security.Validator, registrars ...Registrar) http.Handler {
	api := http.NewServeMux()
	for _, reg := range registrars {
		reg.Register(api)
	}

	root := http.NewServeMux()
	// Liveness/readiness — unauthenticated probes, OUTSIDE the auth boundary.
	root.HandleFunc("GET /healthz", handleHealth)
	root.HandleFunc("GET /readyz", handleHealth)
	// Everything under /api/v1/ is authenticated. The component Register patterns
	// carry the full /api/v1/... path, so no prefix stripping is needed.
	authMW := AuthMiddleware(dev, validator)
	root.Handle("/api/v1/", authMW(api))
	return root
}

func handleHealth(w http.ResponseWriter, _ *http.Request) {
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(` + "`" + `{"status":"ok"}` + "`" + `))
}
`
