// Code generated by cmd/modelgen from contract.schema.json; DO NOT EDIT.
// Edit the schema and re-run `make gen-models` instead.

package classifier

import (
	fweng "github.com/mixofreality-studio/archistrator-platform/framework-go/engine"
)

type Classification string

type WidgetID string

// ClassifierEngine is the generated service-contract interface for this component.
type ClassifierEngine interface {
	Classify(rc fweng.Context, id WidgetID) (Classification, error)
}
